// src/angular/projects/spark-angular/src/lib/components/sprk-stepper/sprk-stepper-step/sprk-stepper-step.component.ts
import { OnInit, Component, ElementRef, Input } from '@angular/core';
import * as _ from 'lodash';

@Component({
  selector: 'sprk-stepper-step',
  template: `
    <li
      [ngClass]="getClasses()"
      [attr.data-id]="idString"
      [attr.data-analytics]="analyticsString"
      data-sprk-stepper="step"
    >
      <div
        [ngClass]="{
          'sprk-c-Stepper__step-content': true,
          'sprk-c-Stepper__step-content--has-description':
            variant === 'hasDescription'
        }"
      >
        <a
          class="sprk-c-Stepper__step-header sprk-b-Link sprk-b-Link--plain"
          [attr.aria-controls]="componentID"
          role="tab"
          [attr.id]="componentAriaLabelID"
          href="#"
          [attr.aria-selected]="isSelected"
        >
          <span class="sprk-c-Stepper__step-icon"></span>
          <h3 class="sprk-c-Stepper__step-heading" data-sprk-stepper="heading">
            {{ heading }}
          </h3>
        </a>

        <div
          *ngIf="variant === 'hasDescription'"
          [ngClass]="{
            'sprk-c-Stepper__step-description': true,
            'sprk-u-HideWhenJs': !isSelected
          }"
          id="{{ componentID }}"
          data-sprk-stepper="description"
          [attr.aria-labelledby]="componentAriaLabelID"
          tabindex="0"
          role="tabpanel"
        >
          <p class="sprk-b-TypeBodyTwo">
            <ng-content></ng-content>
          </p>
        </div>
      </div>
    </li>
  `
})
export class SprkStepperStepComponent implements OnInit {
  @Input()
  additionalClasses: string;
  @Input()
  idString: string;
  @Input()
  variant: string;
  @Input()
  isDefaultActive: boolean;
  @Input()
  heading: string;
  @Input()
  analyticsString: string;
  componentID = _.uniqueId('step-');
  componentAriaLabelID = _.uniqueId('step-aria-');
  activeClass = 'sprk-c-Stepper__step--selected';
  isSelected = false;

  constructor(public ref: ElementRef) {}

  getClasses(): string {
    const classArray: string[] = ['sprk-c-Stepper__step'];

    if (this.additionalClasses) {
      this.additionalClasses.split(' ').forEach(className => {
        classArray.push(className);
      });
    }

    if (this.isDefaultActive) {
      classArray.push(this.activeClass);
    }

    return classArray.join(' ');
  }

  ngOnInit(): void {
    if (this.isDefaultActive) {
      this.isSelected = true;
    }
  }
}

// src/react/projects/spark-react/src/SprkStepper/components/SprkStepperStep/SprkStepperStep.js
import React from 'react';
import PropTypes from 'prop-types';
import classnames from 'classnames';

const SprkStepperStep = props => {
  const {
    additionalClasses,
    children,
    title,
    isSelected,
    idString,
    analyticsString,
    variant,
    ...other
  } = props;

  const hasDescription = variant === 'hasDescription';

  return (
    <li
      role="tab"
      className={classnames(
        'sprk-c-Stepper__step',
        isSelected ? 'sprk-c-Stepper__step--selected' : '',
        additionalClasses,
      )}
      aria-selected={isSelected ? 'true' : 'false'}
      data-sprk-stepper="step"
      data-id={idString}
      data-analytics={analyticsString}
      {...other}
    >
      <div
        className={classnames(
          'sprk-c-Stepper__step-content',
          hasDescription ? 'sprk-c-Stepper__step-content--has-description' : '',
          !isSelected ? 'sprk-u-HideWhenJs' : '',
        )}
      >
        <span
          className="
          sprk-c-Stepper__step-header sprk-b-Link sprk-b-Link--plain"
        >
          <span className="sprk-c-Stepper__step-icon" />
          <h3
            className="sprk-c-Stepper__step-heading"
            data-sprk-stepper="heading"
          >
            {title}
          </h3>
        </span>

        {hasDescription && isSelected && (
          <div
            className="sprk-c-Stepper__step-description"
            data-sprk-stepper="description"
          >
            <p className="sprk-b-TypeBodyTwo">{children}</p>
          </div>
        )}
        {/* <div
      class="sprk-c-Stepper__step-description"
      data-sprk-stepper="description"
      id="one-target-1"
      aria-labelledby="one-step-1"
      role="tabpanel">
      <p class="sprk-b-TypeBodyTwo">
        Step 1 Lorem ipsum dolor sit amet consectetur adipisicing elit.
      </p>
    </div> */}
      </div>
    </li>
  );
};

SprkStepperStep.propTypes = {
  // The children that will be rendered inside the component
  children: PropTypes.node,
  // Any additional classes (space-delimited string) to apply to the root
  additionalClasses: PropTypes.string,
  idString: PropTypes.string,
  analyticsString: PropTypes.string,
  title: PropTypes.string,
  isSelected: PropTypes.bool,
  variant: PropTypes.oneOf(['default', 'hasDescription']),
};

SprkStepperStep.defaultProps = {
  variant: 'default',
};

export default SprkStepperStep;
