// angular/projects/spark-angular/src/lib/components/sprk-list-item/sprk-list-item.component.ts
import { Component, Input, TemplateRef, ViewChild } from '@angular/core';

@Component({
  selector: 'sprk-list-item',
  template: `
    <ng-template>
      <ng-content></ng-content>
    </ng-template>
  `
})
export class SprkListItemComponent {
  /**
   * The value supplied will be assigned to the
   * `data-analytics` attribute on the component.
   * Intended for an outside
   * library to capture data.
   */
  @Input()
  analyticsString: string;
  /**
   * The value supplied will be assigned
   * to the `data-id` attribute on the
   * component. This is intended to be
   * used as a selector for automated
   * tools. This value should be unique
   * per page.
   */
  @Input()
  idString: string;
  /**
   * Expects a space separated string
   * of classes to be added to the
   * component.
   */
  @Input()
  additionalClasses: string;

  /**
   * @ignore
   */
  @ViewChild(TemplateRef, { static: true }) content: TemplateRef<any>;
}

// react/src/base/lists/SprkListItem.js
import React from 'react';
import PropTypes from 'prop-types';

const SprkListItem = (props) => {
  const { children, additionalClasses, idString, ...other } = props;

  return (
    <li className={additionalClasses} data-id={idString} {...other}>
      {children}
    </li>
  );
};

SprkListItem.defaultProps = {
  idString: undefined,
  additionalClasses: undefined,
  children: undefined,
};

SprkListItem.propTypes = {
  /**
   * Content to render inside list item.
   */
  children: PropTypes.node,
  /**
   * Assigned to the `data-id` attribute serving as a unique selector for automated tools.
   */
  idString: PropTypes.string,
  /**
   * A space-separated string of classes to add to the outermost container of the component.
   */
  additionalClasses: PropTypes.string,
};

export default SprkListItem;
