// src/angular/projects/spark-core-angular/src/lib/components/sprk-dropdown/sprk-dropdown.component.ts
import {
  Component,
  Input,
  Output,
  ElementRef,
  HostListener,
  EventEmitter
} from '@angular/core';

@Component({
  selector: 'sprk-dropdown',
  template: `
    <div
      [ngClass]="{
        'sprk-c-MastheadMask': isOpen && dropdownType === 'mastheadSelector'
      }"
    >
      <div [ngClass]="{ 'sprk-o-Box': dropdownType === 'mastheadSelector' }">
        <sprk-link
          [additionalClasses]="getTriggerClasses()"
          aria-haspopup="true"
          href="#nogo"
          (click)="toggle($event)"
          [idString]="idString"
          [analyticsString]="analyticsString"
          role="combobox"
        >
          <span [ngClass]="getTriggerTextClasses()">{{ triggerText }}</span>
          <span class="sprk-u-ScreenReaderText">{{ screenReaderText }}</span>
          <sprk-icon
            [iconType]="triggerIconType"
            additionalClasses="sprk-u-mls sprk-c-Icon--stroke-current-color {{ additionalIconClasses }}"
          ></sprk-icon>
        </sprk-link>
      </div>

      <div [ngClass]="getClasses()" *ngIf="isOpen">
        <div
          class="sprk-c-Dropdown__header"
          *ngIf="dropdownType === 'mastheadSelector' || title || selector"
        >
          <h2 class="sprk-c-Dropdown__title sprk-b-TypeBodyTwo" *ngIf="title">
            {{ title }}
          </h2>

          <sprk-link
            *ngIf="selector && !title"
            linkType="plain"
            additionalClasses="sprk-o-Stack sprk-o-Stack--split@xxs sprk-o-Stack--center-column sprk-u-Width-100"
            href="#nogo"
            aria-haspopup="true"
            (click)="toggle($event)"
          >
            <span
              class="sprk-c-Dropdown__title sprk-b-TypeBodyTwo sprk-o-Stack__item sprk-o-Stack__item--flex@xxs"
              >{{ selector }}</span
            >
            <sprk-icon
              [iconType]="triggerIconType"
              additionalClasses="sprk-c-Icon--stroke-current-color sprk-u-mls sprk-c-Icon--toggle sprk-Stack__item {{ additionalIconClasses }}"
            ></sprk-icon>
          </sprk-link>
        </div>

        <ul class="sprk-c-Dropdown__links">
          <li
            class="sprk-c-Dropdown__item"
            *ngFor="let choice of choices; let i = index"
            [attr.data-sprk-dropdown-choice-index]="i"
            (click)="choiceClick($event)"
          >
            <div *ngIf="choice.content; then: content; else: link"></div>
            <ng-template #link>
              <sprk-link
                linkType="unstyled"
                [href]="choice.href || '#nogo'"
                [attr.data-sprk-dropdown-value]="choice.value"
                additionalClasses="sprk-c-Dropdown__link {{ choice.active && 'sprk-c-Dropdown__link--active' }}"
                role="option"
                >{{ choice.text }}
              </sprk-link>
            </ng-template>
            <ng-template #content>
              <sprk-link
                linkType="unstyled"
                [attr.data-sprk-dropdown-value]="choice.value"
                [href]="choice.href || '#nogo'"
                additionalClasses="sprk-c-Dropdown__link {{ choice.active && 'sprk-c-Dropdown__link--active' }}"
                role="option"
              >
                <p class="sprk-b-TypeBodyOne">{{ choice.content.title }}</p>
                <p>{{ choice.content.infoLine1 }}</p>
                <p>{{ choice.content.infoLine2 }}</p>
              </sprk-link>
            </ng-template>
          </li>
        </ul>
        <ng-content select="[sprkDropdownFooter]"></ng-content>
      </div>
    </div>
  `
})
export class SparkDropdownComponent {
  @Input()
  dropdownType = 'base';
  @Input()
  additionalClasses: string;
  @Input()
  additionalIconClasses: string;
  @Input()
  additionalTriggerClasses: string;
  @Input()
  additionalTriggerTextClasses: string;
  @Input()
  idString: string;
  @Input()
  analyticsString: string;
  @Input()
  isOpen = false;
  @Input()
  title: string;
  @Input()
  selector: string;
  @Input()
  choices: any[];
  @Input()
  triggerIconType: string;
  @Input()
  triggerText: string;
  @Input()
  screenReaderText: string;
  @Output()
  choiceMade: EventEmitter<string> = new EventEmitter();

  constructor(public ref: ElementRef) {}

  toggle(event): void {
    event.preventDefault();
    this.isOpen = !this.isOpen;
  }

  @HostListener('document:click', ['$event'])
  onClick(event): void {
    if (
      !this.ref.nativeElement.contains(event.target) ||
      event.target.classList.contains('sprk-c-MastheadMask')
    ) {
      this.hideDropdown();
    }
  }

  @HostListener('document:focusin', ['$event'])
  onFocusin(event): void {
    /* istanbul ignore else: angular focus event isnt setting e.target */
    if (
      !this.ref.nativeElement.contains(event.target) ||
      event.target.classList.contains('sprk-c-MastheadMask')
    ) {
      this.hideDropdown();
    }
  }

  choiceClick(event) {
    event.preventDefault();
    this.clearActiveChoices();
    const choiceIndex = event.currentTarget.getAttribute(
      'data-sprk-dropdown-choice-index'
    );
    const clickedChoice = this.choices[choiceIndex];
    if (
      this.dropdownType === 'informational' ||
      this.dropdownType === 'mastheadSelector'
    ) {
      this.setActiveChoice(event);
      this.updateTriggerText(event);
    }
    this.hideDropdown();
    this.choiceMade.emit(clickedChoice['value']);
  }

  setActiveChoice(event): void {
    const choiceIndex = event.currentTarget.getAttribute(
      'data-sprk-dropdown-choice-index'
    );
    this.choices[choiceIndex]['active'] = true;
  }

  updateTriggerText(event): void {
    const choiceIndex = event.currentTarget.getAttribute(
      'data-sprk-dropdown-choice-index'
    );
    this.triggerText = this.choices[choiceIndex]['value'];
  }

  clearActiveChoices(): void {
    this.choices.forEach((choice: object) => {
      choice['active'] = false;
    });
  }

  hideDropdown(): void {
    this.isOpen = false;
  }

  getClasses(): string {
    const classArray: string[] = ['sprk-c-Dropdown'];

    if (this.additionalClasses) {
      this.additionalClasses.split(' ').forEach(className => {
        classArray.push(className);
      });
    }

    return classArray.join(' ');
  }

  getTriggerClasses(): string {
    const classArray: string[] = ['sprk-b-Link'];

    if (this.additionalTriggerClasses) {
      this.additionalTriggerClasses.split(' ').forEach(className => {
        classArray.push(className);
      });
    }

    return classArray.join(' ');
  }

  getTriggerTextClasses(): string {
    const classArray: string[] = [''];

    if (this.additionalTriggerTextClasses) {
      this.additionalTriggerTextClasses.split(' ').forEach(className => {
        classArray.push(className);
      });
    }

    return classArray.join(' ');
  }
}

// src/react/projects/spark-core-react/src/SprkDropdown/SprkDropdown.js
import React, { Component } from 'react';
import PropTypes from 'prop-types';
import classNames from 'classnames';
import SprkIcon from '../SprkIcon/SprkIcon';

class SprkDropdown extends Component {
  constructor(props) {
    super(props);
    this.state = {
      triggerText: props.defaultTriggerText,
      isOpen: false
    };
    this.toggleDropdownOpen = this.toggleDropdownOpen.bind(this);
    this.closeOnEsc = this.closeOnEsc.bind(this);
    this.closeOnClickOutside = this.closeOnClickOutside.bind(this);
    this.closeDropdown = this.closeDropdown.bind(this);
    this.updateTriggerText = this.updateTriggerText.bind(this);
    this.runChoiceFunction = this.runChoiceFunction.bind(this);
    this.myRef = React.createRef();
  }

  closeOnEsc(e) {
    if (e.key === 'Escape') {
      this.closeDropdown();
    }
  }

  closeOnClickOutside(e) {
    if (!this.myRef.current.contains(e.target)) {
      this.closeDropdown();
    }
  }

  componentWillMount() {
    window.addEventListener('keydown', this.closeOnEsc)
    window.addEventListener('focusin', this.closeOnClickOutside)
    window.addEventListener('click', this.closeOnClickOutside)
  }

  componentWillUnmount() {
    window.removeEventListener('keydown', this.closeOnEsc);
    window.removeEventListener('focusin', this.closeOnClickOutside)
    window.removeEventListener('click', this.closeOnClickOutside)
  }

  closeDropdown() {
    this.setState(prevState => ({
      isOpen: false
    }));
  }

  updateTriggerText(text) {
    this.setState({
      triggerText: text
    })
  }

  runChoiceFunction(text) {
    if (this.props.choiceFunction) {
      this.props.choiceFunction(text);
    }
  }

  toggleDropdownOpen() {
    this.setState(prevState => ({
      isOpen: !prevState.isOpen,
    }));
  }

  render() {
    const {additionalClasses, additionalIconClasses, choices, choiceFunction, defaultTriggerText, iconType, title, variant} = this.props;
    const { triggerText, isOpen } = this.state;
    return (
      <div ref={this.myRef}>
        <a className={classNames(
          "sprk-b-Link",
          "sprk-b-Link--plain",
          {"sprk-u-mrs": variant === 'informational'}
        )} href="#nogo" aria-haspopup="true" role="combobox" onClick={this.toggleDropdownOpen}>
          { variant === 'informational' &&
            <React.Fragment>
              <span data-sprk-dropdown-trigger-text-container="" role="combobox">{triggerText}</span>
              <SprkIcon additionalClasses="sprk-c-Icon--stroke-current-color sprk-u-mls" iconType="chevron-down" />
            </React.Fragment>
          }
          { variant === 'base' &&
            <SprkIcon iconType={iconType} additionalClasses={additionalIconClasses} />
          }
        </a>
        {isOpen &&
          <div className={classNames("sprk-c-Dropdown", additionalClasses)}>
            {title &&
            <div className="sprk-c-Dropdown__header">
              <h2 className="sprk-c-Dropdown__title">{title}</h2>
            </div>
            }
            <ul className="sprk-c-Dropdown__links">
              {choices.map((choice, id) => {
                return(
                  <li className="sprk-c-Dropdown__item" role="option" key={id}>

                    {variant === 'base' &&
                      <a
                        className="sprk-c-Dropdown__link"
                        href={choice.href || '#nogo'}
                        onClick={() => {
                          this.updateTriggerText(choice.text);
                          this.closeDropdown()
                          this.runChoiceFunction(choice.value)
                        }}>{choice.text}</a>
                    }
                    {variant === 'informational' &&
                      <React.Fragment>
                        <a
                          className="sprk-c-Dropdown__link"
                          href={choice.href || '#nogo'}
                          onClick={() => {
                            this.updateTriggerText(choice.content.title);
                            this.closeDropdown()
                            this.runChoiceFunction(choice.value)
                          }}>
                          <p className="sprk-b-TypeBodyOne">{choice.content.title}</p>
                          <p className="sprk-b-TypeBodyTwo">{choice.content.infoLine1}</p>
                          <p className="sprk-b-TypeBodyTwo">{choice.content.infoLine2}</p>
                        </a>
                      </React.Fragment>
                    }
                  </li>);
              })
            }
            </ul>
          </div>
        }
      </div>
    );
  }
}

SprkDropdown.propTypes = {};

SprkDropdown.defaultProps = {
  variant: 'base'
};

export default SprkDropdown;
