// angular/projects/spark-angular/src/lib/components/sprk-link/sprk-link.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { Router } from '@angular/router';
@Component({
  selector: 'sprk-link',
  template: `
    <a
      (click)="handleClick($event)"
      [ngClass]="getClasses()"
      [href]="href"
      [attr.data-analytics]="analyticsString"
      [attr.target]="target"
      [attr.data-id]="idString"
      [attr.disabled]="isDisabled"
      [attr.aria-controls]="ariaControls"
      [attr.aria-label]="ariaLabel"
      [attr.aria-labelledby]="ariaLabelledby"
      [attr.aria-haspopup]="ariaHasPopUp"
      [attr.role]="role"
      [attr.id]="id"
      [attr.aria-current]="ariaCurrent"
      [attr.aria-expanded]="ariaExpanded"
      [attr.aria-hidden]="ariaHidden"
      [attr.aria-selected]="ariaSelected"
    >
      <ng-content></ng-content>
    </a>
  `
})
export class SprkLinkComponent implements OnInit {
  /**
   * @ignore
   */
  constructor(public router: Router) {}

  /**
   * Will cause the appropriate variant type to render.
   * Optional values are: `simple`, `icon`, `unstyled` or `plain`.
   * If omitted, the default Spark Link class is applied.
   * The `unstyled` variant will render an `href` with no
   * CSS classes.
   */
  @Input()
  linkType: string;
  /**
   * The `href` value of the link. If omitted,
   * the href will be set to `#`
   * and the routing will be disabled. If
   * set to reference an ID then the page
   * will scroll to that anchor as normal.
   */
  @Input()
  href: string;
  /**
   * The value supplied will be assigned
   * to the `data-id` attribute on the
   * component. This is intended to be
   * used as a selector for automated
   * tools. This value should be unique
   * per page.
   */
  @Input()
  idString: string;
  /**
   * Value for the `role`
   * attribute of the link.
   */
  @Input()
  role: string;
  /**
   * The string that will be
   * assigned to the `id` attribute of
   * the link.
   */
  @Input()
  id: string;
  /**
   * Expects a value to assign to the
   * `aria-controls` attribute of the link.
   */
  @Input()
  ariaControls: string;
  /**
   * Expects a value to assign to
   * the `aria-labelledby` attribute of the link.
   */
  @Input()
  ariaLabelledby: string;
  /**
   * Expects a value to assign to
   * the `aria-selected` attribute of the link.
   */
  @Input()
  ariaSelected: string;
  /**
   * Expects a value to assign to
   * the `aria-hidden` attribute of the link.
   */
  @Input()
  ariaHidden: string;
  /**
   * Expects a value to assign
   * to the `aria-curren`t attribute of the link.
   */
  @Input()
  ariaCurrent: string;
  /**
   * Expects a value to assign to
   * the `aria-expanded `attribute of the link.
   */
  @Input()
  ariaExpanded: string;
  /**
   * Expects a value to assign
   * to the `aria-haspopup` attribute of the link.
   */
  @Input()
  ariaHasPopUp: string;
  /**
   * Expects a value to assign to
   * the `aria-label` attribute of the link.
   */
  @Input()
  ariaLabel: string;
  /**
   * The value supplied will be assigned to the
   * `data-analytics` attribute on the component.
   * Intended for an outside
   * library to capture data.
   */
  @Input()
  analyticsString: string;
  /**
   * Expects a value to assign to
   * the `target` attribute of the link.
   */
  @Input()
  target: string;
  /**
   * Expects a space separated string
   * of classes to be added to the
   * component.
   */
  @Input()
  additionalClasses: string;
  /**
   * If `true`, will set disabled styles on the link.
   */
  @Input()
  isDisabled: boolean;
  /**
   * By default, the component determines if
   * the `href` is an external or internal link
   * by looking for the `:` character in the
   * `href` string. If external link functionality
   * is desired with an `href` value that contains
   * a `:` set this input to true. This overrides
   * the default and avoids using the Angular Router.
   */
  @Input()
  isExternal = false;

  /**
   * @ignore
   */
  ngOnInit() {
    // Sets the default href if none provided
    if (this.href === '' || this.href === null || this.href === undefined) {
      this.href = '#';
      return;
    }
    // Build jump link's href
    if (this.isJumpLink(this.href)) {
      this.href = `${this.getPathWithoutHash(this.router.url)}${this.href}`;
    }
  }
  /**
   * @ignore
   */
  isExternalLink(value): boolean {
    return new RegExp('^.*:', 'i').test(value);
  }
  /**
   * @ignore
   */
  isJumpLinkWithPage(value): boolean {
    return new RegExp('^.*#.+', 'i').test(value);
  }
  /**
   * @ignore
   */
  isJumpLink(value): boolean {
    return new RegExp('^#.+', 'i').test(value);
  }
  /**
   * @ignore
   */
  isNoActionLink(value): boolean {
    return value === '#';
  }
  /**
   * @ignore
   */
  getPathWithoutHash(value): string {
    return value.split('#')[0];
  }
  /**
   * @ignore
   */
  scrollToId() {
    const elementID = this.href.split('#').pop();
    const element: HTMLElement = document.getElementById(elementID);
    if (element) {
      element.scrollIntoView();
    }
  }
  /**
   * @ignore
   */
  handleClick(event): void {
    // Let browser handle route if external Link
    if (this.isExternalLink(this.href) || this.isExternal) {
      return;
    }

    event.preventDefault();

    // Prevent default and return
    if (this.isNoActionLink(this.href)) {
      return;
    } else if (this.isJumpLinkWithPage(this.href)) {
      if (
        this.getPathWithoutHash(this.href) ===
        this.getPathWithoutHash(this.router.url)
      ) {
        this.scrollToId();
      } else {
        this.router.navigateByUrl(this.href);
      }
    } else {
      this.router.navigateByUrl(this.href);
    }
  }

  /**
   * @ignore
   */
  getClasses(): string {
    const classArray: string[] = [];

    switch (this.linkType) {
      case 'unstyled':
        break;
      case 'simple':
        classArray.push('sprk-b-Link sprk-b-Link--simple');
        break;
      case 'plain':
        classArray.push('sprk-b-Link sprk-b-Link--plain');
        break;
      case 'icon':
        classArray.push(
          'sprk-b-Link sprk-b-Link--simple sprk-b-Link--has-icon'
        );
        break;
      default:
        classArray.push('sprk-b-Link');
        break;
    }

    if (this.isDisabled) {
      classArray.push('sprk-b-Link--disabled');
    }

    if (this.additionalClasses) {
      this.additionalClasses.split(' ').forEach(className => {
        classArray.push(className);
      });
    }

    return classArray.join(' ');
  }
}

// react/src/base/links/SprkLink.js
import React from 'react';
import PropTypes from 'prop-types';
import classnames from 'classnames';

const SprkLink = (props) => {
  const {
    children,
    element,
    variant,
    additionalClasses,
    idString,
    analyticsString,
    onClick,
    href,
    ...other
  } = props;
  const TagName = element || 'a';
  const classNames = classnames(additionalClasses, {
    'sprk-b-Link': variant !== 'unstyled',
    'sprk-b-Link--simple': variant === 'simple',
    'sprk-b-Link--plain': variant === 'plain',
    'sprk-b-Link--disabled': variant === 'disabled',
    'sprk-b-Link--simple sprk-b-Link--has-icon': variant === 'has-icon',
  });

  let link;
  if (href) {
    link = href;
  } else if (TagName === 'a' && !href) {
    link = '#';
  } else {
    link = undefined;
  }

  let clickEvent;
  function handleClick(e) {
    e.preventDefault();
  }
  if (onClick) {
    clickEvent = onClick;
  } else if (!onClick && link === '#') {
    clickEvent = handleClick;
  }

  return (
    <TagName
      className={classNames}
      data-analytics={analyticsString}
      data-id={idString}
      href={link}
      onClick={clickEvent}
      {...other}
    >
      {children}
    </TagName>
  );
};

SprkLink.propTypes = {
  /** The children that will be rendered inside the link. */
  children: PropTypes.node,
  /**
   * Will cause the appropriate variant
   * type to render.
   */
  variant: PropTypes.oneOf([
    'base',
    'simple',
    'has-icon',
    'plain',
    'disabled',
    'unstyled',
  ]),
  /**
   * The value supplied will be assigned to
   * the 'data-id' attribute on the
   * component. This is intended to be used as
   * a selector for automated tools. This value
   * should be unique per page.
   */
  idString: PropTypes.string,
  /**
   * Value assigned to the
   * `data-analytics` attribute on the component.
   * Intended for an outside
   * library to capture data.
   */
  analyticsString: PropTypes.string,
  /**
   * A space-separated list of
   * classes that will be added
   * to the outermost element.
  */
  additionalClasses: PropTypes.string,
  /** The href value for the link. */
  href: PropTypes.string,
  /**
   * Determines if link renders as an anchor tag, or router link.
   */
  element: PropTypes.oneOfType([
    PropTypes.string,
    PropTypes.func,
    PropTypes.elementType
  ]),
  /** The event that will fire when the link is clicked. */
  onClick: PropTypes.func,
};

SprkLink.defaultProps = {
  variant: 'base',
};

export default SprkLink;
