// src/react/projects/spark-react/src/SprkAccordion/components/SprkAccordionItem/SprkAccordionItem.js
import React, { Component } from 'react';
import AnimateHeight from 'react-animate-height';
import PropTypes from 'prop-types';
import classnames from 'classnames';
import SprkIcon from '../../../SprkIcon/SprkIcon';

class SprkAccordionItem extends Component {
  constructor(props) {
    super(props);
    const { isDefaultOpen } = this.props;
    this.state = {
      isOpen: isDefaultOpen || false,
      height: isDefaultOpen ? 'auto' : 0,
    };
    this.toggle = this.toggle.bind(this);
  }

  toggle(e) {
    const { onToggle } = this.props;
    e.preventDefault();
    this.setState(prevState => ({
      isOpen: !prevState.isOpen,
      height: !prevState.isOpen ? 'auto' : 0,
    }));
    if (onToggle) onToggle(e);
  }

  render() {
    const {
      analyticsString,
      idString,
      children,
      heading,
      headingAddClasses,
      additionalClasses,
      contentAddClasses,
      iconAddClasses,
      isDefaultOpen,
      id,
      ...other
    } = this.props;
    const { isOpen, height } = this.state;

    const iconClasses = classnames(
      'sprk-c-Icon--l sprk-c-Icon--toggle sprk-c-Accordion__icon',
      { 'sprk-c-Icon--open': isOpen },
      iconAddClasses,
    );

    const itemClassNames = classnames(
      'sprk-c-Accordion__item',
      { 'sprk-c-Accordion__item--open': isOpen },
      additionalClasses,
    );

    const headingClassNames = classnames(
      'sprk-c-Accordion__heading',
      'sprk-b-TypeDisplaySeven',
      headingAddClasses,
    );

    return (
      <li className={itemClassNames} data-id={idString} {...other}>
        <a
          aria-controls={id}
          className="sprk-c-Accordion__summary"
          data-analytics={analyticsString}
          href="#nogo"
          onClick={this.toggle}
          aria-expanded={isOpen ? 'true' : 'false'}
        >
          <h3 className={headingClassNames}>{heading}</h3>
          <SprkIcon
            iconName="chevron-up-circle-two-color"
            additionalClasses={iconClasses}
          />
        </a>

        <AnimateHeight duration={300} height={height}>
          <div
            className={classnames(
              'sprk-c-Accordion__content',
              contentAddClasses,
            )}
            id={id}
          >
            {children}
          </div>
        </AnimateHeight>
      </li>
    );
  }
}

SprkAccordionItem.defaultProps = {
  analyticsString: '',
  children: '',
  headingAddClasses: '',
  additionalClasses: '',
  idString: '',
  isDefaultOpen: false,
  iconAddClasses: '',
  contentAddClasses: '',
};

SprkAccordionItem.propTypes = {
  // Content for the item
  children: PropTypes.node,
  // Value for the data-analytics attribute on the accordion trigger
  analyticsString: PropTypes.string,
  // The item heading
  heading: PropTypes.string.isRequired,
  // Additional classes for the heading
  headingAddClasses: PropTypes.string,
  // Additional classes for the item
  additionalClasses: PropTypes.string,
  // The data-id value for the accordion item
  idString: PropTypes.string,
  // Used to specify whether the item should be open by default
  isDefaultOpen: PropTypes.bool,
  // Additional classes for the toggle icon
  iconAddClasses: PropTypes.string,
  // Additional classes for the toggle content
  contentAddClasses: PropTypes.string,
};

export default SprkAccordionItem;

// src/angular/projects/spark-core-angular/src/lib/components/sprk-accordion-item/sprk-accordion-item.component.ts
import { Component, Input, OnInit } from '@angular/core';
import * as _ from 'lodash';
import {
  trigger,
  state,
  style,
  animate,
  transition
} from '@angular/animations';

@Component({
  selector: 'sprk-accordion-item',
  template: `
    <li [ngClass]="getClasses()">
      <a
        [attr.aria-controls]="accordion_controls_id"
        [ngClass]="{
          'sprk-c-Accordion__summary': true
        }"
        href="#nogo"
        [attr.data-analytics]="analyticsString"
        [attr.data-id]="idString"
        (click)="toggleAccordion($event)"
      >
        <span [ngClass]="getHeadingClasses()">
          <sprk-icon
            [iconType]="leadingIcon"
            additionalClasses="sprk-c-Icon--current-color sprk-c-Icon--l sprk-u-mrs"
            *ngIf="leadingIcon"
          ></sprk-icon>
          {{ title }}
        </span>

        <sprk-icon
          additionalClasses="sprk-c-Accordion__icon sprk-c-Icon--toggle sprk-c-Icon--l {{ iconStateClass }}"
          [iconType]="currentIconType"
        ></sprk-icon>
      </a>

      <div [@toggleContent]="animState">
        <div
          [id]="accordion_controls_id"
          class="sprk-c-Accordion__content sprk-b-TypeBodyTwo"
        >
          <ng-content></ng-content>
        </div>
      </div>
    </li>
  `,
  animations: [
    trigger('toggleContent', [
      state(
        'closed',
        style({
          height: '0',
          display: 'none',
          overflow: 'hidden'
        })
      ),
      state(
        'open',
        style({
          height: '*',
          display: 'block'
        })
      ),
      transition('closed => open', animate('300ms ease-in')),
      transition('open => closed', animate('300ms ease-out'))
    ])
  ]
})
export class SparkAccordionItemComponent implements OnInit {
  @Input()
  title: string;
  @Input()
  analyticsString: string;
  @Input()
  idString: string;
  @Input()
  additionalClasses: string;
  @Input()
  additionalHeadingClasses: string;
  @Input()
  isOpen = false;
  @Input()
  isActive: boolean;
  @Input()
  iconTypeClosed = 'chevron-up-circle-two-color';
  @Input()
  iconTypeOpen = 'chevron-up-circle-two-color';
  @Input()
  leadingIcon: string;

  componentID = _.uniqueId();
  accordion_controls_id = `accordionHeading__${this.componentID}`;
  public currentIconType = this.iconTypeClosed;
  public iconStateClass = '';
  public animState = 'closed';

  accordionState(): void {
    this.isOpen === false
      ? (this.animState = 'closed')
      : (this.animState = 'open');

    this.isOpen === false
      ? (this.currentIconType = this.iconTypeClosed)
      : (this.currentIconType = this.iconTypeOpen);

    this.isOpen === false
      ? (this.iconStateClass = '')
      : (this.iconStateClass = 'sprk-c-Icon--open');
  }

  toggleAccordion(event): void {
    event.preventDefault();
    this.isOpen = !this.isOpen;
    this.accordionState();
  }

  getClasses(): string {
    const classArray: string[] = ['sprk-c-Accordion__item'];

    if (this.isOpen) {
      classArray.push('sprk-c-Accordion__item--open');
    }

    if (this.isActive) {
      classArray.push('sprk-c-Accordion__item--active');
    }

    if (this.additionalClasses) {
      this.additionalClasses.split(' ').forEach(className => {
        classArray.push(className);
      });
    }

    return classArray.join(' ');
  }

  getHeadingClasses(): string {
    const classArray: string[] = ['sprk-c-Accordion__heading'];

    if (this.additionalHeadingClasses) {
      this.additionalHeadingClasses.split(' ').forEach(className => {
        classArray.push(className);
      });
    }

    return classArray.join(' ');
  }

  ngOnInit() {
    this.accordionState();
  }
}
