// angular/projects/spark-angular/src/lib/components/sprk-modal/sprk-modal.component.ts
import {
  Component,
  EventEmitter,
  HostListener,
  Input,
  Output,
} from '@angular/core';
import { uniqueId } from 'lodash';

@Component({
  selector: 'sprk-modal',
  template: `
    <div
      *ngIf="isVisible"
      [ngClass]="getClasses()"
      role="dialog"
      tabindex="1"
      [attr.aria-labelledby]="heading_id"
      aria-modal="true"
      [attr.aria-describedby]="content_id"
      [attr.data-id]="idString"
    >
      <div class="sprk-o-Stack sprk-o-Stack--large">
        <header class="sprk-c-Modal__header" sprkStackItem>
          <h2
            class="sprk-c-Modal__heading"
            [id]="heading_id"
            sprkHeading
            variant="displayFour"
          >
            {{ title }}
          </h2>

          <button
            *ngIf="modalType != 'wait'"
            class="sprk-c-Modal__icon"
            type="button"
            aria-label="Close Modal"
            [attr.data-analytics]="closeAnalyticsString"
            (click)="closeModal($event)"
          >
            <sprk-icon iconName="close"></sprk-icon>
          </button>
        </header>

        <div
          class="sprk-c-Modal__body sprk-o-Stack sprk-o-Stack--medium"
          sprkStackItem
        >
          <div
            *ngIf="modalType == 'wait'"
            sprkStackItem
            sprkSpinner
            variant="primary"
            size="large"
          ></div>
          <ng-content></ng-content>
        </div>

        <footer
          *ngIf="modalType === 'choice'"
          sprkStackItem
          class="
            sprk-c-Modal__footer
            sprk-o-Stack
            sprk-o-Stack--split@xs
            sprk-o-Stack--end-row
            sprk-o-Stack--medium"
        >
          <div sprkStackItem>
            <button
              sprkButton
              variant="tertiary"
              analyticsString="cancelAnalyticsString"
              (click)="emitCancelClick($event)"
              additionalClasses="sprk-c-Button--full@xs"
            >
              {{ cancelText }}
            </button>
          </div>
          <div sprkStackItem>
            <button
              sprkButton
              analyticsString="confirmAnalyticsString"
              (click)="emitConfirmClick($event)"
              additionalClasses="sprk-c-Button--full@xs"
            >
              {{ confirmText }}
            </button>
          </div>
        </footer>
      </div>
    </div>

    <div
      *ngIf="isVisible"
      class="sprk-c-ModalMask"
      tabindex="-1"
      (click)="closeModal($event)"
    ></div>
  `,
})
export class SprkModalComponent {
  /**
   * Expects a space separated string
   * of classes to be added to the
   * component.
   */
  @Input()
  additionalClasses: string;
  /**
   * The value supplied will be
   * rendered as the text for the Modal title.
   */
  @Input()
  title: string;
  /**
   * This determines the variant of the Modal.
   * Can be `choice`, `info`, or `wait`.
   */
  @Input()
  modalType: string;
  /**
   * The value supplied will be
   * rendered as the text for the confirm button.
   */
  @Input()
  confirmText = 'Confirm';
  /**
   * The value supplied will be rendered
   * as the text for the cancel button.
   */
  @Input()
  cancelText = 'Cancel';
  /**
   * The value supplied will be assigned to the
   * `data-analytics` attribute
   * on the confirm button. Intended
   * for an outside library to capture data.
   */
  @Input()
  confirmAnalyticsString: string;
  /**
   * The value supplied will be assigned to the
   * `data-analytics` attribute
   * on the cancel button. Intended
   * for an outside library to capture data.
   */
  @Input()
  cancelAnalyticsString: string;
  /**
   * The value supplied will be assigned to the
   * `data-analytics` attribute
   * on the close button. Intended
   * for an outside library to capture data.
   */
  @Input()
  closeAnalyticsString: string;
  /**
   * The value supplied will be assigned
   * to the `data-id` attribute on the
   * component. This is intended to be
   * used as a selector for automated
   * tools. This value should be unique
   * per page.
   */
  @Input()
  idString: string;
  /**
   * If `true`, the Modal will be shown.
   * If `false`, the modal will not be shown.
   */
  @Input()
  isVisible = false;
  /**
   * When the Modal is closed the hide event is
   * emitted and a callback function can
   * be triggered if supplied.
   */
  @Output()
  hide = new EventEmitter<any>();
  /**
   * Available when the Modal type is `choice`.
   * The Modal will emit a confirm click event
   * when the confirmation button is clicked.
   * A callback function can be triggered if
   * supplied.
   */
  @Output()
  confirmClick = new EventEmitter<any>();
  /**
   * Available when the Modal type is `choice`.
   * The Modal will emit a cancel click event
   * when the cancel link is clicked.
   * A callback function can be triggered if supplied.
   */
  @Output()
  cancelClick = new EventEmitter<any>();
  /**
   * @ignore
   */
  componentID = uniqueId();
  /**
   * @ignore
   */
  heading_id = `modalHeading__${this.componentID}`;
  /**
   * @ignore
   */
  content_id = `modalContent__${this.componentID}`;

  /**
   * @ignore
   */
  @HostListener('document:keydown', ['$event'])
  handleKeyboardEvent(event: KeyboardEvent) {
    if (this.isVisible && event.key === 'Escape') {
      this.closeModal(event);
    }
  }

  /**
   * @ignore
   */
  constructor() {}

  /**
   * @ignore
   */
  closeModal(event): void {
    if (this.modalType !== 'wait') {
      event.preventDefault();
      this.hide.emit(event);
    }
  }

  /**
   * Emits an event when the confirmation
   * button is clicked.
   */
  emitConfirmClick(event): void {
    this.confirmClick.emit(event);
  }

  /**
   * Emits an event when the cancel
   * link is clicked.
   */
  emitCancelClick(event): void {
    event.preventDefault();
    this.cancelClick.emit(event);
    this.closeModal(event);
  }

  /**
   * @ignore
   */
  getClasses(): string {
    const classArray: string[] = ['sprk-c-Modal'];
    if (this.modalType === 'wait') {
      classArray.push('sprk-c-Modal--wait');
    }

    if (this.additionalClasses) {
      this.additionalClasses.split(' ').forEach((className) => {
        classArray.push(className);
      });
    }

    return classArray.join(' ');
  }
}

// react/src/components/modals/SprkModal.js
/* eslint-disable prefer-template */
/* global window */
/* global document */
import React, { Component } from 'react';
import PropTypes from 'prop-types';
import classnames from 'classnames';
import uniqueId from 'lodash/uniqueId';
import noop from 'lodash/noop';
import SprkSpinner from '../spinners/SprkSpinner';
import CloseButton from './CloseButton';
import ModalFooter from './ModalFooter';
import Mask from './Mask';

class SprkModal extends Component {
  constructor(props) {
    super(props);

    this.aria_id = uniqueId();
    this.closeButtonRef = React.createRef();
    this.footerRef = React.createRef();
    this.containerRef = React.createRef();

    this.cancel = this.cancel.bind(this);
    this.removeListeners = this.removeListeners.bind(this);
    this.attachListeners = this.attachListeners.bind(this);
    this.setInternalFocus = this.setInternalFocus.bind(this);
    this.setExternalFocus = this.setExternalFocus.bind(this);
    this.handleKeyEvents = this.handleKeyEvents.bind(this);
    this.isTabPressed = this.isTabPressed.bind(this);
    this.isEscPressed = this.isEscPressed.bind(this);
    this.getFocusableEls = this.getFocusableEls.bind(this);
    this.isActiveElement = this.isActiveElement.bind(this);
  }

  componentDidMount() {
    // set focus in case the modal is open by default
    this.setInternalFocus();
  }

  shouldComponentUpdate(nextProps) {
    const { isVisible } = this.props;

    // if it's closed now and going to be open
    if (!isVisible && nextProps.isVisible) {
      // save the element with focus so we can apply it later.
      this.focusTarget = document.activeElement;
    }

    return true;
  }

  componentDidUpdate(prevProps) {
    const { isVisible } = this.props;

    // if it was closed and now its open, set the internal focus
    if (isVisible && !prevProps.isVisible) {
      this.setInternalFocus();
    }

    // if it was open and now its closed, set the external focus
    if (prevProps.isVisible && !isVisible) {
      this.setExternalFocus();
    }
  }

  componentWillUnmount() {
    this.removeListeners();
  }

  isTabPressed(e) {
    e.key === 'Tab' || e.keyCode === 9;
  }

  isEscPressed(e) {
    e.key === 'Escape' || e.keyCode === 27;
  }

  getFocusableEls (containerRef) {
    const focusEls = containerRef.querySelectorAll(
      'a[href], area[href],'
      + 'input:not([disabled]),'
      + 'select:not([disabled]),'
      + 'textarea:not([disabled]),'
      + 'button:not([disabled]), [tabindex="0"]',
    );
    return focusEls;
  };

  isActiveElement(elementRef) {
    document.activeElement === elementRef;
  }

  setExternalFocus() {
    const { isVisible, shouldReturnFocusOnClose } = this.props;

    // only if the modal is closed
    if (!isVisible) {
      // only if the flag says to do it
      if (shouldReturnFocusOnClose && this.focusTarget) {
        this.focusTarget.focus();
      }
    }
  }

  setInternalFocus() {
    const { isVisible, variant } = this.props;

    if (isVisible) {
      switch (variant) {
        case 'choice':
          // focus the confirm button
          if (this.footerRef.current) {
            this.footerRef.current.focusConfirm();
          }
          break;
        case 'info':
          // focus the close button
          if (this.closeButtonRef.current) {
            this.closeButtonRef.current.focusButton();
          }
          break;
        case 'wait':
          // focus the whole modal
          if (this.containerRef.current) {
            this.containerRef.current.focus();
          }
          break;
        default:
          // focus the whole modal
          if (this.containerRef.current) {
            this.containerRef.current.focus();
          }
          break;
      }
    }
  }

  cancel() {
    const { variant, cancelClick } = this.props;

    if (variant !== 'wait') {
      cancelClick();
    }

    this.removeListeners();
  }

  handleKeyEvents(e) {
    const { isVisible, variant } = this.props;

    // Return if there is no open modal
    if (!isVisible) {
      return;
    }

    const focusableEls = this.getFocusableEls(this.containerRef.current);
    const firstFocusableEl = focusableEls[0];
    const lastFocusableEl = focusableEls[focusableEls.length - 1];

    if (this.isEscPressed(e)) {
      // Cannot use Esc to close Wait Modals
      if (variant !== 'wait') {
        e.preventDefault();
        this.cancel();
      }
    }

    if (this.isTabPressed(e)) {
      if (variant === 'wait') {
        e.preventDefault();
        // Wait modals only ever focus the modal container
        this.containerRef.current.focus();
      } else if (e.shiftKey) {
        if (this.isActiveElement(firstFocusableEl)) {
          // underflow to the end
          e.preventDefault();
          lastFocusableEl.focus();
        }
      } else if (this.isActiveElement(lastFocusableEl)) {
        // overflow to the beginning
        e.preventDefault();
        firstFocusableEl.focus();
      }
    }
  }

  attachListeners() {
    window.addEventListener('keydown', this.handleKeyEvents);
  }

  removeListeners() {
    window.removeEventListener('keydown', this.handleKeyEvents);
  }

  render() {
    const {
      additionalClasses,
      analyticsString,
      children,
      title,
      variant,
      confirmText,
      cancelText,
      idString,
      isVisible,
      confirmClick,
      cancelClick,
      shouldReturnFocusOnClose,
      closeIcon,
      closeAnalyticsString,
      maskAnalyticsString,
      confirmAnalyticsString,
      cancelAnalyticsString,
      ...rest
    } = this.props;

    if (!isVisible) {
      return null;
    }

    const isWait = variant === 'wait';
    const isChoice = variant === 'choice';

    this.attachListeners();

    return (
      <>
        <div
          className={classnames(
            'sprk-c-Modal',
            isWait ? 'sprk-c-Modal--wait' : '',
            additionalClasses,
          )}
          role="dialog"
          aria-modal="true"
          aria-labelledby={'modalHeading_' + this.aria_id}
          aria-describedby={'modalContent_' + this.aria_id}
          data-analytics={analyticsString}
          data-id={idString}
          ref={this.containerRef}
          // eslint-disable-next-line jsx-a11y/no-noninteractive-tabindex
          tabIndex="0"
          {...rest}
        >
          <div className="sprk-o-Stack sprk-o-Stack--large">
            <header className="sprk-o-Stack__item sprk-c-Modal__header">
              <h2
                className="sprk-c-Modal__heading sprk-b-TypeDisplayFour"
                id={'modalHeading_' + this.aria_id}
              >
                {title}
              </h2>

              {!isWait && (
                <CloseButton
                  clickAction={this.cancel}
                  ref={this.closeButtonRef}
                  iconName={closeIcon}
                  analyticsString={closeAnalyticsString}
                />
              )}
            </header>

            <div>
              <div
                className="sprk-o-Stack__item sprk-c-Modal__body sprk-o-Stack sprk-o-Stack--medium"
                id={'modalContent_' + this.aria_id}
              >
                {isWait && (
                  <SprkSpinner
                    size="large"
                    lightness="dark"
                    additionalClasses="sprk-o-Stack__item"
                  />
                )}
                <div className="sprk-b-TypeBodyTwo">
                  {children}
                </div>
              </div>

              {isChoice && (
                <ModalFooter
                  confirmClick={confirmClick}
                  cancelClick={this.cancel}
                  confirmText={confirmText}
                  cancelText={cancelText}
                  ref={this.footerRef}
                  confirmAnalyticsString={confirmAnalyticsString}
                  cancelAnalyticsString={cancelAnalyticsString}
                />
              )}
            </div>
          </div>
        </div>

        <Mask clicked={this.cancel} analyticsString={maskAnalyticsString} />
      </>
    );
  }
}

SprkModal.propTypes = {
  /** Content to render inside modal. */
  children: PropTypes.node,
  /** The modal heading text. */
  title: PropTypes.string,
  /** Determines style of modal to render. */
  variant: PropTypes.oneOf(['wait', 'info', 'choice']),
  /** Text to render on the confirmation button. */
  confirmText: PropTypes.string,
  /** Text to render on the cancel button. */
  cancelText: PropTypes.string,
  /** Sets whether the modal is displayed. */
  isVisible: PropTypes.bool,
  /** The function that runs when confirm choice is clicked. */
  confirmClick: PropTypes.func,
  /**
   * The function that runs when the cancel choice is clicked.
   * Cancel choices includ clicking the X, clicking the Mask, or pressing Esc.
  */
  cancelClick: PropTypes.func,
  /**
   * 	If true, focus will automatically be returned to the last-focused item when the modal is closed.
   */
  shouldReturnFocusOnClose: PropTypes.bool,
  /**
   * Expects a space separated string
   * of classes to be added to the
   * modal's outermost container.
   */
  additionalClasses: PropTypes.string,
  /**
   * The value supplied will be assigned to the
   * `data-analytics` attribute on the component.
   * Intended for an outside
   * library to capture data.
   */
  analyticsString: PropTypes.string,
  /**
   * The value supplied will be assigned
   * to the `data-id` attribute on the
   * component. This is intended to be
   * used as a selector for automated
   * tools. This value should be unique
   * per page.
   */
  idString: PropTypes.string,
  // TODO: Actually give this a default
  /**
   * The icon name to use for the close button in the modal. Defaults to "close".
   */
  closeIcon: PropTypes.string,
  /** The string to pass to the CloseButton as analyticsString */
  closeAnalyticsString: PropTypes.string,
  /** The string to pass to the modal mask to be used for the data-analytics attribute. */
  maskAnalyticsString: PropTypes.string,
  /** The string to pass to the modal footer for the data-analytics attribute. */
  confirmAnalyticsString: PropTypes.string,
  /** The string to pass to the modal footer for the data-analytics attribute. */
  cancelAnalyticsString: PropTypes.string,
};

SprkModal.defaultProps = {
  variant: 'choice',
  confirmText: 'Confirm',
  cancelText: 'Cancel',
  /** Sets whether the modal is displayed. */
  isVisible: false,
  confirmClick: noop,
  cancelClick: noop,
  shouldReturnFocusOnClose: true,
};

export default SprkModal;
