// angular/projects/spark-angular/src/lib/components/sprk-masthead/components/sprk-masthead-accordion-item/sprk-masthead-accordion-item.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { uniqueId } from 'lodash';
import { toggleAnimations } from '../../../sprk-toggle/sprk-toggle-animations';

@Component({
  selector: 'sprk-masthead-accordion-item',
  template: `
    <li [ngClass]="getClasses()">
      <div sprkStackItem class="sprk-c-MastheadAccordion__summary-content">
        <button
          [attr.aria-controls]="accordion_controls_id"
          class="sprk-c-MastheadAccordion__summary"
          [attr.data-analytics]="analyticsString"
          [attr.data-id]="idString"
          (click)="toggleAccordion($event)"
          [attr.aria-expanded]="isOpen"
          type="button"
        >
          <span [ngClass]="getHeadingClasses()">
            <sprk-icon
              [iconName]="leadingIcon"
              additionalClasses="sprk-c-Icon--filled-current-color sprk-c-Icon--xl sprk-c-Icon--toggle sprk-u-mrs"
              *ngIf="leadingIcon"
            ></sprk-icon>
            {{ heading }}
          </span>

          <sprk-icon
            additionalClasses="sprk-c-MastheadAccordion__icon sprk-c-Icon--filled-current-color sprk-c-Icon--stroke-current-color sprk-c-Icon--toggle {{
              iconStateClass
            }}"
            [iconName]="currentIconType"
          ></sprk-icon>
        </button>
      </div>

      <div [@toggleContent]="animState">
        <div [id]="accordion_controls_id"><ng-content></ng-content></div>
      </div>
    </li>
  `,
  animations: [toggleAnimations.toggleContent],
})
export class SprkMastheadAccordionItemComponent implements OnInit {
  /**
   * The value supplied will be used
   * as the heading for the item.
   */
  @Input()
  heading: string;
  /**
   * The value supplied will be assigned to the
   * `data-analytics` attribute on the component.
   * Intended for an outside
   * library to capture data.
   */
  @Input()
  analyticsString: string;
  /**
   * The value supplied will be assigned
   * to the `data-id` attribute on the
   * component. This is intended to be
   * used as a selector for automated
   * tools. This value should be unique
   * per page.
   */
  @Input()
  idString: string;
  /**
   * Expects a space separated string
   * of classes to be added to the
   * component.
   */
  @Input()
  additionalClasses: string;
  /**
   * Expects a space separated string
   * of classes to be added to the
   * heading.
   */
  @Input()
  additionalHeadingClasses: string;
  /**
   * If `true`, the Masthead accordion item
   * will be open when it is rendered.
   */
  @Input()
  isOpen = false;
  /**
   * If `true`, the Masthead accordion item
   * will be active when it is rendered.
   */
  @Input()
  isActive: boolean;
  /**
   * The name of the icon to use
   * for the clickable close icon.
   */
  @Input()
  iconTypeClosed = 'chevron-down';
  /**
   * The name of the icon to use
   * for the clickable open icon.
   */
  @Input()
  iconTypeOpen = 'chevron-down';
  /**
   * Expects a name of an icon to use
   * as a leading icon for the Masthead accordion item.
   */
  @Input()
  leadingIcon: string;

  /**
   * @ignore
   */
  componentID = uniqueId();
  /**
   * @ignore
   */
  accordion_controls_id = `accordionHeading__${this.componentID}`;
  /**
   * @ignore
   */
  public currentIconType = this.iconTypeClosed;
  /**
   * @ignore
   */
  public iconStateClass = '';
  /**
   * @ignore
   */
  public animState = 'closed';

  /**
   * This applies the correct styles to the item
   * when it is open or closed.
   */
  accordionState(): void {
    this.isOpen === false
      ? (this.animState = 'closed')
      : (this.animState = 'open');

    this.isOpen === false
      ? (this.currentIconType = this.iconTypeClosed)
      : (this.currentIconType = this.iconTypeOpen);

    this.isOpen === false
      ? (this.iconStateClass = '')
      : (this.iconStateClass = 'sprk-c-Icon--open');
  }
  /**
   * Updates the isOpen state when
   * the item is toggled.
   */
  toggleAccordion(event): void {
    event.preventDefault();
    this.isOpen = !this.isOpen;
    this.accordionState();
  }

  /**
   * @ignore
   */
  getClasses(): string {
    const classArray: string[] = [
      'sprk-c-MastheadAccordion__item',
      'sprk-u-Overflow--hidden',
    ];

    if (this.isOpen) {
      classArray.push('sprk-c-MastheadAccordion__item--open');
    }

    if (this.isActive) {
      classArray.push('sprk-c-MastheadAccordion__item--active');
    }

    if (this.additionalClasses) {
      this.additionalClasses.split(' ').forEach((className) => {
        classArray.push(className);
      });
    }

    return classArray.join(' ');
  }
  /**
   * @ignore
   */
  getHeadingClasses(): string {
    const classArray: string[] = ['sprk-c-MastheadAccordion__heading'];

    if (this.additionalHeadingClasses) {
      this.additionalHeadingClasses.split(' ').forEach((className) => {
        classArray.push(className);
      });
    }

    return classArray.join(' ');
  }

  ngOnInit() {
    this.accordionState();
  }
}

// react/src/components/masthead/components/SprkMastheadAccordionItem/SprkMastheadAccordionItem.js
import React, { Component } from 'react';
import AnimateHeight from 'react-animate-height';
import PropTypes from 'prop-types';
import classNames from 'classnames';
import uniqueId from 'lodash/uniqueId';
import SprkIcon from '../../../icons/SprkIcon';
import SprkLink from '../../../../base/links/SprkLink';

class SprkMastheadAccordionItem extends Component {
  constructor(props) {
    super(props);
    const { defaultOpen, subNavLinks } = this.props;
    this.state = {
      isOpen: defaultOpen || false,
      height: defaultOpen ? 'auto' : 0,
      subNavLinks: subNavLinks.map(link => ({ id: uniqueId(), ...link })),
    };
    this.toggleAccordionOpen = this.toggleAccordionOpen.bind(this);
  }

  toggleAccordionOpen() {
    this.setState(prevState => ({
      isOpen: !prevState.isOpen,
      height: !prevState.isOpen ? 'auto' : 0,
    }));
  }

  render() {
    const {
      additionalClasses,
      analyticsString,
      defaultOpen,
      element,
      href,
      idString,
      isActive,
      isButton,
      leadingIcon,
      subNavLinks,
      text,
      ...rest
    } = this.props;
    const { isOpen, height, subNavLinks: stateLinks } = this.state;
    const TagName = element;
    return (
      <li
        className={classNames(
          'sprk-c-MastheadAccordion__item',
          { 'sprk-c-MastheadAccordion__item--open': isOpen },
          { 'sprk-c-MastheadAccordion__item--active': isActive },
          { 'sprk-o-Box': isButton },
          additionalClasses,
        )}
        data-analytics={analyticsString}
        data-id={idString}
      >
        {stateLinks.length > 0 && (
          <React.Fragment>
            <SprkLink
              variant="unstyled"
              additionalClasses="sprk-c-MastheadAccordion__summary"
              onClick={this.toggleAccordionOpen}
              aria-expanded={isOpen ? 'true' : 'false'}
            >
              <span className="sprk-b-TypeBodyOne sprk-c-MastheadAccordion__heading">
                {text}
              </span>
              <SprkIcon
                additionalClasses={classNames({ 'sprk-c-Icon--open': isOpen })}
                iconName="chevron-down"
              />
            </SprkLink>
            <AnimateHeight duration={300} height={height}>
              <ul className="sprk-b-List sprk-b-List--bare sprk-c-MastheadAccordion__details">
                {stateLinks.map((subnavlink) => {
                  const {
                    element: innerElement,
                    href: innerHref,
                    id: innerId,
                    text: innerText,
                    ...innerRest
                  } = subnavlink;
                  const InnerTagName = innerElement || 'a';
                  return (
                    <li key={innerId}>
                      <InnerTagName
                        href={
                          InnerTagName === 'a' ? innerHref || '#nogo' : undefined
                        }
                        className={classNames(
                          'sprk-b-Link sprk-b-Link--plain sprk-c-Masthead__link',
                        )}
                        {...innerRest}
                      >
                        {innerText}
                      </InnerTagName>
                    </li>
                  );
                })}
              </ul>
            </AnimateHeight>
          </React.Fragment>
        )}
        {stateLinks.length <= 0 && (
          <TagName
            className={classNames(
              { 'sprk-c-MastheadAccordion__summary': !isButton },
              {
                'sprk-c-Button sprk-c-Button--secondary sprk-c-Button--compact sprk-c-Button--full@s': isButton,
              },
            )}
            href={TagName === 'a' ? href : undefined}
            {...rest}
          >
            <span
              className={classNames({
                'sprk-c-MastheadAccordion__heading': !isButton,
              })}
            >
              {leadingIcon && (
                <SprkIcon
                  additionalClasses="sprk-c-Icon--stroke-current-color sprk-c-Icon--l sprk-u-mrs"
                  iconName={leadingIcon}
                />
              )}
              {text}
            </span>
          </TagName>
        )}
      </li>
    );
  }
}

SprkMastheadAccordionItem.propTypes = {
  /**
   * Expects a space separated string
   * of classes to be added to the
   * component.
   */
  additionalClasses: PropTypes.string,
  /**
   * The value supplied will be assigned to the
   * `data-analytics` attribute on the component.
   * Intended for an outside
   * library to capture data.
   */
  analyticsString: PropTypes.string,
  /**
   * Decides whether the Accordion item should render open by default.
   */
  defaultOpen: PropTypes.bool,
  /**
   * The element to render, could be 'a' or a Component.
   */
  element: PropTypes.oneOfType([PropTypes.string, PropTypes.func]),
  /**
   * Assigned to the `href` attribute if element is 'a'.
   */
  href: PropTypes.string,
  /**
   * The value supplied will be assigned
   * to the `data-id` attribute on the
   * component. This is intended to be
   * used as a selector for automated
   * tools. This value should be unique
   * per page.
   */
  idString: PropTypes.string,
  /** Decides if the outer link is the active link.*/
  isActive: PropTypes.bool,
  /** Will render the element as a button with correct style. */
  isButton: PropTypes.bool,
  /** The name of the icon to render before the text. */
  leadingIcon: PropTypes.string,
  /** An array of link objects that builds the sub nav. */
  subNavLinks: PropTypes.arrayOf(
    PropTypes.shape({
      /** The element to render, could be 'a' or a Component. */
      element: PropTypes.oneOfType([PropTypes.string, PropTypes.func]),
      /** Assigned to the href attribute if element is 'a'. */
      href: PropTypes.string,
      /** The element to render, could be 'a' or a Component. */
      text: PropTypes.string,
    }),
  ),
  /** The text inside the element. */
  text: PropTypes.string,
};

SprkMastheadAccordionItem.defaultProps = {
  defaultOpen: false,
  element: 'a',
  isActive: false,
  isButton: false,
  subNavLinks: [],
  href: '#nogo',
};

export default SprkMastheadAccordionItem;
