// react/src/components/stepper/SprkStepper.js
import React, { Component } from 'react';
import PropTypes from 'prop-types';
import classnames from 'classnames';
import SprkStepperStep from './components/SprkStepperStep/SprkStepperStep';
import SprkStepperSlider from './components/SprkStepperSlider/SprkStepperSlider';

class SprkStepper extends Component {
  constructor(props) {
    super(props);

    this.handleStepClick = this.handleStepClick.bind(this);
    this.handleKeyEvents = this.handleKeyEvents.bind(this);
    this.retreatTab = this.retreatTab.bind(this);
    this.advanceTab = this.advanceTab.bind(this);
    this.jumpToFirstTab = this.jumpToFirstTab.bind(this);
    this.jumpToLastTab = this.jumpToLastTab.bind(this);
    this.getInitialActiveStep = this.getInitialActiveStep.bind(this);
    this.setNewActiveStep = this.setNewActiveStep.bind(this);
    this.updateSliderPosition = this.updateSliderPosition.bind(this);

    this.state = {
      activeStepIndex: this.getInitialActiveStep(),
      sliderStyle: { top: 0 },
    };
  }

  handleStepClick(e, indexOfStep) {
    this.setNewActiveStep(indexOfStep);
  }

  handleKeyEvents(event) {
    const keys = {
      end: 35,
      home: 36,
      left: 37,
      right: 39,
      up: 38,
      down: 40,
    };

    if (event.keyCode === keys.left || event.keyCode === keys.up) {
      event.preventDefault();
      this.retreatTab();
    } else if (event.keyCode === keys.right || event.keyCode === keys.down) {
      event.preventDefault();
      this.advanceTab();
    } else if (event.keyCode === keys.home) {
      event.preventDefault();
      this.jumpToFirstTab();
    } else if (event.keyCode === keys.end) {
      event.preventDefault();
      this.jumpToLastTab();
    }
  }

  retreatTab() {
    const { activeStepIndex } = this.state;
    const { children } = this.props;

    let newIndex = activeStepIndex - 1;

    if (newIndex < 0) {
      newIndex = children.length - 1;
    }

    this.setNewActiveStep(newIndex);
  }

  advanceTab() {
    const { activeStepIndex } = this.state;
    const { children } = this.props;

    let newIndex = activeStepIndex + 1;

    if (newIndex >= children.length) {
      newIndex = 0;
    }

    this.setNewActiveStep(newIndex);
  }

  jumpToFirstTab() {
    this.setNewActiveStep(0);
  }

  jumpToLastTab() {
    const { children } = this.props;

    this.setNewActiveStep(children.length - 1);
  }

  getInitialActiveStep() {
    const { children } = this.props;

    // the first step is active by default
    let initialIndex = 0;

    children.forEach((child, index) => {
      if (child.props.isSelected) {
        initialIndex = index;
      }
    });

    return initialIndex;
  }

  setNewActiveStep(stepIndex) {
    this.setState({ activeStepIndex: stepIndex });
  }

  updateSliderPosition(position) {
    this.setState({
      sliderStyle: {
        top: position,
      },
    });
  }

  render() {
    const {
      additionalClasses,
      children,
      idString,
      hasDarkBackground,
      ...other
    } = this.props;
    const { activeStepIndex, sliderStyle } = this.state;

    let hasDesc = false;
    let descCount = 0;

    // count the number of Step children with descriptions. If that doesn't match the total number of children,
    // warn the user
    children.forEach((child, index) => {
      if (child.type.name === SprkStepperStep.name && child.props.children) {
        descCount++;
      }
    });

    if (descCount === children.length) {
      hasDesc = true;
    } else if (descCount > 0) {
      console.warn(
        'SprkStepper: If any step has a description, they all must have a description.',
      );
    }

    let stepper = (
      <ol
        className={classnames(
          'sprk-c-Stepper',
          hasDarkBackground ? 'sprk-c-Stepper--has-dark-bg' : '',
          !hasDarkBackground ? additionalClasses : '',
        )}
        role="tablist"
        aria-orientation="vertical" // todo change based on window width
        data-id={idString}
        {...other}
      >
        {hasDesc && (
          <SprkStepperSlider
            title={children[activeStepIndex].props.title} // active title
            contents={children[activeStepIndex].props.children} // active contents
            sliderStyle={sliderStyle}
          />
        )}

        {children.map((childNode, index) => {
          // Ignore all child nodes that are not SprkStepperSteps
          if (childNode.type.name !== SprkStepperStep.name) return null;

          return (
            <SprkStepperStep
              {...childNode.props}
              key={childNode.props.id || index}
              isSelected={activeStepIndex === index}
              tabIndex={0}
              additionalClasses={classnames(
                index === 0 ? 'sprk-c-Stepper__step--first' : '',
                index === children.length - 1
                  ? 'sprk-c-Stepper__step--last'
                  : '',
                childNode.props.additionalClasses,
              )}
              onKeyDown={this.handleKeyEvents}
              onClick={event => {
                childNode.props.onClick();
                this.handleStepClick(event, index);
              }}
              renderCallback={this.updateSliderPosition}
              hasDescription={hasDesc}
              hasDarkBackground={hasDarkBackground}
            />
          );
        })}
      </ol>
    );

    if (hasDarkBackground) {
      return (
        <div
          className={classnames(
            'sprk-u-BackgroundColor--blue sprk-o-Box sprk-o-Box--large',
            additionalClasses,
          )}
        >
          {stepper}
        </div>
      );
    }

    return stepper;
  }
}

SprkStepper.propTypes = {
  /**
   * If true, the Stepper will be
   * rendered on a dark background.
   * `($sprk-blue)`
  */
  hasDarkBackground: PropTypes.bool,
  /**
   * Expects a space separated string
   * of classes to be added to the
   * component.
   */
  additionalClasses: PropTypes.string,
  /**
   * Value assigned
   * to the `data-id` attribute on the
   * component. This is intended to be
   * used as a selector for automated
   * tools. This value should be unique
   * per page.
   */
  idString: PropTypes.string,
};

export default SprkStepper;

// angular/projects/spark-angular/src/lib/components/sprk-stepper/sprk-stepper.component.ts
import { AfterViewInit, Component, ElementRef, Input } from '@angular/core';

@Component({
  selector: 'sprk-stepper',
  template: `
    <ol
      [ngClass]="getClasses()"
      data-sprk-stepper="container"
      [attr.data-id]="idString"
      role="tablist"
      aria-orientation="vertical"
    >
      <ng-content></ng-content>
    </ol>
  `
})
export class SprkStepperComponent implements AfterViewInit {
  /**
   * Expects a space separated string
   * of classes to be added to the
   * component.
   */
  @Input()
  additionalClasses: string;
  /**
   * The value supplied will be assigned
   * to the `data-id` attribute on the
   * component. This is intended to be
   * used as a selector for automated
   * tools. This value should be unique
   * per page.
   */
  @Input()
  idString: string;
  /**
   * If `true`, this will apply the correct styles
   * the to the Stepper for when it is on a dark background.
   */
  @Input()
  hasDarkBg: boolean;

  constructor(public ref: ElementRef) {}

  /**
   * @ignore
   */
  resetTabs(tabs, tabpanels, activeClass) {
    tabs.forEach(tab => {
      tab.classList.remove(activeClass || 'sprk-c-Tabs__button--active');
      tab.removeAttribute('tabindex');
      tab.setAttribute('aria-selected', 'false');
      tabpanels.forEach(panel => {
        panel.classList.add('sprk-u-HideWhenJs');
      });
    });
  }

  /**
   * @ignore
   */
  handleTabKeydown(e, steps, stepPanels, activeClass, sliderEl) {
    // TODO: implement
  }

  /**
   * @ignore
   */
  setActiveTab(tab, tabpanel, activeClass) {
    tab.classList.add(activeClass || 'sprk-c-Tabs__button--active');
    tab.setAttribute('tabindex', '0');
    tab.setAttribute('aria-selected', 'true');
    if (tabpanel) {
      tabpanel.classList.remove('sprk-u-HideWhenJs');
    }
    tab.focus();
  }

  /**
   * @ignore
   */
  getClasses(): string {
    const classArray: string[] = ['sprk-c-Stepper'];

    if (this.additionalClasses) {
      this.additionalClasses.split(' ').forEach(className => {
        classArray.push(className);
      });
    }

    if (this.hasDarkBg) {
      classArray.push('sprk-c-Stepper--has-dark-bg');
    }

    return classArray.join(' ');
  }

  /**
   * @ignore
   */
  bindUIEvents(): void {
    const steps = this.ref.nativeElement.querySelectorAll(
      '[data-sprk-stepper="step"]'
    );
    const stepPanels = this.ref.nativeElement.querySelectorAll(
      '[role="tabpanel"]'
    );
    const activeClass = 'sprk-c-Stepper__step--selected';
    const container = this.ref.nativeElement.querySelector(
      '[data-sprk-stepper="container"]'
    );
    const hasSlideEffect = this.ref.nativeElement.querySelector(
      '[data-sprk-stepper="description"]'
    );
    let sliderEl;
    if (!steps[0]) {
      return;
    }
    steps[0].classList.add('sprk-c-Stepper__step--first');
    steps[steps.length - 1].classList.add('sprk-c-Stepper__step--last');

    // If the stepper has stepper descriptions then build slider
    if (hasSlideEffect) {
      sliderEl = document.createElement('li');
      sliderEl.classList.add('sprk-c-Stepper__slider');
      sliderEl.setAttribute('data-sprk-stepper', 'slider');
      container.prepend(sliderEl);
    }

    steps.forEach((step, index) => {
      const stepTrigger = step.querySelector('[role="tab"]');
      if (!stepTrigger) {
        return;
      }
      if (hasSlideEffect) {
        step.classList.add('sprk-c-Stepper__step--has-slider');
      }

      stepTrigger.addEventListener('click', event => {
        event.preventDefault();
        this.resetTabs(steps, stepPanels, activeClass);
        this.setActiveTab(step, stepPanels[index], activeClass);
      });
    });

    this.ref.nativeElement.addEventListener('keydown', e => {
      this.handleTabKeydown(e, steps, stepPanels, activeClass, sliderEl);
    });
  }

  ngAfterViewInit(): void {
    this.bindUIEvents();
  }
}
