// src/react/projects/spark-core-react/src/SprkDropdown/SprkDropdown.js
import React, { Component } from 'react';
import PropTypes from 'prop-types';
import classNames from 'classnames';
import SprkIcon from '../SprkIcon/SprkIcon';
import { uniqueId } from 'lodash';

class SprkDropdown extends Component {
  constructor(props) {
    super(props);
    this.state = {
      triggerText: props.defaultTriggerText,
      isOpen: false,
      choiceItems: props.choices.items.map(item => { return { id: uniqueId(), ...item}; })
    };
    this.toggleDropdownOpen = this.toggleDropdownOpen.bind(this);
    this.closeOnEsc = this.closeOnEsc.bind(this);
    this.closeOnClickOutside = this.closeOnClickOutside.bind(this);
    this.closeDropdown = this.closeDropdown.bind(this);
    this.updateTriggerText = this.updateTriggerText.bind(this);
    this.runChoiceFunction = this.runChoiceFunction.bind(this);
    this.myRef = React.createRef();
  }

  closeOnEsc(e) {
    if (e.key === 'Escape') {
      this.closeDropdown();
    }
  }

  closeOnClickOutside(e) {
    if (!this.myRef.current.contains(e.target)) {
      this.closeDropdown();
    }
  }

  componentDidMount() {
    window.addEventListener('keydown', this.closeOnEsc)
    window.addEventListener('focusin', this.closeOnClickOutside)
    window.addEventListener('click', this.closeOnClickOutside)
  }

  componentWillUnmount() {
    window.removeEventListener('keydown', this.closeOnEsc);
    window.removeEventListener('focusin', this.closeOnClickOutside)
    window.removeEventListener('click', this.closeOnClickOutside)
  }

  closeDropdown() {
    this.setState(prevState => ({
      isOpen: false
    }));
  }

  updateTriggerText(text) {
    this.setState({
      triggerText: text
    })
  }

  runChoiceFunction(text) {
    if (this.props.choices.choiceFunction) {
      this.props.choices.choiceFunction(text);
    }
  }

  toggleDropdownOpen() {
    this.setState(prevState => ({
      isOpen: !prevState.isOpen,
    }));
  }

  render() {
    const {
      additionalClasses,
      additionalIconClasses,
      additionalTriggerClasses,
      additionalTriggerTextClasses,
      analyticsString,
      children,
      choices,
      defaultTriggerText,
      iconType,
      idString,
      screenReaderText,
      title,
      variant
    } = this.props;
    const { triggerText, isOpen } = this.state;
    return (
      <div ref={this.myRef}>
        <a className={classNames(
          "sprk-b-Link",
          "sprk-b-Link--plain",
          {"sprk-u-mrs": variant === 'informational'},
          additionalTriggerClasses,
        )}
           href="#nogo"
           aria-haspopup="true"
           role="combobox"
           data-analytics={analyticsString ? analyticsString : 'undefined'}
           data-id={idString ? idString : 'undefined'}
           onClick={this.toggleDropdownOpen}>
          { variant === 'informational' &&
            <React.Fragment>
              <span
                className={classNames(additionalTriggerTextClasses)}
                role="combobox">{triggerText}</span>
              <SprkIcon additionalClasses="sprk-c-Icon--stroke-current-color sprk-u-mls" iconType="chevron-down" />
            </React.Fragment>
          }
          { variant === 'base' &&
            <React.Fragment>
              <span
                className={
                  classNames("sprk-u-ScreenReaderText", additionalTriggerTextClasses)
                }>{screenReaderText}</span>
              <SprkIcon iconType={iconType} additionalClasses={additionalIconClasses} />
            </React.Fragment>
          }
        </a>
        {isOpen &&
          <div className={classNames("sprk-c-Dropdown", additionalClasses)}>
            {title &&
            <div className="sprk-c-Dropdown__header">
              <h2 className="sprk-c-Dropdown__title">{title}</h2>
            </div>
            }
            <ul className="sprk-c-Dropdown__links">
              {this.state.choiceItems.map((choice) => {
                const {content, element, href, isActive, text, value, ...rest} = choice;
                const TagName = element || 'a';
                return(
                  <li className="sprk-c-Dropdown__item" role="option" key={choice.id}>

                    {variant === 'base' &&
                      <TagName
                        className="sprk-c-Dropdown__link"
                        href={TagName === 'a' ? href || '#nogo' : undefined}
                        onClick={() => {
                          this.updateTriggerText(text);
                          this.closeDropdown()
                          this.runChoiceFunction(value)
                        }}
                        {...rest}>{text}</TagName>
                    }
                    {variant === 'informational' &&
                      <React.Fragment>
                        <TagName
                          className={classNames(
                            "sprk-c-Dropdown__link",
                            {"sprk-c-Dropdown__link--active": isActive}
                            )}
                          href={TagName === 'a' ? href || '#nogo' : undefined}
                          onClick={() => {
                            this.updateTriggerText(content.title);
                            this.closeDropdown()
                            this.runChoiceFunction(value)
                          }}
                          {...rest}>
                          <p className="sprk-b-TypeBodyOne">{content.title}</p>
                          <p className="sprk-b-TypeBodyTwo">{content.infoLine1}</p>
                          <p className="sprk-b-TypeBodyTwo">{content.infoLine2}</p>
                        </TagName>
                      </React.Fragment>
                    }
                  </li>);
              })
            }
            </ul>
          </div>
        }
      </div>
    );
  }
}

SprkDropdown.propTypes = {
  // Classes applied to the dropdown
  additionalClasses: PropTypes.string,
  // Classes applied to the icon
  additionalIconClasses: PropTypes.string,
  // Classes applied to the link that triggers the dropdown to open
  additionalTriggerClasses: PropTypes.string,
  // Classes applied to the text in the trigger link
  additionalTriggerTextClasses: PropTypes.string,
  // Assigned to data-analytics
  analyticsString: PropTypes.string,
  // Incoming children
  children: PropTypes.node,
  // Choices object that builds the dropdown contents
  choices: PropTypes.shape({
    // An array of objects that describe the items in the menu
    items: PropTypes.arrayOf(PropTypes.shape({
      // The element to render for each menu item
      element: PropTypes.oneOfType([PropTypes.string, PropTypes.func]),
      // Assigned to href of the element is 'a'
      href: PropTypes.string,
      // The text inside the item
      text: PropTypes.string,
    }))
  }),
  // The text set as the default of the trigger link
  defaultTriggerText: PropTypes.string,
  // The icon type of the trigger icon
  iconType: PropTypes.string,
  // Assigned to data-id
  idString: PropTypes.string,
  // Text that is visually hidden when the trigger is just an icon
  screenReaderText: PropTypes.string,
  // The text of the optional header above the choices in the dropdown
  title: PropTypes.string,
  // The variant name
  variant: PropTypes.oneOf(['base', 'informational'])
};

SprkDropdown.defaultProps = {
  choices: {
    items: []
  },
  defaultTriggerText: 'Choose One...',
  iconType: 'chevron-down',
  variant: 'base'
};

export default SprkDropdown;

// angular/projects/spark-angular/src/lib/components/sprk-dropdown/sprk-dropdown.component.ts
import {
  Component,
  Input,
  Output,
  ElementRef,
  HostListener,
  EventEmitter
} from '@angular/core';

@Component({
  selector: 'sprk-dropdown',
  template: `
    <div
      [ngClass]="{
        'sprk-c-MastheadMask': isOpen && dropdownType === 'mastheadSelector'
      }"
    >
      <div [ngClass]="{ 'sprk-o-Box': dropdownType === 'mastheadSelector' }">
        <sprk-link
          [additionalClasses]="getTriggerClasses()"
          (click)="toggle($event)"
          [idString]="idString"
          [analyticsString]="analyticsString"
          aria-haspopup="listbox"
          [attr.aria-label]="title ? title : screenReaderText"
        >
          <span [ngClass]="getTriggerTextClasses()">{{ triggerText }}</span>
          <span class="sprk-u-ScreenReaderText">{{ screenReaderText }}</span>
          <sprk-icon
            [iconType]="triggerIconType"
            additionalClasses="sprk-u-mls sprk-c-Icon--stroke-current-color {{
              additionalIconClasses
            }}"
          ></sprk-icon>
        </sprk-link>
      </div>

      <div [ngClass]="getClasses()" *ngIf="isOpen">
        <div
          class="sprk-c-Dropdown__header"
          *ngIf="dropdownType === 'mastheadSelector' || title || selector"
        >
          <h2 class="sprk-c-Dropdown__title sprk-b-TypeBodyTwo" *ngIf="title">
            {{ title }}
          </h2>

          <sprk-link
            *ngIf="selector && !title"
            linkType="plain"
            additionalClasses="sprk-o-Stack sprk-o-Stack--split@xxs sprk-o-Stack--center-column sprk-u-Width-100"
            ariaHasPopUp="true"
            (click)="toggle($event)"
          >
            <span
              class="sprk-c-Dropdown__title sprk-b-TypeBodyTwo sprk-o-Stack__item sprk-o-Stack__item--flex@xxs"
              >{{ selector }}</span
            >
            <sprk-icon
              [iconType]="triggerIconType"
              additionalClasses="sprk-c-Icon--stroke-current-color sprk-u-mls sprk-c-Icon--toggle sprk-Stack__item {{
                additionalIconClasses
              }}"
            ></sprk-icon>
          </sprk-link>
        </div>

        <ul
          class="sprk-c-Dropdown__links"
          role="listbox"
        >
          <li
            class="sprk-c-Dropdown__item"
            *ngFor="let choice of choices; let i = index"
            [attr.data-sprk-dropdown-choice-index]="i"
            (click)="choiceClick($event)"
            [attr.aria-label]="choice.content ? choice.content.title : choice.text"
          >
            <div *ngIf="choice.content; then content; else link"></div>
            <ng-template #link>
              <sprk-link
                linkType="unstyled"
                [href]="choice.href"
                additionalClasses="sprk-c-Dropdown__link {{
                  choice.active && 'sprk-c-Dropdown__link--active'
                }}"
                role="option"
                >{{ choice.text }}
              </sprk-link>
            </ng-template>
            <ng-template #content>
              <sprk-link
                linkType="unstyled"
                [href]="choice.href"
                additionalClasses="sprk-c-Dropdown__link {{
                  choice.active && 'sprk-c-Dropdown__link--active'
                }}"
                role="option"
              >
                <p class="sprk-b-TypeBodyOne">{{ choice.content.title }}</p>
                <p>{{ choice.content.infoLine1 }}</p>
                <p>{{ choice.content.infoLine2 }}</p>
              </sprk-link>
            </ng-template>
          </li>
        </ul>
        <ng-content select="[sprkDropdownFooter]"></ng-content>
      </div>
    </div>
  `
})
export class SprkDropdownComponent {
  /**
   * The variant of the Dropdown to render.
   */
  @Input()
  dropdownType = 'base';
  /**
   * Expects a space separated string
   * of classes to be added to the
   * component.
   */
  @Input()
  additionalClasses: string;
  /**
   * Expects a space separated string
   * of classes to be added to the
   * icon.
   */
  @Input()
  additionalIconClasses: string;
  /**
   * Expects a space separated string of
   * classes to be added to the trigger link element.
   */
  @Input()
  additionalTriggerClasses: string;
  /**
   * Expects a space separated string of
   * classes to be added to the trigger text.
   */
  @Input()
  additionalTriggerTextClasses: string;
  /**
   * The value supplied will be assigned
   * to the `data-id` attribute on the
   * component. This is intended to be
   * used as a selector for automated
   * tools. This value should be unique
   * per page.
   */
  @Input()
  idString: string;
  /**
   * The value supplied will be assigned to the
   * `data-analytics` attribute on the component.
   * Intended for an outside
   * library to capture data.
   */
  @Input()
  analyticsString: string;
  /**
   * If `true`, the Dropdown will be open when rendered.
   */
  @Input()
  isOpen = false;
  /**
   * The value supplied will be displayed
   * in a box above the choices.
   */
  @Input()
  title: string;
  /**
   * The value supplied will be assigned to
   * the `.Dropdown__title` text.
   * Should be used if using the `mastheadSelector` type.
   */
  @Input()
  selector: string;
  /**
   * Expects an array of choice objects.
   */
  @Input()
  choices: any[];
  /**
   * If supplied, will render the icon
   * to the right of the trigger text.
   */
  @Input()
  triggerIconType: string;
  /**
   * The text that is initially rendered to the trigger.
   * If `dropdownType` is `informational`,
   * clicking on a choice will change the trigger text.
   */
  @Input()
  triggerText: string;
  /**
   * The value supplied will be visually hidden
   * inside the trigger. Userful
   * for when title is empty,
   * and only `triggerIconType` is supplied.
   */
  @Input()
  screenReaderText: string;
  /**
   * When the `dropdownType` is
   *  `informational` and a
   * user clicks on a choice from
   * the menu, the `choiceMade` event is
   * emitted from the Dropdown and it
   * contains the value of the clicked choice.
   */
  @Output()
  choiceMade: EventEmitter<string> = new EventEmitter();
  /**
   * @ignore
   */
  constructor(public ref: ElementRef) {}
  /**
   * @ignore
   */
  toggle(event): void {
    this.isOpen = !this.isOpen;
  }

  @HostListener('document:click', ['$event'])
  onClick(event): void {
    if (
      !this.ref.nativeElement.contains(event.target) ||
      event.target.classList.contains('sprk-c-MastheadMask')
    ) {
      this.hideDropdown();
    }
  }

  @HostListener('document:focusin', ['$event'])
  onFocusin(event): void {
    /* istanbul ignore else: angular focus event isnt setting e.target */
    if (
      !this.ref.nativeElement.contains(event.target) ||
      event.target.classList.contains('sprk-c-MastheadMask')
    ) {
      this.hideDropdown();
    }
  }
  /**
   * @ignore
   */
  choiceClick(event) {
    this.clearActiveChoices();
    const choiceIndex = event.currentTarget.getAttribute(
      'data-sprk-dropdown-choice-index'
    );
    const clickedChoice = this.choices[choiceIndex];
    if (
      this.dropdownType === 'informational' ||
      this.dropdownType === 'mastheadSelector'
    ) {
      this.setActiveChoice(event);
      this.updateTriggerText(event);
    }
    this.hideDropdown();
    this.choiceMade.emit(clickedChoice['value']);
  }
  /**
   * @ignore
   */
  setActiveChoice(event): void {
    const choiceIndex = event.currentTarget.getAttribute(
      'data-sprk-dropdown-choice-index'
    );
    this.choices[choiceIndex]['active'] = true;
  }
  /**
   * @ignore
   */
  updateTriggerText(event): void {
    const choiceIndex = event.currentTarget.getAttribute(
      'data-sprk-dropdown-choice-index'
    );
    this.triggerText = this.choices[choiceIndex]['value'];
  }

  /**
   * @ignore
   */
  clearActiveChoices(): void {
    this.choices.forEach((choice: object) => {
      choice['active'] = false;
    });
  }

  /**
   * @ignore
   */
  hideDropdown(): void {
    this.isOpen = false;
  }

  /**
   * @ignore
   */
  getClasses(): string {
    const classArray: string[] = ['sprk-c-Dropdown'];

    if (this.additionalClasses) {
      this.additionalClasses.split(' ').forEach(className => {
        classArray.push(className);
      });
    }

    return classArray.join(' ');
  }

  /**
   * @ignore
   */
  getTriggerClasses(): string {
    const classArray: string[] = [];

    if (this.additionalTriggerClasses) {
      this.additionalTriggerClasses.split(' ').forEach(className => {
        classArray.push(className);
      });
    }

    return classArray.join(' ');
  }

  /**
   * @ignore
   */
  getTriggerTextClasses(): string {
    const classArray: string[] = [''];

    if (this.additionalTriggerTextClasses) {
      this.additionalTriggerTextClasses.split(' ').forEach(className => {
        classArray.push(className);
      });
    }

    return classArray.join(' ');
  }
}
