// react/src/components/masthead/components/SprkMastheadSelector/SprkMastheadSelector.js
/* global window */
import React, { Component } from 'react';
import PropTypes from 'prop-types';
import classNames from 'classnames';
import uniqueId from 'lodash/uniqueId';
import SprkIcon from '../../../icons/SprkIcon';
import SprkLink from '../../../../base/links/SprkLink';

class SprkMastheadSelector extends Component {
  constructor(props) {
    super();
    this.state = {
      isOpen: false,
      triggerText: props.defaultTriggerText,
      choiceItems: props.choices.items.map((item) => ({
        id: uniqueId(),
        ...item,
      })),
    };
    this.openDropdown = this.openDropdown.bind(this);
    this.closeDropdown = this.closeDropdown.bind(this);
    this.updateTriggerText = this.updateTriggerText.bind(this);
    this.closeOnEsc = this.closeOnEsc.bind(this);
    this.closeOnClickOutside = this.closeOnClickOutside.bind(this);
    this.dropdownRef = React.createRef();
  }

  componentDidMount() {
    window.addEventListener('keydown', this.closeOnEsc);
    window.addEventListener('focusin', this.closeOnClickOutside);
    window.addEventListener('click', this.closeOnClickOutside);
  }

  componentWillUnmount() {
    window.removeEventListener('keydown', this.closeOnEsc);
    window.removeEventListener('focusin', this.closeOnClickOutside);
    window.removeEventListener('click', this.closeOnClickOutside);
  }

  closeOnEsc(e) {
    if (e.key === 'Escape') {
      this.closeDropdown();
    }
  }

  closeOnClickOutside(e) {
    if (!this.dropdownRef.current.contains(e.target)) {
      this.closeDropdown();
    }
  }

  openDropdown(e) {
    e.preventDefault();
    this.setState({
      isOpen: true,
    });
  }

  closeDropdown() {
    this.setState({
      isOpen: false,
    });
  }

  updateTriggerText(text) {
    this.setState({
      triggerText: text,
    });
  }

  render() {
    const {
      additionalClasses,
      additionalIconClasses,
      additionalTriggerClasses,
      additionalTriggerTextClasses,
      analyticsString,
      choices,
      iconName,
      idString,
      isFlush,
    } = this.props;
    const { choiceFunction, footer } = choices;
    const { choiceItems, isOpen, triggerText } = this.state;

    return (
      // eslint-disable-next-line
      <div
        role="dialog"
        ref={this.dropdownRef}
        className={classNames({ 'sprk-c-MastheadMask': isOpen && isFlush })}
        onClick={() => {
          if (isOpen) {
            this.closeDropdown();
          }
        }}
      >
        <div className={classNames({ 'sprk-o-Box': isFlush })}>
          <SprkLink
            variant="plain"
            additionalClasses={classNames(
              `
                sprk-c-Masthead__selector
                sprk-o-Stack
                sprk-o-Stack--split@xxs
                sprk-o-Stack--center-column
              `,
              additionalTriggerClasses,
            )}
            data-analytics={analyticsString}
            data-id={idString}
            onClick={this.openDropdown}
            href="#nogo"
            data-sprk-dropdown-trigger="dropdown-selector"
            aria-haspopup="true"
          >
            <span
              className={classNames(
                'sprk-o-Stack__item sprk-o-Stack__item--flex@xxs',
                additionalTriggerTextClasses,
              )}
              role="listbox"
            >
              {triggerText}
            </span>
            <SprkIcon
              iconName={iconName}
              additionalClasses={classNames(
                'sprk-c-Icon--toggle sprk-Stack__item',
                additionalIconClasses,
              )}
            />
          </SprkLink>
        </div>

        {isOpen && (
          <div
            className={classNames(
              'sprk-c-Masthead__selector-dropdown',
              additionalClasses,
            )}
            data-sprk-dropdown="dropdown-selector"
          >
            <div className="sprk-c-Masthead__selector-dropdown-header">
              <SprkLink
                variant="plain"
                additionalClasses="
                  sprk-o-Stack
                  sprk-o-Stack--split@xxs
                  sprk-o-Stack--center-column
                "
                onClick={this.closeDropdown}
                href="#nogo"
                aria-haspopup="true"
              >
                <span
                  className="
                    sprk-c-Masthead__selector-dropdown-title
                    sprk-b-TypeBodyTwo
                    sprk-o-Stack__item
                    sprk-o-Stack__item--flex@xxs
                  "
                >
                  {triggerText}
                </span>
                <SprkIcon
                  iconName="chevron-up"
                  additionalClasses="sprk-c-Icon--toggle sprk-Stack__item"
                />
              </SprkLink>
            </div>

            <ul className="sprk-c-Masthead__selector-dropdown-links">
              {choiceItems.map((item) => {
                const {
                  element,
                  href,
                  title,
                  information,
                  value,
                  ...rest
                } = item;
                const TagName = element || 'a';
                return (
                  <li
                    className="sprk-c-Masthead__selector-dropdown-item"
                    key={item.id}
                  >
                    <TagName
                      className="sprk-c-Masthead__selector-dropdown-link"
                      href={TagName === 'a' ? href || '#nogo' : undefined}
                      onClick={() => {
                        this.updateTriggerText(title);
                        this.closeDropdown();
                        if (choiceFunction) {
                          choiceFunction(value);
                        }
                      }}
                      role="option"
                      {...rest}
                    >
                      <p className="sprk-b-TypeBodyOne">{title}</p>
                      <p>{information}</p>
                    </TagName>
                  </li>
                );
              })}
            </ul>

            {footer && (
              <div className=" sprk-c-Masthead__selector-footer ">{footer}</div>
            )}
          </div>
        )}
      </div>
    );
  }
}

SprkMastheadSelector.propTypes = {
  /**
   * A space-separated string of classes to add to
   * the outermost container of the component.
   */
  additionalClasses: PropTypes.string,
  /**
   * A space-separated string of classes to add to the icon.
   */
  additionalIconClasses: PropTypes.string,
  /**
   * A space-separated string of classes to add to the trigger element.
   */
  additionalTriggerClasses: PropTypes.string,
  /**
   * A space-separated string of classes to add to the trigger text.
   */
  additionalTriggerTextClasses: PropTypes.string,
  /**
   * Assigned to the `data-analytics` attribute serving as
   * a unique selector for outside libraries to capture data.
   */
  analyticsString: PropTypes.string,
  /** Configuration object that builds the dropdown. */
  choices: PropTypes.shape({
    /**
     * A function supplied that will run when a choice is made.
     */
    choiceFunction: PropTypes.func,
    /** A node to render at the foot of the dropdown menu. */
    footer: PropTypes.node,
    /** An array of objects that describe the items in the menu. */
    items: PropTypes.arrayOf(
      PropTypes.shape({
        /**
         * Determines if link renders as an anchor tag, or router link.
         */
        element: PropTypes.oneOfType([PropTypes.string, PropTypes.func]),
        /**
         * The `href` value assigned the logo's link.
         */
        href: PropTypes.string,
        /** The text for the Masthead Selector item. */
        text: PropTypes.string,
      }),
    ).isRequired,
  }).isRequired,
  // TODO: Get rid of this, not needed
  children: PropTypes.node,
  /** The text set as the default of the trigger link */
  defaultTriggerText: PropTypes.string,
  /** The icon type of the trigger icon */
  iconName: PropTypes.string,
  /**
   * Assigned to the `data-id` attribute serving as
   * a unique selector for automated tools.
   */
  idString: PropTypes.string,
  /** Applies styles if the selector is flush with the sides of the viewport */
  isFlush: PropTypes.bool,
};

SprkMastheadSelector.defaultProps = {
  defaultTriggerText: 'Choose One...',
  iconName: 'chevron-down',
  isFlush: false,
};

export default SprkMastheadSelector;

// angular/projects/spark-angular/src/lib/components/sprk-masthead/components/sprk-masthead-selector/sprk-masthead-selector.component.ts
import {
  Component,
  Input,
  Output,
  ElementRef,
  HostListener,
  EventEmitter,
  OnChanges,
  SimpleChanges,
} from '@angular/core';
import { ISprkMastheadSelectorChoice } from '../sprk-masthead-selector/sprk-masthead-selector.interfaces';

@Component({
  selector: 'sprk-masthead-selector',
  template: `
    <div [ngClass]="{ 'sprk-c-MastheadMask': isOpen && isFlush }">
      <div [ngClass]="{ 'sprk-o-Box': isFlush }">
        <a
          sprkLink
          variant="plain"
          class="
            sprk-c-Masthead__selector
            sprk-o-Stack
            sprk-o-Stack--split@xxs
            sprk-o-Stack--center-column
          "
          (click)="toggle($event)"
          [idString]="idString"
          [analyticsString]="analyticsString"
          aria-haspopup="listbox"
          href="#"
          [attr.aria-label]="
            triggerText ? triggerText : screenReaderText || 'Choose One'
          "
        >
          <span sprkStackItem class="sprk-o-Stack__item--flex@xxs">{{
            triggerText
          }}</span>
          <span class="sprk-u-ScreenReaderText">{{ screenReaderText }}</span>
          <sprk-icon
            sprkStackItem
            [iconName]="triggerIconName"
            additionalClasses="sprk-Stack__item sprk-u-mhs"
          ></sprk-icon>
        </a>
      </div>

      <div class="sprk-c-Masthead__selector-dropdown" *ngIf="isOpen">
        <div class="sprk-c-Masthead__selector-dropdown-header" *ngIf="heading">
          <a
            sprkLink
            variant="plain"
            class="sprk-o-Stack sprk-o-Stack--split@xxs sprk-o-Stack--center-column sprk-c-Masthead__selector-dropdown-header-link"
            (click)="toggle($event)"
            [attr.aria-label]="heading"
            href="#"
          >
            <span
              sprkStackItem
              class="sprk-c-Masthead__selector-dropdown-title sprk-b-TypeBodyTwo sprk-o-Stack__item--flex@xxs"
              >{{ heading }}</span
            >
            <sprk-icon
              sprkStackItem
              [iconName]="triggerIconName"
              additionalClasses="
                sprk-c-Icon--toggle
              "
            ></sprk-icon>
          </a>
        </div>

        <ul
          class="sprk-c-Masthead__selector-dropdown-links"
          role="listbox"
          [attr.aria-label]="
            heading ? heading : screenReaderText || 'My Choices'
          "
        >
          <li
            class="sprk-c-Masthead__selector-dropdown-item"
            *ngFor="let choice of choices; let i = index"
            (click)="choiceClick(i)"
            [attr.aria-selected]="choice.active"
            role="option"
          >
            <div *ngIf="choice.content; then content; else link"></div>
            <ng-template #link>
              <a
                *ngIf="!choice.routerLink"
                sprkLink
                variant="unstyled"
                [attr.href]="choice.href"
                [analyticsString]="choice.analyticsString"
                [ngClass]="{
                  'sprk-c-Masthead__selector-dropdown-link': true,
                  'sprk-c-Masthead__selector-dropdown-link--active':
                    choice.active
                }"
                [attr.aria-label]="choice.text"
                >{{ choice.text }}
              </a>
              <a
                *ngIf="choice.routerLink"
                sprkLink
                variant="unstyled"
                [routerLink]="choice.routerLink"
                [analyticsString]="choice.analyticsString"
                [ngClass]="{
                  'sprk-c-Masthead__selector-dropdown-link': true,
                  'sprk-c-Masthead__selector-dropdown-link--active':
                    choice.active
                }"
                [attr.aria-label]="choice.text"
                >{{ choice.text }}
              </a>
            </ng-template>
            <ng-template #content>
              <a
                sprkLink
                *ngIf="!choice.routerLink"
                variant="unstyled"
                [attr.href]="choice.href"
                [analyticsString]="choice.analyticsString"
                [ngClass]="{
                  'sprk-c-Masthead__selector-dropdown-link': true,
                  'sprk-c-Masthead__selector-dropdown-link--active':
                    choice.active
                }"
                [attr.aria-label]="choice.content.title"
              >
                <p sprkText variant="bodyOne">{{ choice.content.title }}</p>
                <p sprkText variant="bodyTwo" *ngIf="choice.content.infoLine1">
                  {{ choice.content.infoLine1 }}
                </p>
                <p sprkText variant="bodyTwo" *ngIf="choice.content.infoLine2">
                  {{ choice.content.infoLine2 }}
                </p>
              </a>
              <a
                sprkLink
                *ngIf="choice.routerLink"
                variant="unstyled"
                [routerLink]="choice.routerLink"
                [analyticsString]="choice.analyticsString"
                [ngClass]="{
                  'sprk-c-Masthead__selector-dropdown-link': true,
                  'sprk-c-Masthead__selector-dropdown-link--active':
                    choice.active
                }"
                [attr.aria-label]="choice.content.title"
              >
                <p sprkText variant="bodyOne">{{ choice.content.title }}</p>
                <p sprkText variant="bodyTwo" *ngIf="choice.content.infoLine1">
                  {{ choice.content.infoLine1 }}
                </p>
                <p sprkText variant="bodyTwo" *ngIf="choice.content.infoLine2">
                  {{ choice.content.infoLine2 }}
                </p>
              </a>
            </ng-template>
          </li>
        </ul>
        <ng-content select="[sprkMastheadSelectorFooter]"></ng-content>
      </div>
    </div>
  `,
})
export class SprkMastheadSelectorComponent implements OnChanges {
  /**
   * The value supplied will be visually hidden
   * inside the trigger. Useful
   * for when heading is empty,
   * and only `triggerIconName` is supplied.
   */
  @Input()
  screenReaderText: string;
  /**
   * This value will be assigned to the Masthead Selector
   * placeholder text and the dropdown heading.
   */
  @Input()
  heading: string;
  /**
   * The value supplied will be assigned
   * to the `data-id` attribute on the
   * component. This is intended to be
   * used as a selector for automated
   * tools. This value should be unique
   * per page.
   */
  @Input()
  idString: string;
  /**
   * The value supplied will be assigned to the
   * `data-analytics` attribute on the component.
   * Intended for an outside
   * library to capture data.
   */
  @Input()
  analyticsString: string;
  /**
   * Expects an array of
   * [ISprkMastheadSelectorChoice](https://github.com/sparkdesignsystem/spark-design-system/blob/main/angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead-selector/sprk-masthead-selector.interfaces.ts)
   *  objects.
   */
  @Input()
  choices: ISprkMastheadSelectorChoice[];
  /**
   * The name of the icon that
   * renders the icon to the right
   * of the trigger text.
   */
  @Input()
  triggerIconName: string;
  /**
   * The text that is initially rendered to the trigger.
   */
  @Input()
  triggerText: string;
  /** Applies styles if the selector is flush with the sides of the viewport. */
  @Input()
  isFlush: boolean;
  /**
   * The event that is
   * emitted from the Masthead Selector when a choice
   * is clicked. The event contains the value
   * of the choice that was clicked.
   */
  @Output()
  choiceMade: EventEmitter<string> = new EventEmitter();

  /**
   * This event will be emitted
   * when the Masthead Selector is opened.
   */
  @Output()
  openedEvent: EventEmitter<any> = new EventEmitter();
  /**
   * This event will be emitted
   * when the Masthead Selector is closed.
   */
  @Output()
  closedEvent: EventEmitter<any> = new EventEmitter();

  /**
   * @ignore
   */
  isOpen = false;
  /**
   * @ignore
   */
  constructor(public ref: ElementRef) {}

  /**
   * @ignore
   */
  ngOnChanges(changes: SimpleChanges): void {
    if (this.choices && changes.choices) {
      this._updateTriggerTextWithDefaultValue();
    }
  }

  /**
   * Updates the open state when the
   * selector is toggled.
   */
  toggle(event): void {
    event.preventDefault();
    this.isOpen = !this.isOpen;
    if (this.isOpen) {
      this.openedEvent.emit();
    } else {
      this.closedEvent.emit();
    }
  }

  @HostListener('document:click', ['$event'])
  onClick(event): void {
    if (
      !this.ref.nativeElement.contains(event.target) ||
      event.target.classList.contains('sprk-c-MastheadMask')
    ) {
      this.hideDropdown();
    }
  }

  @HostListener('document:focusin', ['$event'])
  onFocusin(event): void {
    /* istanbul ignore next: angular focus event isnt setting e.target */
    if (
      !this.ref.nativeElement.contains(event.target) ||
      event.target.classList.contains('sprk-c-MastheadMask')
    ) {
      this.hideDropdown();
    }
  }
  /**
   * @ignore
   */
  choiceClick(i) {
    this.clearActiveChoices();
    const clickedChoice = this.choices[i];

    this.setActiveChoice(i);
    this.updateTriggerText(i);
    this.hideDropdown();
    this.choiceMade.emit(clickedChoice['value']);
  }
  /**
   * @ignore
   */
  setActiveChoice(i): void {
    this.choices[i]['active'] = true;
  }
  /**
   * @ignore
   */
  updateTriggerText(i): void {
    this.triggerText = this.choices[i]['value'];
  }

  /**
   * @ignore
   */
  clearActiveChoices(): void {
    this.choices.forEach((choice: ISprkMastheadSelectorChoice) => {
      choice['active'] = false;
    });
  }

  /**
   * @ignore
   */
  hideDropdown(): void {
    this.isOpen = false;
  }

  /**
   * Update trigger text with default choice value.
   */
  protected _updateTriggerTextWithDefaultValue(): void {
    const defaultChoice = this._lookupDefaultChoice();

    if (defaultChoice) {
      // Deactivate previously activated choices
      this.clearActiveChoices();
      // Mark default choice as active
      defaultChoice.active = true;
      // Update trigger text
      this.triggerText = defaultChoice.value;
    }
  }

  /**
   * Lookup choice with specified `isDefault: true` field.
   */
  protected _lookupDefaultChoice(): ISprkMastheadSelectorChoice | null {
    return this.choices.find((choice) => choice.isDefault) || null;
  }
}
