// react/src/components/dividers/SprkDivider.js
import React from 'react';
import PropTypes from 'prop-types';
import classnames from 'classnames';

const SprkDivider = (props) => {
  const { element, additionalClasses, idString, ...other } = props;
  const classNames = classnames('sprk-c-Divider', additionalClasses);
  const TagName = element;
  return <TagName className={classNames} data-id={idString} {...other} />;
};

SprkDivider.defaultProps = {
  idString: undefined,
  additionalClasses: undefined,
};

SprkDivider.propTypes = {
  /**
   * Determines if link renders as a `<span>` or `<hr>`.
   */
  element: PropTypes.oneOf(['span', 'hr']).isRequired,
  /**
   * Value assigned
   * to the `data-id` attribute on the
   * component. This is intended to be
   * used as a selector for automated
   * tools. This value should be unique
   * per page.
   */
  idString: PropTypes.string,
  /**
   * Expects a space separated string
   * of classes to be added to the
   * Divider.
   */
  additionalClasses: PropTypes.string,
};

export default SprkDivider;

// angular/projects/spark-angular/src/lib/components/sprk-divider/sprk-divider.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'sprk-divider',
  template: `
    <span [ngClass]="getClasses()" [attr.data-id]="idString"> </span>
  `
})
export class SprkDividerComponent {
  /**
   * Expects a space separated string
   * of classes to be added to the
   * component.
   */
  @Input()
  additionalClasses: string;
  /**
   * The value supplied will be assigned
   * to the 'data-id' attribute on the
   * component. This is intended to be
   * used as a selector for automated
   * tools. This value should be unique
   * per page.
   */
  @Input()
  idString: string;

  getClasses(): string {
    const classArray: string[] = ['sprk-c-Divider'];

    if (this.additionalClasses) {
      this.additionalClasses.split(' ').forEach(className => {
        classArray.push(className);
      });
    }

    return classArray.join(' ');
  }
}
