// src/angular/src/app/spark-extras-angular/components/sprk-highlight-board/sprk-highlight-board.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'sprk-highlight-board',
  template: `
  <div [ngClass]="getClasses()">
    <img
      *ngIf="type !== 'noImage'"
      class="sprk-c-HighlightBoard__image"
      src="{{ imgSrc }}"
      alt="{{ imgAlt }}">

    <div
      [ngClass]="{
        'sprk-c-HighlightBoard__content': true,
        'sprk-c-HighlightBoard__content--light': type === 'default' || !type || type === 'fullWidth'
      }">
      <div class="sprk-u-mbl">
        <h1 class="sprk-b-TypeDisplayThree sprk-c-HighlightBoard__primary-heading sprk-u-mbs">
          {{ heading }}
        </h1>

        <h4 class="sprk-b-TypeDisplayFour sprk-c-HighlightBoard__sub-heading sprk-u-mbm">
          {{ subHeading }}
        </h4>
      </div>

      <sprk-stack
        itemSpacing="medium"
        splitAt="small"
        additionalClasses="sprk-c-HighlightBoard__cta-container">
        <div sprkStackItem>
          <a
            [routerLink]="ctaHref"
            class="sprk-c-HighlightBoard__cta sprk-c-Button sprk-c-Button--primary sprk-c-Button--full@sm"
            [attr.data-analytics]="analyticsStringCta">
            {{ ctaText }}
          </a>
        </div>

        <div
          sprkStackItem
          *ngIf="ctaText2">
          <a
            [routerLink]="ctaHref2"
            class="sprk-c-HighlightBoard__cta sprk-c-Button sprk-c-Button--primary sprk-c-Button--full@sm"
            [attr.data-analytics]="analyticsStringCta2">
            {{ ctaText2 }}
          </a>
        </div>
      </sprk-stack>
    </div>
  </div>
  `,
  styles: ['']
})
export class SparkHighlightBoardComponent {
  @Input()
  heading: string;
  @Input()
  subHeading: string;
  @Input()
  imgSrc: string;
  @Input()
  imgAlt: string;
  @Input()
  ctaText: string;
  @Input()
  ctaHref: string;
  @Input()
  ctaText2: string;
  @Input()
  ctaHref2: string;
  @Input()
  analyticsStringCta: string;
  @Input()
  analyticsStringCta2: string;
  @Input()
  additionalClasses: string;
  @Input()
  type: string;

  getClasses(): string {
    const classArray: string[] = ['sprk-c-HighlightBoard'];

    switch (this.type) {
      case 'noImage':
        break;
      case 'stacked':
        classArray.push(
          'sprk-c-HighlightBoard--has-image sprk-c-HighlightBoard--stacked'
        );
        break;
      case 'fullWidth':
        classArray.push(
          'sprk-c-HighlightBoard--has-image sprk-c-HighlightBoard--has-image'
        );
        break;
      default:
        classArray.push('sprk-c-HighlightBoard--has-image');
        break;
    }

    if (this.additionalClasses) {
      this.additionalClasses.split(' ').forEach(className => {
        classArray.push(className);
      });
    }

    return classArray.join(' ');
  }
}

// src/react/projects/spark-core-react/src/SprkHighlightBoard/SprkHighlightBoard.js
import React, { Component } from 'react';
import PropTypes from 'prop-types';
import classnames from 'classnames';
import { SprkButton } from '@sparkdesignsystem/spark-core-react';

const SprkHighlightBoard = (props) => {
  const {
    children,
    imgSrc,
    imgAlt,
    heading,
    ctaText,
    ctaHref,
    ctaAnalytics,
    ctaIdString,
    ctaText2,
    ctaHref2,
    ctaAnalytics2,
    ctaIdString2,
    variant,
    additionalClasses,
    idString,
    analyticsString,
    ...other
  } = props;

  const classNames = classnames(
    'sprk-c-HighlightBoard',
    'sprk-u-mbm',
    additionalClasses,
    {'sprk-c-HighlightBoard--has-image': imgSrc},
    {'sprk-c-HighlightBoard--stacked': variant === 'stacked'},
  );

  return (
    <div className={classNames} data-id={idString} {...other}>
      {imgSrc && 
        <img
          className='sprk-c-HighlightBoard__image'
          src={imgSrc}
          alt={imgAlt} />
      }

      { (heading || ctaText || ctaText2) &&
        <div className='sprk-c-HighlightBoard__content sprk-o-Stack sprk-o-Stack--large'>
          { heading && 
            <h1 className="sprk-b-TypeDisplayOne sprk-c-HighlightBoard__heading sprk-o-Stack__item">
              {heading}
            </h1>
          }

          { (ctaText || ctaText2) && 
          <div className= {
            classnames(
              'sprk-o-Stack__item',
              'sprk-o-Stack',
              'sprk-o-Stack--medium',
              'sprk-o-Stack--split@xs',
              'sprk-o-Stack--center-column',
              {'sprk-o-Stack--center-row' : variant === 'noimage' || variant === 'stacked'}
            )
          } >
            
            { ctaText &&
              <div className="sprk-o-Stack__item sprk-c-HighlightBoard__cta">
                <SprkButton
                  element="a"
                  href={ctaHref}
                  analyticsString={ctaAnalytics}
                  idString={ctaIdString}
                  additionalClasses='sprk-c-Button--full@sm' >

                  {ctaText}
                </SprkButton>
              </div>
            }

            { ctaText2 &&
              <div className="sprk-o-Stack__item sprk-c-HighlightBoard__cta">
                <SprkButton
                  variant='secondary'
                  element="a"
                  href={ctaHref2}
                  analyticsString={ctaAnalytics2}
                  idString={ctaIdString2}
                  additionalClasses='sprk-c-Button--full@sm' >

                  {ctaText2}
                </SprkButton>
              </div>
            }
          </div>
          }
        </div>
      }
    </div>
  );
}

SprkHighlightBoard.propTypes = {
  // The source for the image
  imgSrc: PropTypes.string,
  // The alt text for the image
  imgAlt: PropTypes.string,
  // The heading text
  heading: PropTypes.string,
  // The text for the first CTA
  ctaText: PropTypes.string,
  // The href for the first CTA
  ctaHref: PropTypes.string,
  // The data-analytics for the first CTA
  ctaAnalytics: PropTypes.string,
  // The data-id for the first CTA
  ctaIdString: PropTypes.string,
  // The text for the second CTA
  ctaText2: PropTypes.string,
  // The href for the second CTA
  ctaHref2: PropTypes.string,
  // The data-analytics for the second CTA
  ctaAnalytics2: PropTypes.string,
  // The data-id for the second CTA
  ctaIdString2: PropTypes.string,
  // The variant that determines the class names
  variant: PropTypes.oneOf(['noimage', 'stacked']),
  // The string to use for the data-id attribute
  idString: PropTypes.string,
  // Any additional classes to add to the highlight board
  additionalClasses: PropTypes.string
};

export default SprkHighlightBoard;
