// src/react/projects/spark-core-react/src/SprkPagination/SprkPagination.js
import React from 'react';
import PropTypes from 'prop-types';
import classnames from 'classnames';
import { uniqueId } from 'lodash';
import SprkLink from '../SprkLink/SprkLink';
import SprkIcon from '../SprkIcon/SprkIcon';

const SprkPagination = (props) => {
  const goToPage = (e, page) => {
    e.preventDefault();

    const { totalItems, itemsPerPage, onChangeCallback } = props;

    const totalPages = Math.ceil(totalItems / itemsPerPage);

    let newPage = page;
    if (page > totalPages) { newPage = totalPages; }
    if (page < 1) { newPage = 1; }

    onChangeCallback({ e, newPage });
  };

  const {
    variant,
    totalItems,
    itemsPerPage,
    currentPage,
    onChangeCallback,
    additionalClasses,
    nextLinkText,
    prevLinkText,
    analyticsStringNext,
    analyticsStringPrev,
    idString,
    ...other
  } = props;

  const totalPages = Math.ceil(totalItems / itemsPerPage);

  // the "long" variant is used if there are more than 3 total pages
  const longVariant = variant === 'default' && totalPages > 3;

  let leftLinkClasses = 'sprk-c-Pagination__icon';
  let rightLinkClasses = 'sprk-c-Pagination__icon';

  if (currentPage === 1) {
    leftLinkClasses += ' sprk-b-Link--disabled';
  }

  if (currentPage === totalPages) {
    rightLinkClasses += ' sprk-b-Link--disabled';
  }

  return (
    <nav
      aria-label="Pagination Navigation"
      data-id={idString}
    >
      <ul
        className={
          classnames(
            'sprk-c-Pagination',
            'sprk-o-HorizontalList',
            'sprk-o-HorizontalList--spacing-medium',
            additionalClasses,
          )
        }
        {...other}
      >
        <li>
          <SprkLink
            href="#"
            onClick={e => goToPage(e, currentPage - 1)}
            additionalClasses={leftLinkClasses}
            variant="plain"
            analyticsString={analyticsStringPrev}
            aria-label="Previous Page"
          >
            <span className="sprk-u-ScreenReaderText">{prevLinkText}</span>
            <SprkIcon iconName="chevron-left" />
          </SprkLink>
        </li>

        { variant === 'default' && (
          <li key={uniqueId('sprk_page_')}>
            <SprkLink
              onClick={e => goToPage(e, 1)}
              href="#"
              additionalClasses={
                classnames(
                  'sprk-c-Pagination__link',
                  { 'sprk-c-Pagination__link--current': currentPage === 1 },
                )}
              aria-label="Page 1"
              aria-current={currentPage === 1}
            >
              1
            </SprkLink>
          </li>
        )}

        { longVariant && currentPage > 2 && (
          <li key={uniqueId('sprk_page_')}>
            ...
          </li>
        )}

        { longVariant && currentPage > 1 && currentPage < totalPages && (
          <li key={uniqueId('sprk_page_')}>
            <SprkLink
              onClick={e => goToPage(e, currentPage)}
              href="#"
              additionalClasses={
                classnames(
                  'sprk-c-Pagination__link',
                  'sprk-c-Pagination__link--current',
                )
              }
              aria-label={`Page ${currentPage}`}
              aria-current="true"
            >
              {currentPage}
            </SprkLink>
          </li>
        )}

        { longVariant && currentPage < totalPages - 1 && (
          <li key={uniqueId('sprk_page_')}>
            ...
          </li>
        )}

        { longVariant && (
          <li key={uniqueId('sprk_page_')}>
            <SprkLink
              onClick={e => goToPage(e, totalPages)}
              href="#"
              additionalClasses={
                classnames(
                  'sprk-c-Pagination__link',
                  { 'sprk-c-Pagination__link--current': currentPage === totalPages },
                )
              }
              aria-label={`Page ${totalPages}`}
              aria-current={currentPage === totalPages}
            >
              {totalPages}
            </SprkLink>
          </li>
        )}

        { variant === 'default' && !longVariant && totalItems / itemsPerPage > 1 && (
          <li key={uniqueId('sprk_page_')}>
            <SprkLink
              onClick={e => goToPage(e, 2)}
              href="#"
              additionalClasses={
                classnames(
                  'sprk-c-Pagination__link',
                  { 'sprk-c-Pagination__link--current': currentPage === 2 },
                )}
              aria-label="Page 2"
              aria-current={currentPage === 2}
            >
              2
            </SprkLink>
          </li>
        )}

        { variant === 'default' && !longVariant && totalItems / itemsPerPage > 2 && (
          <li key={uniqueId('sprk_page_')}>
            <SprkLink
              onClick={e => goToPage(e, 3)}
              href="#"
              additionalClasses={
                classnames(
                  'sprk-c-Pagination__link',
                  { 'sprk-c-Pagination__link--current': currentPage === 3 },
                )}
              aria-label="Page 3"
              aria-current={currentPage === 3}
            >
              3
            </SprkLink>
          </li>
        )}

        <li>
          <SprkLink
            href="#"
            onClick={e => goToPage(e, currentPage + 1)}
            additionalClasses={rightLinkClasses}
            variant="plain"
            analyticsString={analyticsStringNext}
            aria-label="Next Page"
          >
            <span className="sprk-u-ScreenReaderText">{nextLinkText}</span>
            <SprkIcon iconName="chevron-right" />
          </SprkLink>
        </li>
      </ul>
    </nav>
  );
};


SprkPagination.propTypes = {
  // The pagination variant
  variant: PropTypes.oneOf(['default', 'pager']),
  // The total number of items that the pagination component will page through
  totalItems: PropTypes.number.isRequired,
  // The number of items per page in the component
  itemsPerPage: PropTypes.number.isRequired,
  // The current visible page of the component
  currentPage: PropTypes.number,
  // callback for handling changes.
  onChangeCallback: PropTypes.func.isRequired,
  // Any additional classes to include on the component
  additionalClasses: PropTypes.string,
  // Screenreader text for the 'previous page' chevron
  nextLinkText: PropTypes.string,
  // Screenreader text for the 'next page' chevron
  prevLinkText: PropTypes.string,
  // The data-analytics string for the 'previous page' link
  analyticsStringNext: PropTypes.string,
  // The data-analytics string for the 'next page' link
  analyticsStringPrev: PropTypes.string,
  // The data-id string for the component
  idString: PropTypes.string,
};

SprkPagination.defaultProps = {
  variant: 'default',
  currentPage: 1,
  additionalClasses: '',
  nextLinkText: 'Next Page',
  prevLinkText: 'Previous Page',
  analyticsStringNext: '',
  analyticsStringPrev: '',
  idString: '',
};

export default SprkPagination;

// src/angular/projects/spark-core-angular/src/lib/components/sprk-pagination/sprk-pagination.component.ts
import {
  Component,
  ElementRef,
  EventEmitter,
  Input,
  Output
} from '@angular/core';

@Component({
  selector: 'sprk-pagination',
  template: `
    <nav
      aria-label="Pagination Navigation"
      [ngClass]="getClasses()"
      *ngIf="paginationType === 'default'"
      [attr.data-id]="idString"
    >
      <sprk-unordered-list
        listType="horizontal"
        additionalClasses="sprk-c-Pagination sprk-o-HorizontalList--spacing-medium"
      >
        <li>
          <sprk-link
            linkType="plain"
            (click)="goBack($event, currentPage)"
            [disabled]="currentPage === 1"
            additionalClasses="sprk-c-Pagination__icon"
            href="#"
            [analyticsString]="analyticsStringLinkPrev"
          >
            <span class="sprk-u-ScreenReaderText">{{ prevLinkText }}</span>
            <sprk-icon
              additionalClasses="sprk-c-Icon--stroke-current-color"
              iconType="chevron-left"
            ></sprk-icon>
          </sprk-link>
        </li>

        <li>
          <sprk-link
            (click)="goToPage($event, 1)"
            additionalClasses="sprk-c-Pagination__link {{currentPage === 1 && 'sprk-c-Pagination__link--current'}}"
            href="#"
            [analyticsString]="analyticsStringFirstLink"
            [attr.aria-current]="currentPage === 1"
            aria-label="Page 1"
          >
            1
          </sprk-link>
        </li>

        <li>
          <sprk-link
            (click)="goToPage($event, 2)"
            additionalClasses="sprk-c-Pagination__link {{currentPage === 2 && 'sprk-c-Pagination__link--current'}}"
            href="#"
            [analyticsString]="analyticsStringSecondLink"
            [attr.aria-current]="currentPage === 2"
            aria-label="Page 2"
          >
            2
          </sprk-link>
        </li>

        <li>
          <sprk-link
            (click)="goToPage($event, 3)"
            additionalClasses="sprk-c-Pagination__link {{currentPage === 3 && 'sprk-c-Pagination__link--current'}}"
            href="#"
            [analyticsString]="analyticsStringThirdLink"
            [attr.aria-current]="currentPage === 3"
            aria-label="Page 3"
          >
            3
          </sprk-link>
        </li>

        <li>
          <sprk-link
            linkType="plain"
            [disabled]="isLastPage()"
            (click)="goForward($event, currentPage)"
            additionalClasses="sprk-c-Pagination__icon"
            href="#"
            [analyticsString]="analyticsStringLinkNext"
          >
            <span class="sprk-u-ScreenReaderText">{{ nextLinkText }}</span>
            <sprk-icon
              additionalClasses="sprk-c-Icon--stroke-current-color"
              iconType="chevron-right"
            ></sprk-icon>
          </sprk-link>
        </li>
      </sprk-unordered-list>
    </nav>

    <nav
      aria-label="Pagination Navigation"
      [ngClass]="getClasses()"
      *ngIf="paginationType === 'long'"
      [attr.data-id]="idString"
    >
      <sprk-unordered-list
        listType="horizontal"
        additionalClasses="sprk-c-Pagination sprk-o-HorizontalList--spacing-small"
      >
        <li>
          <sprk-link
            linkType="plain"
            [disabled]="currentPage === 1"
            (click)="goBack($event, currentPage)"
            additionalClasses="sprk-c-Pagination__icon"
            href="#"
          >
            <span class="sprk-u-ScreenReaderText">{{ prevLinkText }}</span>
            <sprk-icon
              additionalClasses="sprk-c-Icon--stroke-current-color"
              iconType="chevron-left"
            ></sprk-icon>
          </sprk-link>
        </li>

        <li>
          <sprk-link
            (click)="goToPage($event, 1)"
            additionalClasses="sprk-c-Pagination__link {{currentPage === 1 && 'sprk-c-Pagination__link--current'}}"
            href="#"
            [analyticsString]="analyticsStringFirstLink"
            aria-label="Page 1"
          >
            1
          </sprk-link>
        </li>

        <li
          [ngClass]="{
            'sprk-u-Display--none': currentPage === 1 || currentPage === 2
          }"
        >
          ...
        </li>

        <li
          [ngClass]="{
            'sprk-u-Display--none':
              currentPage === 1 || currentPage === totalPages()
          }"
        >
          <sprk-link
            (click)="goToPage($event, currentPage)"
            additionalClasses="sprk-c-Pagination__link sprk-c-Pagination__link--current"
            href="#"
            aria-current="true"
            [analyticsString]="analyticsStringSecondLink"
            attr.aria-label="Page {{ currentPage }}"
          >
            {{ currentPage }}
          </sprk-link>
        </li>

        <li
          [ngClass]="{
            'sprk-u-Display--none':
              currentPage === totalPages() || currentPage === totalPages() - 1
          }"
        >
          ...
        </li>

        <li>
          <sprk-link
            (click)="goToPage($event, totalPages())"
            additionalClasses="sprk-c-Pagination__link {{currentPage === totalPages() && 'sprk-c-Pagination__link--current'}}"
            href="#"
            [analyticsString]="analyticsStringThirdLink"
            attr.aria-label="Page {{ totalPages() }}"
          >
            {{ totalPages() }}
          </sprk-link>
        </li>

        <li>
          <sprk-link
            linkType="plain"
            [disabled]="isLastPage()"
            (click)="goForward($event, currentPage)"
            additionalClasses="sprk-c-Pagination__icon"
            href="#"
            [analyticsString]="analyticsStringLinkNext"
          >
            <span class="sprk-u-ScreenReaderText">Next</span>
            <sprk-icon
              additionalClasses="sprk-c-Icon--stroke-current-color"
              iconType="chevron-right"
            ></sprk-icon>
          </sprk-link>
        </li>
      </sprk-unordered-list>
    </nav>

    <nav
      aria-label="Pagination Navigation"
      [ngClass]="getClasses()"
      *ngIf="paginationType === 'pager'"
      [attr.data-id]="idString"
    >
      <sprk-unordered-list
        listType="horizontal"
        additionalClasses="sprk-c-Pagination sprk-o-HorizontalList--spacing-large"
      >
        <li class="sprk-c-Pagination__item">
          <sprk-link
            linkType="plain"
            [disabled]="currentPage === 1"
            (click)="goBack($event, currentPage)"
            additionalClasses="sprk-c-Pagination__icon sprk-b-Link--simple"
            href="#"
            [analyticsString]="analyticsStringLinkPrev"
          >
            <span class="sprk-u-ScreenReaderText">{{ prevLinkText }}</span>
            <sprk-icon
              additionalClasses="sprk-c-Icon--stroke-current-color"
              iconType="chevron-left"
            ></sprk-icon>
          </sprk-link>
        </li>

        <li class="sprk-c-Pagination__item">
          <sprk-link
            linkType="plain"
            [disabled]="isLastPage()"
            (click)="goForward($event, currentPage)"
            additionalClasses="sprk-c-Pagination__icon sprk-b-Link--simple"
            href="#"
            [analyticsString]="analyticsStringLinkNext"
          >
            <span class="sprk-u-ScreenReaderText">{{ nextLinkText }}</span>
            <sprk-icon
              additionalClasses="sprk-c-Icon--stroke-current-color"
              iconType="chevron-right"
            ></sprk-icon>
          </sprk-link>
        </li>
      </sprk-unordered-list>
    </nav>
  `
})
export class SparkPaginationComponent {
  @Input()
  paginationType = 'default'; // default, long, pager
  @Input()
  nextLinkText = 'Next'; // Text to display for next link
  @Input()
  prevLinkText = 'Prev'; // Text to display for previous link
  @Input()
  currentPage = 1; // The currently active page
  @Input()
  totalItems: number; // Total number of items
  @Input()
  itemsPerPage: number; // Total number of items to show per page
  @Input()
  analyticsStringFirstLink: string;
  @Input()
  analyticsStringSecondLink: string;
  @Input()
  analyticsStringThirdLink: string;
  @Input()
  analyticsStringLinkNext: string;
  @Input()
  analyticsStringLinkPrev: string;
  @Input()
  idString: string;
  @Input()
  additionalClasses: string;

  // Will be emitted to the parent component on the click event
  @Output()
  previousClick = new EventEmitter();
  @Output()
  nextClick = new EventEmitter();
  @Output()
  pageClick = new EventEmitter<object>();

  goToPage(event, page): void {
    event.preventDefault();
    // Update currentPage to new selected page
    this.currentPage = page;
    // Emit out click event and page when clicked
    this.pageClick.emit({ event, page });
  }

  goBack(event, page): void {
    event.preventDefault();
    if (this.currentPage > 1) {
      this.currentPage = this.currentPage - 1;
    }
    this.previousClick.emit({ event, page });
  }

  goForward(event, page): void {
    event.preventDefault();
    if (this.currentPage < this.totalPages()) {
      this.currentPage = this.currentPage + 1;
    }
    this.nextClick.emit({ event, page });
  }

  // Returns total # of
  // pages based on total # of
  // items & desired # of items to show per page
  totalPages(): number {
    return Math.ceil(this.totalItems / this.itemsPerPage);
  }

  // Returns true if currently on the last page
  isLastPage(): boolean {
    return this.currentPage === this.totalPages();
  }

  getClasses(): string {
    const classArray: string[] = [''];

    if (this.additionalClasses) {
      this.additionalClasses.split(' ').forEach(className => {
        classArray.push(className);
      });
    }

    return classArray.join(' ');
  }
  constructor(public ref: ElementRef) {}
}
