// src/react/projects/spark-react/src/SprkStepper/components/SprkStepperSlider/SprkStepperSlider.js
import React, { Component } from 'react';
import PropTypes from 'prop-types';
import classnames from 'classnames';

class SprkStepperSlider extends Component {
  render() {
    const {
      title,
      contents,
      sliderStyle,
    } = this.props;

    return (
      <li className={classnames(
        'sprk-c-Stepper__slider',
        'sprk-c-Stepper__slider--active',
        )}
        style={sliderStyle}
      >
        <div className='sprk-c-Stepper__step-content sprk-c-Stepper__step-content--has-description' >
          <span className="sprk-c-Stepper__step-header sprk-b-Link sprk-b-Link--plain" >
            <span className="sprk-c-Stepper__step-icon sprk-u-Visibility--hidden" />
            <h3 className="sprk-c-Stepper__step-heading" >
              {title}
            </h3>
          </span>

          <div className="sprk-c-Stepper__step-description" >
            <p className="sprk-b-TypeBodyTwo">
              {contents}
            </p>
          </div>
        </div>
      </li>
    );
  };
}

SprkStepperSlider.propTypes = {
  // The title text for the slider
  title: PropTypes.string,
  // The contents text for the slider
  contents: PropTypes.string,
  // An object representing the style properties of this component. The important property is "top".
  sliderStyle: PropTypes.object,
};

export default SprkStepperSlider;

// src/angular/projects/spark-angular/src/lib/components/sprk-stepper/sprk-stepper-slider/sprk-stepper-slider.component.ts
import { Component, Input, OnChanges, AfterContentInit } from '@angular/core';

@Component({
  selector: 'sprk-stepper-slider',
  template: `
    <li
      class="sprk-c-Stepper__slider sprk-c-Stepper__slider--active sprk-u-Width-100"
      [ngStyle]="myStyle"
      *ngIf="selected && hasDescription"
    >
      <div
        class="sprk-c-Stepper__step-content sprk-c-Stepper__step-content--has-description"
      >
        <span
          class="sprk-c-Stepper__step-header sprk-b-Link sprk-b-Link--plain"
        >
          <span
            class="sprk-c-Stepper__step-icon sprk-u-Visibility--hidden"
          ></span>
          <h3 class="sprk-c-Stepper__step-heading" data-sprk-stepper="heading">
            {{ title }}
          </h3>
        </span>
        <div class="sprk-c-Stepper__step-description">
          <ng-container [ngTemplateOutlet]="content"></ng-container>
        </div>
      </div>
    </li>
  `
})
export class SprkStepperSliderComponent implements OnChanges, AfterContentInit {
  name = 'Angular';
  @Input() offsetTop = 0;
  @Input() title: string;
  @Input() content;
  @Input() selected: boolean;
  @Input() hasDescription: boolean;

  myStyle;

  ngOnChanges() {
    /// NEEDS LEFT OFFSET
    this.myStyle = { top: this.offsetTop + 'px' };
  }

  ngAfterContentInit() {}
}
