// react/src/components/accordions/components/SprkAccordionItem/SprkAccordionItem.js
import React, { Component } from 'react';
import AnimateHeight from 'react-animate-height';
import PropTypes from 'prop-types';
import classnames from 'classnames';
import SprkIcon from '../../../icons/SprkIcon';
import SprkLink from '../../../../base/links/SprkLink';

class SprkAccordionItem extends Component {
  constructor(props) {
    super(props);
    // TODO: Remove isDefaultOpen in future issue #1299
    const { isDefaultOpen, isOpen = isDefaultOpen } = this.props;
    this.state = {
      isOpen: isOpen || false,
      height: isOpen ? 'auto' : 0,
    };
    this.toggle = this.toggle.bind(this);
  }

  toggle(e) {
    const { onToggle } = this.props;
    e.preventDefault();
    this.setState((prevState) => ({
      isOpen: !prevState.isOpen,
      height: !prevState.isOpen ? 'auto' : 0,
    }));
    if (onToggle) onToggle(e);
  }

  /* TODO: Remove headingAddClasses, contentAddClasses,
  iconAddClasses in future issue #1299 */
  render() {
    const {
      analyticsString,
      idString,
      children,
      heading,
      headingAddClasses,
      headingAdditionalClasses = headingAddClasses,
      additionalClasses,
      contentAddClasses,
      contentAdditionalClasses = contentAddClasses,
      iconAddClasses,
      iconAdditionalClasses = iconAddClasses,
      id,
      iconNameOpen,
      iconNameClosed,
      leadingIcon,
      ...other
    } = this.props;
    const { isOpen, height } = this.state;

    const iconClasses = classnames(
      'sprk-c-Icon--toggle sprk-c-Accordion__icon sprk-c-Icon--xl',
      { 'sprk-c-Icon--open': isOpen },
      iconAdditionalClasses,
    );

    const itemClassNames = classnames(
      'sprk-c-Accordion__item',
      { 'sprk-c-Accordion__item--open': isOpen },
      additionalClasses,
    );

    const headingClassNames = classnames(
      'sprk-c-Accordion__heading',
      'sprk-b-TypeDisplaySeven',
      headingAdditionalClasses,
    );

    return (
      <li className={itemClassNames} data-id={idString} {...other}>
        <SprkLink
          variant="unstyled"
          element="button"
          aria-controls={id}
          additionalClasses="sprk-c-Accordion__summary"
          data-analytics={analyticsString}
          onClick={this.toggle}
          aria-expanded={isOpen ? 'true' : 'false'}
        >
          {leadingIcon && (
            <SprkIcon
              iconName={leadingIcon}
              additionalClasses="
                      sprk-c-Icon--filled-current-color
                      sprk-c-Icon--xl sprk-u-mrs"
            />
          )}
          <h3 className={headingClassNames}>{heading}</h3>
          <SprkIcon
            iconName={isOpen ? iconNameOpen : iconNameClosed}
            additionalClasses={iconClasses}
          />
        </SprkLink>

        <AnimateHeight duration={300} height={height}>
          <div
            className={classnames(
              'sprk-c-Accordion__content',
              contentAdditionalClasses,
            )}
            id={id}
          >
            {children}
          </div>
        </AnimateHeight>
      </li>
    );
  }
}

SprkAccordionItem.defaultProps = {
  iconNameOpen: 'chevron-up-circle',
  iconNameClosed: 'chevron-up-circle',
};

SprkAccordionItem.propTypes = {
  /**
   * Children content for the item.
   */
  children: PropTypes.node,
  /**
   * Assigned to the `data-analytics` attribute serving as a unique selector
   * for outside libraries to capture data.
   */
  analyticsString: PropTypes.string,
  /**
   * The text for the item heading.
   */
  heading: PropTypes.string.isRequired,
  // TODO remove as part of Issue 1299
  /**
   * Deprecated - use `headingAdditionalClasses` instead. Expects a space
   * separated string of classes to be added to the heading.
   */
  headingAddClasses: PropTypes.string,
  /**
   * Expects a space separated string of classes to be added to the heading.
   */
  headingAdditionalClasses: PropTypes.string,
  /**
   * A space-separated string of classes to add to the outermost container of
   * the component.
   */
  additionalClasses: PropTypes.string,
  /**
   * Assigned to the `data-id` attribute serving as a unique selector for
   * automated tools.
   */
  idString: PropTypes.string,
  // TODO remove as part of Issue 1299
  /**
   * Deprecated - Use `isOpen` instead.
   * Used to specify whether the item should be open by default.
   */
  isDefaultOpen: PropTypes.bool,
  /**
   * Used to specify whether the item is opened or closed.
   */
  isOpen: PropTypes.bool,
  // TODO remove as part of Issue 1299
  /**
   * Deprecated - use `iconAdditionalClasses` instead. Expects a space
   * separated string of classes to be added to the icon.
   */
  iconAddClasses: PropTypes.string,
  /**
   * Expects a space separated string of classes to be added to the icon.
   */
  iconAdditionalClasses: PropTypes.string,
  // TODO remove as part of Issue 1299
  /**
   * Deprecated - use `contentAdditionalClasses` instead. Expects a space
   * separated string of classes to be added to the toggle content.
   */
  contentAddClasses: PropTypes.string,
  /**
   * Expects a space separated string of classes to be added to the toggle
   * content.
   */
  contentAdditionalClasses: PropTypes.string,
  /**
   * A unique ID for the accordion item.
   */
  id: PropTypes.string,
  /**
   * A function to be called when the Accordion item is toggled.
   */
  onToggle: PropTypes.func,
  /**
   * The name of the icon to use when the Accordion item is open
   */
  iconNameOpen: PropTypes.string,
  /**
   * The name of the icon to use when the Accordion item is closed
   */
  iconNameClosed: PropTypes.string,
  /**
   * The name of the icon to use before
   * the title in the Accordion item.
   * This is optional.
   */
  leadingIcon: PropTypes.string,
};

export default SprkAccordionItem;

// angular/projects/spark-angular/src/lib/components/sprk-accordion-item/sprk-accordion-item.component.ts
import { Component, Input, Output, OnInit, EventEmitter } from '@angular/core';
import * as _ from 'lodash';
import { toggleAnimations } from '../sprk-toggle/sprk-toggle-animations';

// TODO Remove title, additionalHeadingClasses, iconTypeClosed,
// iconTypeOpen, isActive as part of Issue 3597
@Component({
  selector: 'sprk-accordion-item',
  template: `
    <li [ngClass]="getClasses()">
      <button
        sprkLink
        variant="unstyled"
        href="#"
        [attr.aria-controls]="accordion_controls_id"
        [attr.aria-expanded]="isOpen"
        class="sprk-c-Accordion__summary"
        [analyticsString]="analyticsString"
        [idString]="idString"
        (click)="toggleAccordion($event)"
      >
        <span [ngClass]="getHeadingClasses()">
          <sprk-icon
            *ngIf="leadingIcon"
            [iconName]="leadingIcon"
            additionalClasses="
              sprk-c-Icon--filled-current-color
              sprk-c-Icon--xl
              sprk-u-mrs"
          ></sprk-icon>
          {{ heading || title }}
        </span>

        <sprk-icon
          [additionalClasses]="getIconClasses()"
          [iconName]="currentIconName"
        ></sprk-icon>
      </button>

      <div [@toggleContent]="animState">
        <div [id]="accordion_controls_id" [ngClass]="getContentClasses()">
          <ng-content></ng-content>
        </div>
      </div>
    </li>
  `,
  animations: [toggleAnimations.toggleContent],
})
export class SprkAccordionItemComponent implements OnInit {
  // TODO - Remove as part of Issue 3597
  /**
   * Deprecated: use `heading` instead. The value supplied will be
   * rendered inside the heading area of the Accordion Item.
   */
  @Input()
  title: string;
  /**
   * The value supplied will be rendered inside the heading area of the
   * Accordion Item.
   */
  @Input()
  heading: string;
  /**
   * The value supplied will be assigned to the `data-analytics` attribute
   * on the component. Intended for an outside library to capture data.
   */
  @Input()
  analyticsString: string;
  /**
   * The value supplied will be assigned to the `data-id` attribute on the
   * component. This is intended to be used as a selector for automated tools.
   * This value should be unique per page.
   */
  @Input()
  idString: string;
  /**
   * Expects a space separated string of classes to be added to the component.
   */
  @Input()
  additionalClasses: string;
  // TODO - Remove as part of Issue 3597
  /**
   * Deprecated - use `headingAdditionalClasses` instead. Expects a space
   * separated string of classes to be added to the heading in the Accordion
   * Item.
   */
  @Input()
  additionalHeadingClasses: string;
  /**
   * Expects a space separated string of classes to be added to the heading in
   * the Accordion Item.
   */
  @Input()
  headingAdditionalClasses: string;
  /**
   * The Accordion item will use this to decide if it should be open or closed
   * on first render. (Interacting with the toggle will override this input.)
   */
  @Input()
  isOpen = false;
  // TODO - Remove as part of Issue 3597
  /**
   * Deprecated - use additionalClasses instead. If `true`, the active class
   * will be applied to the item.
   */
  @Input()
  isActive: boolean;
  // TODO - Remove this input and move the default value to iconNameClosed
  // as part of issue 3597
  /**
   * Deprecated - use `iconNameClosed` instead. The name of the icon to use for
   * a closed Accordion Item.
   */
  @Input()
  iconTypeClosed = 'chevron-up-circle';
  /**
   * The name of the icon to use for a closed Accordion Item.
   */
  @Input()
  iconNameClosed;
  // TODO - Remove this input and move the default value to iconNameOpen
  // as part of issue 3597
  /**
   * Deprecated - use `iconNameOpen` instead. The name of the icon to use for
   * an open Accordion Item.
   */
  @Input()
  iconTypeOpen = 'chevron-up-circle';
  /**
   * The name of the icon to use for an open Accordion Item.
   */
  @Input()
  iconNameOpen;
  /**
   * The name of the icon to use before the heading in the Accordion Item.
   * This is optional.
   */
  @Input()
  leadingIcon: string;
  /**
   * Expects a space separated string of classes to be added to the Accordion
   * Item icon.
   */
  @Input()
  iconAdditionalClasses: string;
  /**
   * Expects a space separated string of classes to be added to the Accordion
   * Item content container.
   */
  @Input()
  contentAdditionalClasses: string;

  /**
   * This event will be emitted when the Accordion Item is opened.
   */
  @Output()
  openedEvent = new EventEmitter<any>();
  /**
   * This event will be emitted when the Accordion Item is closed.
   */
  @Output()
  closedEvent = new EventEmitter<any>();

  /**
   * @ignore
   */
  componentID = _.uniqueId();
  /**
   * @ignore
   */
  accordion_controls_id = `accordionHeading__${this.componentID}`;
  // TODO replace default value with iconNameClosed as part of issue 3597
  /**
   * @ignore
   */
  public currentIconName = this.iconTypeClosed;
  /**
   * @ignore
   */
  public iconStateClass = '';
  /**
   * @ignore
   */
  public animState = 'closed';

  /**
   * @ignore
   */
  toggleState(): void {
    if (this.isOpen) {
      this.animState = 'open';
      // TODO - Remove iconTypeOpen as part of Issue 3597
      this.currentIconName = this.iconNameOpen || this.iconTypeOpen;
      this.iconStateClass = 'sprk-c-Icon--open';
    } else {
      this.animState = 'closed';
      // TODO - Remove iconTypeClosed as part of Issue 3597
      this.currentIconName = this.iconNameClosed || this.iconTypeClosed;
      this.iconStateClass = '';
    }
  }

  /**
   * @ignore
   */
  toggleAccordion(event): void {
    event.preventDefault();
    this.isOpen = !this.isOpen;
    if (this.isOpen) {
      this.openedEvent.emit();
    } else {
      this.closedEvent.emit();
    }
    this.toggleState();
  }

  /**
   * @ignore
   */
  getClasses(): string {
    const classArray: string[] = [
      'sprk-c-Accordion__item',
      'sprk-u-Overflow--hidden',
    ];

    if (this.isOpen) {
      classArray.push('sprk-c-Accordion__item--open');
    }

    if (this.isActive) {
      classArray.push('sprk-c-Accordion__item--active');
    }

    if (this.additionalClasses) {
      this.additionalClasses.split(' ').forEach((className) => {
        classArray.push(className);
      });
    }

    return classArray.join(' ');
  }

  /**
   * @ignore
   */
  getHeadingClasses(): string {
    const classArray: string[] = [
      'sprk-c-Accordion__heading',
      'sprk-b-TypeDisplaySeven',
    ];

    // TODO - Remove additionalHeadingClasses as part of Issue 3597
    const additionalClasses =
      this.headingAdditionalClasses || this.additionalHeadingClasses;

    if (additionalClasses) {
      additionalClasses.split(' ').forEach((className) => {
        classArray.push(className);
      });
    }

    return classArray.join(' ');
  }

  /**
   * @ignore
   */
  getIconClasses(): string {
    const classArray: string[] = [
      'sprk-c-Accordion__icon',
      'sprk-c-Icon--xl',
      'sprk-c-Icon--toggle',
      this.iconStateClass,
    ];

    if (this.iconAdditionalClasses) {
      this.iconAdditionalClasses.split(' ').forEach((className) => {
        classArray.push(className);
      });
    }

    return classArray.join(' ');
  }

  /**
   * @ignore
   */
  getContentClasses(): string {
    const classArray: string[] = ['sprk-c-Accordion__content'];

    if (this.contentAdditionalClasses) {
      this.contentAdditionalClasses.split(' ').forEach((className) => {
        classArray.push(className);
      });
    }

    return classArray.join(' ');
  }

  ngOnInit() {
    this.toggleState();
  }
}
