// spark/components/promo/angular/sprk-promo.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'sprk-promo',
  template: `
    <div [ngClass]="getClasses()" [attr.data-id]="idString">
      <sprk-link
        linkType="unstyled"
        *ngIf="isFlag && !mediaRev"
        [additionalClasses]="getClassesFlag()"
        [href]="imgHref"
        [analyticsString]="flagLinkAnalytics"
      >
        <img
          class="sprk-c-Promo__image--flag"
          alt="{{ imgAlt }}"
          src="{{ imgSrc }}"
        />
      </sprk-link>
      <sprk-link
        linkType="unstyled"
        *ngIf="imgSrc && !mediaRev && !isFlag"
        [href]="imgHref"
        [analyticsString]="imgLinkAnalytics"
        [additionalClasses]="getClassesImg()"
      >
        <img
          class="sprk-c-Promo__image"
          alt="{{ imgAlt }}"
          src="{{ imgSrc }}"
        />
      </sprk-link>

      <div [ngClass]="getClassesContent()">
        <h3
          *ngIf="title"
          class="sprk-b-TypeDisplayFive sprk-o-Stack__item sprk-c-Promo__title"
        >
          {{ title }}
        </h3>

        <div *ngIf="subtitle" class="sprk-c-Promo__subtitle sprk-o-Stack__item">
          {{ subtitle }}
        </div>

        <div class="sprk-b-TypeBodyTwo sprk-o-Stack__item">
          <ng-content></ng-content>
        </div>

        <div *ngIf="cta === 'button'" class="sprk-o-Stack__item">
          <sprk-link
            linkType="unstyled"
            [href]="buttonHref"
            additionalClasses="sprk-c-Button"
            [analyticsString]="buttonLinkAnalytics"
          >
            {{ ctaText }}
          </sprk-link>
        </div>

        <sprk-link
          linkType="simple"
          *ngIf="cta === 'link'"
          [href]="ctaLinkHref"
          additionalClasses="sprk-o-Stack__item"
          [analyticsString]="ctaLinkAnalytics"
        >
          {{ ctaText }}
        </sprk-link>
      </div>

      <sprk-link
        linkType="unstyled"
        *ngIf="isFlag && mediaRev"
        [href]="imgHref"
        [additionalClasses]="getClassesFlag()"
        [analyticsString]="flagLinkAnalytics"
      >
        <img
          class="sprk-c-Promo__image--flag"
          alt="{{ imgAlt }}"
          src="{{ imgSrc }}"
        />
      </sprk-link>

      <sprk-link
        linkType="unstyled"
        *ngIf="imgSrc && mediaRev && !isFlag"
        [href]="imgHref"
        [analyticsString]="imgLinkAnalytics"
        [additionalClasses]="getClassesImg()"
      >
        <img
          class="sprk-c-Promo__image"
          alt="{{ imgAlt }}"
          src="{{ imgSrc }}"
        />
      </sprk-link>
    </div>
  `
})
export class SprkPromoComponent {
  @Input()
  title: string;
  @Input()
  subtitle: string;
  @Input()
  cta: string; // 'link' or 'button'
  @Input()
  ctaText: string;
  @Input()
  buttonHref: string;
  @Input()
  buttonLinkAnalytics: string;
  @Input()
  ctaLinkHref: string;
  @Input()
  ctaLinkAnalytics: string;
  @Input()
  additionalClasses: string;
  @Input()
  additionalClassesContent: string;
  @Input()
  isFlag: boolean; // if true, use the flag variant
  @Input()
  additionalClassesFlagLink: string;
  @Input()
  flagLinkAnalytics: string;
  @Input()
  imgSrc: string;
  @Input()
  imgAlt: string;
  @Input()
  imgHref: string;
  @Input()
  imgLinkAnalytics: string;
  @Input()
  additionalClassesImgLink: string;
  @Input()
  mediaRev: boolean;
  @Input()
  hasBorder: boolean;
  @Input()
  idString: string;

  getClasses(): string {
    const classArray: string[] = [
      'sprk-c-Promo',
      'sprk-o-Stack',
      'sprk-o-Stack--split@s'
    ];

    if (this.isFlag) {
      classArray.push('sprk-c-Promo--flag');
    }

    if (this.hasBorder) {
      classArray.push('sprk-c-Promo--bordered');
    }

    if (this.additionalClasses) {
      this.additionalClasses.split(' ').forEach(className => {
        classArray.push(className);
      });
    }
    return classArray.join(' ');
  }

  getClassesFlag(): string {
    const classArray: string[] = [
      'sprk-o-Stack__item--fourth@s',
      'sprk-o-Stack__item'
    ];

    if (this.additionalClassesFlagLink) {
      this.additionalClassesFlagLink.split(' ').forEach(className => {
        classArray.push(className);
      });
    }
    return classArray.join(' ');
  }

  getClassesImg(): string {
    const classArray: string[] = [
      'sprk-o-Stack__item',
      'sprk-o-Stack__item--half@s'
    ];

    if (this.additionalClassesImgLink) {
      this.additionalClassesImgLink.split(' ').forEach(className => {
        classArray.push(className);
      });
    }
    return classArray.join(' ');
  }

  getClassesContent(): string {
    const classArray: string[] = [
      'sprk-c-Promo__content',
      'sprk-o-Stack__item',
      'sprk-o-Stack',
      'sprk-o-Stack--large'
    ];

    if (this.isFlag) {
      classArray.push('sprk-o-Stack__item--three-fourths@s');
    } else {
      if (this.imgSrc) {
        classArray.push('sprk-o-Stack__item--half@s');
      }
    }

    if (this.additionalClassesContent) {
      this.additionalClassesContent.split(' ').forEach(className => {
        classArray.push(className);
      });
    }
    return classArray.join(' ');
  }
}

// src/react/projects/spark-core-react/src/SprkPromo/SprkPromo.js
import React from 'react';
import PropTypes from 'prop-types';
import classnames from 'classnames';


const SprkPromo = (props) => {
  const { title, subtitle, children, cta, ctaText, buttonHref, buttonLinkAnalytics, ctaLinkHref, ctaLinkAnalytics, additionalClasses, additionalClassesContent, isFlag, additionalClassesFlagLink, flagLinkAnalytics, imgSrc, imgAlt, imgHref, imgLinkAnalytics, additionalClassesImgLink, mediaRev, hasBorder, idString } = props;
  
  return (
    <div
      className={
        classnames(
          'sprk-b-Promo',
          'sprk-o-Stack',
          'sprk-o-Stack--split@s',
          {'sprk-c-Promo--flag': isFlag},
          {'sprk-c-Promo--bordered': hasBorder},
          additionalClasses
        )}
      data-id={idString}>
      
      {isFlag && !mediaRev && 
        <a
          href={imgHref}
          className={
            classnames(
              'sprk-o-Stack__item--fourth@s',
              'sprk-o-Stack__item',
              additionalClassesFlagLink
            )}
          data-analytics={flagLinkAnalytics}>
            <img
              className="sprk-c-Promo__image--flag"
              alt={imgAlt}
              src={imgSrc}
            />
        </a>
      }

      {imgSrc && !mediaRev && !isFlag && 
        <a
          href={imgHref}
          className={
            classnames(
              'sprk-o-Stack__item',
              'sprk-o-Stack__item--half@s',
              additionalClassesImgLink
            )}
          data-analytics={imgLinkAnalytics}>
            <img
              className="sprk-c-Promo__image"
              alt={imgAlt}
              src={imgSrc}
            />
        </a>
      }

      <div className={
        classnames(
          'sprk-c-Promo__content',
          'sprk-o-Stack__item',
          'sprk-o-Stack',
          'sprk-o-Stack--large',
          {'sprk-o-Stack__item--three-fourths@s': isFlag},
          {'sprk-o-Stack__item--half@s': imgSrc},
          additionalClassesContent
        )
      } >
        {title && 
          <h3 className = "sprk-b-TypeDisplayFive sprk-o-Stack__item sprk-c-Promo__title">
            {title}
          </h3>
        }

        {subtitle && 
          <div className="sprk-c-Promo__subtitle sprk-o-Stack__item">
            {subtitle}
          </div>
        }

        <div className="sprk-b-TypeBodyTwo sprk-o-Stack__item">
          {children}
        </div>

          {cta === 'button' && 
            <div className='sprk-o-Stack__item'>
              <a
                href={buttonHref}
                className="sprk-c-Button"
                data-analytics={buttonLinkAnalytics}
                >
                {ctaText}  
              </a>
            </div>
          }

          {cta === 'link' &&
            <a
              href={ctaLinkHref}
              className="sprk-o-Stack__item sprk-b-Link sprk-b-Link--simple"
              data-analytics={ctaLinkAnalytics}
              >
              {ctaText}
            </a>
          }
      </div>

      {isFlag && mediaRev && 
        <a
          href={imgHref}
          className={
            classnames(
              'sprk-o-Stack__item--fourth@s',
              'sprk-o-Stack__item',
              additionalClassesFlagLink
            )}
          data-analytics={flagLinkAnalytics}>
            <img
              className="sprk-c-Promo__image--flag"
              alt={imgAlt}
              src={imgSrc}
            />
        </a>
      }

      {imgSrc && mediaRev && !isFlag && 
        <a
          href={imgHref}
          className={
            classnames(
              'sprk-o-Stack__item',
              'sprk-o-Stack__item--half@s',
              additionalClassesImgLink
            )}
          data-analytics={imgLinkAnalytics}>
            <img
              className="sprk-c-Promo__image"
              alt={imgAlt}
              src={imgSrc}
            />
        </a>
      }
    </div>
  );
}

SprkPromo.propTypes = {
  title: PropTypes.string,
  subtitle: PropTypes.string,
  content: PropTypes.node,
  cta: PropTypes.string,
  ctaText: PropTypes.string,
  buttonHref: PropTypes.string,
  buttonLinkAnalytics: PropTypes.string,
  ctaLinkHref: PropTypes.string,
  ctaLinkAnalytics: PropTypes.string,
  additionalClasses: PropTypes.string, 
  additionalClassesContent: PropTypes.string,
  isFlag: PropTypes.bool,
  additionalClassesFlagLink: PropTypes.string,
  flagLinkAnalytics: PropTypes.string,
  imgSrc: PropTypes.string,
  imgAlt: PropTypes.string,
  imgHref: PropTypes.string,
  imgLinkAnalytics: PropTypes.string,
  additionalClassesImgLink: PropTypes.string,
  mediaRev: PropTypes.bool,
  hasBorder: PropTypes.bool,
  idString: PropTypes.string

  // The promo variant that determines the class names
  // variant: PropTypes.oneOf(['base', 'asdf']),
};

export default SprkPromo;
