// angular/projects/spark-angular/src/lib/components/sprk-table/sprk-table.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'sprk-table',
  template: `
    <div [ngClass]="getClasses()" [attr.data-id]="idString">
      <table [ngClass]="getTableClasses()">
        <ng-content></ng-content>
      </table>
    </div>
  `
})
export class SprkTableComponent {
  /**
   * Expects a space separated string
   * of classes to be added to the
   * component container.
   */
  @Input()
  additionalClasses: string;
  /**
   * Expects a space separated string
   * of classes to be added to the
   * table element.
   */
  @Input()
  additionalTableClasses: string;
  /**
   * The value supplied will be assigned
   * to the 'data-id' attribute on the
   * component. This is intended to be
   * used as a selector for automated
   * tools. This value should be unique
   * per page.
   */
  @Input()
  idString: string;

  getClasses(): string {
    const classArray: string[] = ['sprk-b-TableContainer'];

    if (this.additionalClasses) {
      this.additionalClasses.split(' ').forEach(className => {
        classArray.push(className);
      });
    }

    return classArray.join(' ');
  }

  getTableClasses(): string {
    const classArray: string[] = [
      'sprk-b-Table',
      'sprk-b-Table--spacing-medium',
      'sprk-b-Table--striped-even',
      'sprk-b-Table--bordered-columns',
      'sprk-b-Table--bordered-columns-inside'
    ];

    if (this.additionalTableClasses) {
      this.additionalTableClasses.split(' ').forEach(className => {
        classArray.push(className);
      });
    }

    return classArray.join(' ');
  }
}

// react/src/base/tables/SprkTable.js
import React from 'react';
import PropTypes from 'prop-types';
import classnames from 'classnames';
import uniqueId from 'lodash/uniqueId';

const SprkTable = (props) => {
  const {
    rows,
    columns,
    variant,
    idString,
    additionalContainerClasses,
    additionalTableClasses,
    children,
    ...other
  } = props;

  const wrapperClassNames = classnames(
    'sprk-b-TableContainer',
    additionalContainerClasses,
  );

  const tableClassNames = classnames(
    'sprk-b-Table',
    { 'sprk-b-Table--secondary': variant === 'secondary' },
    {
      'sprk-b-Table--secondary-row-comparison':
        variant === 'secondaryRowComparison',
    },
    { 'sprk-b-Table--grouped-columns': variant === 'grouped' },
    { 'sprk-b-Table--row-comparison': variant === 'rowComparison' },
    additionalTableClasses,
  );

  if (variant === 'grouped') {
    return (
      <div className={wrapperClassNames} data-id={idString}>
        <table className={tableClassNames} {...other}>
          <thead className="sprk-b-Table__head">
            {columns.length > 0
              && columns.map(row => (
                <tr key={uniqueId('row_')}>
                  {row.map(col => (
                    <th
                      key={uniqueId('th')}
                      rowSpan={col.rowspan}
                      colSpan={col.colspan}
                    >
                      {col.header}
                    </th>
                  ))}
                </tr>
              ))}
          </thead>

          {rows.length > 0 && (
            <tbody>
              {rows.map(row => (
                <tr key={uniqueId('row_')}>
                  {row.map(item => (
                    <td key={uniqueId('td_')}>{item}</td>
                  ))}
                </tr>
              ))}
            </tbody>
          )}
        </table>
      </div>
    );
  }
  if (variant === 'rowComparison') {
    return (
      <div className={wrapperClassNames} data-id={idString}>
        <table className={tableClassNames} {...other}>
          <thead className="sprk-b-Table__head">
            {columns.length > 0 && (
              <tr>
                <th className="sprk-b-Table__empty-heading" />
                {columns.map(col => (
                  <th key={uniqueId('th_')}>{col.header}</th>
                ))}
              </tr>
            )}
          </thead>

          {rows.length > 0 && (
            <tbody>
              {rows.map(row => (
                <tr key={uniqueId('row_')}>
                  <th>{row.rowHeading}</th>
                  {columns.length > 0
                    && columns.map(col => (
                      <td key={uniqueId('td_')}>{row[col.name]}</td>
                    ))}
                </tr>
              ))}
            </tbody>
          )}
        </table>
      </div>
    );
  }
  if (variant === 'secondaryRowComparison') {
    return (
      <div className={wrapperClassNames} data-id={idString}>
        <table className={tableClassNames} {...other}>
          {rows.length > 0 && (
            <tbody>
              {rows.map(row => (
                <tr key={uniqueId('row_')}>
                  <th>{row.rowHeading}</th>
                  {columns.length > 0
                    && columns.map(col => (
                      <td key={uniqueId('td_')}>{row[col.name]}</td>
                    ))}
                  {row.button && <td>{row.button}</td>}
                </tr>
              ))}
            </tbody>
          )}
        </table>
      </div>
    );
  }

  if (variant === 'html') {
    return (
      <div className={wrapperClassNames} data-id={idString}>
        <table className={tableClassNames} {...other}>
          {children}
        </table>
      </div>
    );
  }
  return (
    <div className={wrapperClassNames} data-id={idString}>
      <table className={tableClassNames} {...other}>
        <thead className="sprk-b-Table__head">
          {columns.length > 0 && (
            <tr>
              {columns.map(col => (
                <th key={uniqueId('th_')}>{col.header}</th>
              ))}
            </tr>
          )}
        </thead>

        {rows.length > 0 && (
          <tbody>
            {rows.map(row => (
              <tr key={uniqueId('row_')}>
                {columns.length > 0
                  && columns.map(col => (
                    <td key={uniqueId('td_')}>{row[col.name]}</td>
                  ))}
              </tr>
            ))}
          </tbody>
        )}
      </table>
    </div>
  );
};

SprkTable.propTypes = {
  /** Array used to render the table headings. */
  columns: PropTypes.oneOfType([
    PropTypes.arrayOf(PropTypes.object),
    PropTypes.arrayOf(PropTypes.array),
  ]),
  /** An array of objects used to map and render the table row data. */
  rows: PropTypes.oneOfType([
    PropTypes.arrayOf(PropTypes.object),
    PropTypes.arrayOf(PropTypes.array),
  ]),
  /** Determines what variant of the table should render. */
  variant: PropTypes.oneOf([
    'default',
    'secondary',
    'grouped',
    'rowComparison',
    'secondaryRowComparison',
    'html',
  ]),
  /**
   * The value supplied will be assigned
   * to the `data-id` attribute on the
   * component. This is intended to be
   * used as a selector for automated
   * tools. This value should be unique
   * per page.
   */
  idString: PropTypes.string,
  /**
   * Expects a space separated string
   * of classes to be added to the
   * outermost containers of the component.
   */
  additionalContainerClasses: PropTypes.string,
  /**
   * Expects a space separated string
   * of classes to be added to the
   * table.
   */
  additionalTableClasses: PropTypes.string,
  /**
   * Content to render inside of components.
   * Available only to the `html` variant.
   */
  children: PropTypes.node,
};

SprkTable.defaultProps = {
  columns: [],
  rows: [],
  variant: 'default',
  idString: '',
  additionalContainerClasses: '',
  additionalTableClasses: '',
  children: '',
};

export default SprkTable;
