// react/src/base/inputs/SprkInputContainer/SprkInputContainer.js
import React, { Component } from 'react';
import classNames from 'classnames';
import PropTypes from 'prop-types';
import SprkLabel from '../SprkLabel/SprkLabel';
import SprkInput from '../SprkInput/SprkInput';
import SprkSelect from '../SprkSelect/SprkSelect';
import SprkDatePicker from '../SprkDatePicker/SprkDatePicker';
import SprkErrorContainer from '../SprkErrorContainer/SprkErrorContainer';
import SprkFieldError from '../SprkFieldError/SprkFieldError';
import SprkHelperText from '../SprkHelperText/SprkHelperText';

class SprkInputContainer extends Component {
  constructor(props) {
    super(props);
    this.renderChildren = this.renderChildren.bind(this);
  }

  renderChildren() {
    const { children } = this.props;
    let id;
    let labelFor;
    let errorContainerID;
    let helperTextID;
    let inputAriaDescribedBy;
    let inputAriaDescribedByArray = [];

    /*
     * Store references to id, for,
     * errorContainerID and helperTextID.
     */
    React.Children.forEach(children, (child) => {
      if (
        child.type.name === SprkInput.name ||
        child.type.name === SprkSelect.name ||
        child.type.name === SprkDatePicker.name
      ) {
        id = child.props.id;
        inputAriaDescribedBy = child.props.ariaDescribedBy;
      }
      if (child.type.name === SprkLabel.name) {
        labelFor = child.props.htmlFor;
      }
      if (
        child.type.name === SprkFieldError.name ||
        child.type.name === SprkErrorContainer.name
      ) {
        errorContainerID = child.props.id;
      }
      if (child.type.name === SprkHelperText.name) {
        helperTextID = child.props.id;
      }
    });

    /* Check to see if the errorContainerID
     * and helperTextID are in the inputAriaDescribedByArray.
     * If they aren't, add it to the array.
     */
    if (helperTextID || errorContainerID) {
      if (inputAriaDescribedBy) {
        inputAriaDescribedByArray = inputAriaDescribedBy.split(' ');
      }
      if (helperTextID) {
        if (!inputAriaDescribedByArray.includes(helperTextID)) {
          inputAriaDescribedByArray.push(helperTextID);
        }
      }
      if (errorContainerID) {
        if (!inputAriaDescribedByArray.includes(errorContainerID)) {
          inputAriaDescribedByArray.push(errorContainerID);
        }
      }
      inputAriaDescribedBy = inputAriaDescribedByArray.join(' ');
    }

    if (id && labelFor && id.length > 0 && labelFor.length > 0) {
      const childrenElements = React.Children.map(children, (child) => {
        /*
         * If the label for and the input id
         * are mismatching, use the id
         * value to set the `for` attribute on the label.
         * SprkInput and SprkLabel will always have
         * an ID and a for. We check for presence (id="")
         * before checking for length to avoid running
         * .length on undefined.
         */
        if (id !== labelFor) {
          if (child.type.name === SprkLabel.name) {
            return React.cloneElement(child, {
              htmlFor: id,
            });
          }
        }

        /*
         * If there is an inputAriaDescribedBy,
         * add it to the SprkInput element.
         */
        if (
          inputAriaDescribedBy &&
          (child.type.name === SprkInput.name ||
            child.type.name === SprkSelect.name ||
            child.type.name === SprkDatePicker.name)
        ) {
          return React.cloneElement(child, {
            ariaDescribedBy: inputAriaDescribedBy,
          });
        }

        return child;
      });
      return childrenElements;
    }
    // Return other elements ex. <div>
    return children;
  }

  render() {
    const {
      additionalClasses,
      analyticsString,
      children,
      idString,
      variant,
      ...rest
    } = this.props;

    return (
      <div
        data-analytics={analyticsString}
        data-id={idString}
        className={classNames('sprk-b-InputContainer', additionalClasses, {
          'sprk-b-InputContainer--huge': variant === 'huge',
        })}
        {...rest}
      >
        {this.renderChildren()}
      </div>
    );
  }
}

SprkInputContainer.propTypes = {
  /**
   * Determines the style of the input container.
   * Supplying no value will cause
   * the default styles to be used.
   */
  variant: PropTypes.oneOf(['huge']),
  /**
   * A space-separated string of
   * classes to add to the outermost
   * container of the component.
   */
  additionalClasses: PropTypes.string,
  /**
   * Assigned to the `data-analytics`
   * attribute serving as a unique selector
   * for outside libraries to capture data.
   */
  analyticsString: PropTypes.string,
  /**
   * Content to render inside of
   * the component.
   */
  children: PropTypes.node,
  /**
   * Assigned to the `data-id` attribute
   * serving as a unique selector for
   * automated tools.
   */
  idString: PropTypes.string,
};

export default SprkInputContainer;

// angular/projects/spark-angular/src/lib/components/inputs/sprk-input-container/sprk-input-container.component.ts
import {
  Component,
  ContentChild,
  Input,
  OnInit,
  ElementRef,
  Renderer2,
} from '@angular/core';
import { uniqueId } from 'lodash';
import { SprkFieldErrorDirective } from '../../../directives/inputs/sprk-field-error/sprk-field-error.directive';
import { SprkInputDirective } from '../../../directives/inputs/sprk-input/sprk-input.directive';
import { SprkLabelDirective } from '../../../directives/inputs/sprk-label/sprk-label.directive';
import { SprkSelectDirective } from '../../../directives/inputs/sprk-select/sprk-select.directive';

@Component({
  selector: 'sprk-input-container',
  template: `
    <div [ngClass]="getClasses()" [attr.data-id]="idString">
      <ng-content></ng-content>
      <ng-content select="[sprk-select-icon]"></ng-content>
      <ng-content select="[sprk-input-icon]"></ng-content>
      <ng-content select="sprk-selection-item-container"></ng-content>
      <ng-content select="sprk-checkbox-item"></ng-content>
      <ng-content select="[sprkHelperText]"></ng-content>
      <ng-content select="[sprkFieldError]"></ng-content>
      <ng-content select="[afterSprkInput]"></ng-content>
    </div>
  `,
})
export class SprkInputContainerComponent implements OnInit {
  /**
   * @ignore
   */
  constructor(public ref: ElementRef, private renderer: Renderer2) {}
  /**
   * Expects a space separated string
   * of classes to be added to the
   * component.
   */
  @Input()
  additionalClasses: string;
  /**
   * This will be used to determine the variant of
   * the checkbox item.
   */
  @Input()
  variant: 'huge' | undefined;

  /**
   * The value supplied will be assigned
   * to the `data-id` attribute on the
   * component. This is intended to be
   * used as a selector for automated
   * tools. This value should be unique
   * per page.
   */
  @Input()
  idString: string;

  /**
   * This component expects a child label element
   * with the `sprkLabel` directive.
   */
  @ContentChild(SprkLabelDirective, { static: true })
  label: SprkLabelDirective;

  /**
   * This component expects a child input element
   * with the `sprkInput` directive.
   */
  @ContentChild(SprkInputDirective, { static: true })
  input: SprkInputDirective;

  /**
   * This component expects a child input element
   * with the `sprkInput` directive.
   */
  @ContentChild(SprkSelectDirective, { static: true })
  select: SprkSelectDirective;

  /**
   * This component expects a child element
   * with the `sprkFieldError` directive.
   */
  @ContentChild(SprkFieldErrorDirective, { static: true })
  error: SprkFieldErrorDirective;

  /**
   * @ignore
   */
  id = uniqueId();
  /**
   * @ignore
   */
  input_id = `input_${this.id}`;
  /**
   * @ignore
   */
  error_id = `error_${this.id}`;

  /**
   * @ignore
   */
  getClasses(): string {
    const classArray: string[] = ['sprk-b-InputContainer'];

    if (this.additionalClasses) {
      this.additionalClasses.split(' ').forEach((className) => {
        classArray.push(className);
      });
    }

    if (this.variant === 'huge') {
      classArray.push('sprk-b-InputContainer--huge');
    }

    return classArray.join(' ');
  }

  hasID(element): boolean {
    return element.id.length > 0;
  }

  hasFor(element): boolean {
    return element.htmlFor.length > 0;
  }

  hasMatchingForAndID(label, input): boolean {
    if (!this.hasFor(label) || !this.hasID(input)) {
      return;
    }
    return label.htmlFor === input.id;
  }

  ngOnInit(): void {
    const inputEl = this.input || this.select;
    if (!this.label || !inputEl) {
      return;
    }

    /**
     * If the label and the input both do not
     * have a for or id then add custom ones.
     */
    if (
      !this.hasID(inputEl.ref.nativeElement) &&
      !this.hasFor(this.label.ref.nativeElement)
    ) {
      this.renderer.setAttribute(
        this.label.ref.nativeElement,
        'for',
        this.input_id,
      );
      this.renderer.setAttribute(
        inputEl.ref.nativeElement,
        'id',
        this.input_id,
      );
    }

    /**
     * If the input has an id
     * but the label has no for
     * then set the for the match the id.
     */
    if (
      this.hasID(inputEl.ref.nativeElement) &&
      !this.hasFor(this.label.ref.nativeElement)
    ) {
      this.renderer.setAttribute(
        this.label.ref.nativeElement,
        'for',
        inputEl.ref.nativeElement.id,
      );
    }

    /**
     * If the label has a for
     * but the input has no id
     * then set the id the match the for.
     */
    if (
      this.hasFor(this.label.ref.nativeElement) &&
      !this.hasID(inputEl.ref.nativeElement)
    ) {
      this.renderer.setAttribute(
        inputEl.ref.nativeElement,
        'id',
        this.label.ref.nativeElement.htmlFor,
      );
    }

    /**
     * If the label for and the input id
     * are there but mismatching, use the id
     * value for the for attribute on the label.
     * This is because input ids and labels
     * need to match and there is no reason
     * they should not match for a11y.
     */
    if (
      !this.hasMatchingForAndID(
        this.label.ref.nativeElement,
        inputEl.ref.nativeElement,
      )
    ) {
      this.renderer.setAttribute(
        this.label.ref.nativeElement,
        'for',
        inputEl.ref.nativeElement.id,
      );
    }

    /**
     * If there is an error container
     * with an id then match the aria-describedby
     * on the input to the id on the
     * error container.
     */
    if (this.error && this.hasID(this.error.ref.nativeElement)) {
      this.renderer.setAttribute(
        inputEl.ref.nativeElement,
        'aria-describedby',
        this.error.ref.nativeElement.id,
      );
    }

    /**
     * If there is an error container
     * and it does not have an id
     * then use custom id for the
     * error and aria.
     */
    if (this.error && !this.hasID(this.error.ref.nativeElement)) {
      this.renderer.setAttribute(
        inputEl.ref.nativeElement,
        'aria-describedby',
        this.error_id,
      );

      this.renderer.setAttribute(
        this.error.ref.nativeElement,
        'id',
        this.error_id,
      );
    }
  }
}
