// react/src/components/footer/SprkFooter.js
import React, { Component } from 'react';
import classnames from 'classnames';
import PropTypes from 'prop-types';
import uniqueId from 'lodash/uniqueId';
import SprkIcon from '../icons/SprkIcon';
import SprkFooterGlobalSection from './components/SprkFooterGlobalSection/SprkFooterGlobalSection';
import SprkFooterConnectIcons from './components/SprkFooterConnectIcons/SprkFooterConnectIcons';
import SprkFooterAwards from './components/SprkFooterAwards/SprkFooterAwards';

class SprkFooter extends Component {
  constructor(props) {
    super(props);
    const { linkColumns, additionalIcons, paragraphs } = props;
    this.state = {
      linkColumnsHasIds: linkColumns.map(item => ({
        heading: item.heading,
        id: uniqueId(),
        links: item.links.map(link => ({ id: uniqueId(), ...link })),
      })),
      additionalIconsHasIds: additionalIcons.map(icon => ({
        id: uniqueId(),
        ...icon,
      })),
      paragraphsHasIds: paragraphs.map(p => ({ id: uniqueId(), ...p })),
    };
  }

  render() {
    const {
      globalItems,
      connectIcons,
      additionalClasses,
      idString,
      awards,
      paragraphs,
      additionalIcons,
    } = this.props;

    const {
      linkColumnsHasIds,
      additionalIconsHasIds,
      paragraphsHasIds,
    } = this.state;
    const classNames = classnames(
      'sprk-o-Box sprk-o-Box--large sprk-u-BackgroundColor--gray',
      additionalClasses,
    );

    return (
      <div className={classNames}>
        <footer
          className="sprk-o-CenteredColumn sprk-o-Stack sprk-o-Stack--misc-b"
          role="contentinfo"
          data-id={idString}
        >
          <div
            className="sprk-o-Stack__item
              sprk-o-Stack
              sprk-o-Stack--medium
              sprk-o-Stack--split@m"
          >
            {Object.keys(globalItems).length > 1 && (
              <SprkFooterGlobalSection globalItems={globalItems} />
            )}
            <div
              className="sprk-o-Stack__item
                sprk-o-Stack__item--seven-tenths@m
                sprk-o-Stack
                sprk-o-Stack--medium"
            >
              <div
                className="sprk-o-Stack__item
                  sprk-o-Stack
                  sprk-o-Stack--medium
                  sprk-o-Stack--split@m"
              >
                {linkColumnsHasIds.length > 0
                  && linkColumnsHasIds.map(column => (
                    <div
                      key={column.id}
                      className="sprk-o-Stack__item
                        sprk-o-Stack__item--third@m
                        sprk-o-Box
                        sprk-u-PaddingRight--a
                        sprk-o-Stack
                        sprk-o-Stack--large"
                    >
                      <h3 className="sprk-o-Stack__item sprk-b-TypeBodyOne">
                        {column.heading}
                      </h3>

                      <ul className="sprk-o-Stack__item sprk-o-Stack sprk-o-Stack--misc-a sprk-b-List sprk-b-List--bare">
                        {column.links.map((columnLink) => {
                          const {
                            id,
                            href,
                            analyticsString,
                            text,
                            element,
                            ...rest
                          } = columnLink;
                          const TagName = element || 'a';
                          return (
                            <li key={id} className="sprk-o-Stack__item asfsdfasdf">
                              <TagName
                                className="sprk-b-Link sprk-b-Link--simple sprk-u-FontWeight--normal"
                                href={TagName === 'a' ? href || '#nogo' : undefined}
                                data-analytics={analyticsString}
                                {...rest}
                              >
                                {text}
                              </TagName>
                            </li>
                          );
                        })}
                      </ul>
                    </div>
                  ))}
              </div>

              {Object.keys(connectIcons).length > 1 && (
                <SprkFooterConnectIcons connectIcons={connectIcons} />
              )}
            </div>
          </div>

          <span className="sprk-c-Divider sprk-u-mvn sprk-u-mhm" />

          <div
            className="sprk-o-Stack__item
            sprk-o-Stack
            sprk-o-Stack--misc-b
            sprk-o-Box
            sprk-u-PaddingTop--b"
          >
            {Object.keys(awards).length > 1 && (
              <SprkFooterAwards awards={awards} />
            )}

            {paragraphs.length > 0
              && paragraphsHasIds.map(p => (
                <p
                  key={p.id}
                  className="sprk-o-Stack__item sprk-b-TypeBodyFour"
                >
                  {p.text}
                </p>
              ))}

            {additionalIcons.length > 0 && (
              <ul className="sprk-o-Stack__item sprk-o-Stack__item--flex@m sprk-o-Stack sprk-o-Stack--split@xxs sprk-o-Stack--medium sprk-b-List sprk-b-List--bare">
                {additionalIconsHasIds.map((icon) => {
                  const {
                    id,
                    href,
                    analyticsString,
                    name,
                    addClasses,
                    screenReaderText,
                    element,
                    ...rest
                  } = icon;
                  const TagName = element || 'a';
                  return (
                    <li key={id} className="sprk-o-Stack__item">
                      <TagName
                        className="sprk-b-Link sprk-b-Link--plain"
                        href={TagName === 'a' ? href || '#nogo' : undefined}
                        data-analytics={analyticsString}
                        {...rest}
                      >
                        <SprkIcon
                          iconName={name}
                          additionalClasses={`sprk-c-Icon--stroke-current-color sprk-c-Icon--l ${
                            addClasses
                          }`}
                        />
                        <span className="sprk-u-ScreenReaderText">{screenReaderText}</span>
                      </TagName>
                    </li>
                  );
                })}
              </ul>
            )}
          </div>
        </footer>
      </div>
    );
  }
}

SprkFooter.defaultProps = {
  additionalClasses: '',
  idString: '',
  globalItems: {},
  linkColumns: [],
  connectIcons: {},
  awards: {},
  additionalIcons: [],
  paragraphs: [],
};

SprkFooter.propTypes = {
  /**
   * Expects a space separated string
   * of classes to be added to the
   * component.
   */
  additionalClasses: PropTypes.string,
  /**
   * Assigned to the `data-id` attribute serving as a unique selector for automated tools.
   */
  idString: PropTypes.string,
  /** Object used to configure the global items section. */
  globalItems: PropTypes.shape({
    /** Main headline for the global section. */
    heading: PropTypes.string,
    /** Object used to configure each item in global items section such as `mediaType`, `src`, `description` etc. */
    items: PropTypes.arrayOf(
      PropTypes.shape({
        /** The type of media element to render. */
        mediaType: PropTypes.oneOf(['image', 'svg', 'SprkIcon']),
        /**
         * Assigned to `src` attribute of the item's image.
         */
        src: PropTypes.string,
        /**
         * Assigned to `href` of item.
         */
        mediaHref: PropTypes.string,
        /**
         * The `alt` text for the image, icon, or `SprkIcon`.
         */
        altText: PropTypes.string.isRequired,
        /**
         * Expects a space separated string
         * of classes to be added to the
         * media of the item.
         */
        mediaAddClasses: PropTypes.string,
        /** The description of the image */
        description: PropTypes.string,
        /**
         * The value supplied will be assigned to the
         * `data-analytics` attribute on the component.
         * Intended for an outside
         * library to capture data.
         */
        analyticsString: PropTypes.string,
        /**
         * Determines if link renders as an anchor tag, or router link.
         */
        element: PropTypes.oneOfType([PropTypes.string, PropTypes.func]),
      }),
    ),
  }),
  /** Constructs the columns of links in the Footer. Maximum number of columns is 3. */
  linkColumns: PropTypes.arrayOf(
    PropTypes.shape({
      /** The main headline for the column. */
      heading: PropTypes.string,
      /**  The links for each column. */
      links: PropTypes.arrayOf(
        PropTypes.shape({
          /**
           * The link `href`.
          */
          href: PropTypes.string,
          /**
           * The link text.
           */
          text: PropTypes.string,
          /**
           * Determines if link renders as an anchor tag, or router link.
           */
          element: PropTypes.oneOfType([PropTypes.string, PropTypes.func]),
          /**
           * The value supplied will be assigned to the
           * `data-analytics` attribute on the component.
           * Intended for an outside
           * library to capture data.
           */
          analyticsString: PropTypes.string,
        }),
      ),
    }),
  ),
  /** Constructs the Connect Icon Section. */
  connectIcons: PropTypes.shape({
    /** The main headline for the section. */
    heading: PropTypes.string,
    /** Configures the icons for the section. */
    icons: PropTypes.arrayOf(
      PropTypes.shape({
        /** The link `href` for the icon. */
        href: PropTypes.string,
        /** Determines what icon `SprkIcon` renders */
        name: PropTypes.string,
        /** Text used for screen readers. */
        screenReaderText: PropTypes.string,
        /**
         * The value supplied will be assigned to the
         * `data-analytics` attribute on the component.
         * Intended for an outside
         * library to capture data.
         */
        analyticsString: PropTypes.string,
        /**
         * Determines if link renders as an anchor tag, or router link.
         */
        element: PropTypes.oneOfType([PropTypes.string, PropTypes.func]),
      }),
    ),
  }),
  /** Configures the Awards Section. */
  awards: PropTypes.shape({
    /** The main headline for the section. */
    heading: PropTypes.string,
    /** Configures the images in the Awards Section. */
    images: PropTypes.arrayOf(
      PropTypes.shape({
        /** The link href for the image. */
        href: PropTypes.string,
        /**
         * Determines if link renders as an anchor tag, or router link.
         */
        element: PropTypes.oneOfType([PropTypes.string, PropTypes.func]),
        /**
         * The image `src`.
         */
        src: PropTypes.string,
        /**
         * The `alt` text for the image, icon, or `SprkIcon`.
         */
        altText: PropTypes.string.isRequired,
        /**
         * Expects a space separated string of
         * classes to be added to the award image.
         */
        addClasses: PropTypes.string,
       /**
        * The value supplied will be assigned to the
        * `data-analytics` attribute on the component.
        * Intended for an outside
        * library to capture data.
        */
        analyticsString: PropTypes.string,
      }),
    ),
    /** The text rendered in the disclaimer. */
    disclaimerText: PropTypes.string,
    /**
     * The value supplied will be assigned to the
     * `data-analytics` attribute on the disclaimer.
     * Intended for an outside
     * library to capture data.
     */
    disclaimerAnalytics: PropTypes.string,
    /** The title text rendered in the disclaimer. */
    disclaimerTitle: PropTypes.string,
  }),
  /** Configuration used for additional icons at bottom of footer. */
  additionalIcons: PropTypes.arrayOf(
    PropTypes.shape({
      /** The icon name `SprkIcon` will use to render. */
      name: PropTypes.string,
      /** The icon `href`. */
      href: PropTypes.string,
      /**
       * Expects a space separated string of
       * classes to be added to the icon.
       */
      addClasses: PropTypes.string,
      /** Text used for screen readers. */
      screenReaderText: PropTypes.string,
      /**
       * Determines if link renders as an anchor tag, or router link.
       */
      element: PropTypes.oneOfType([PropTypes.string, PropTypes.func]),
      /**
       * The value supplied will be assigned to the
       * `data-analytics` attribute on the component.
       * Intended for an outside
       * library to capture data.
       */
      analyticsString: PropTypes.string,
    }),
  ),
  /** Configuration for the paragraphs of copyright info, etc. */
  paragraphs: PropTypes.arrayOf(
    PropTypes.shape({
      /**
       * The text to render in the paragraphs section.
       */
      text: PropTypes.string,
    }),
  ),
};

export default SprkFooter;

// angular/projects/spark-angular/src/lib/components/sprk-footer/sprk-footer.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'sprk-footer',
  template: `
    <div class="sprk-o-Box sprk-o-Box--large sprk-u-BackgroundColor--gray">
      <footer
        [ngClass]="getClasses()"
        role="contentinfo"
        [attr.data-id]="idString"
      >
        <div
          class="sprk-o-Stack__item sprk-o-Stack sprk-o-Stack--medium sprk-o-Stack--split@m"
        >
          <div
            *ngIf="globalLinks"
            class="sprk-o-Stack__item sprk-o-Stack__item--three-tenths@m sprk-o-Stack sprk-o-Stack--misc-b sprk-o-Box sprk-u-prh"
          >
            <h3 class="sprk-o-Stack__item sprk-b-TypeBodyOne">
              {{ globalHeading }}
            </h3>

            <div
              *ngFor="let item of globalLinks"
              class="sprk-o-Stack__item sprk-o-Stack sprk-o-Stack--medium"
            >
              <div class="sprk-o-Stack__item">
                <sprk-link
                  linkType="plain"
                  href="{{ item.href }}"
                  analyticsString="{{ item.analytics || item.analyticsString }}"
                >
                  <sprk-icon
                    *ngIf="item.icon"
                    iconType="{{ item.icon }}"
                    additionalClasses="{{ item.iconCSS }}"
                  ></sprk-icon>
                  <span *ngIf="item.icon" class="sprk-u-ScreenReaderText">{{
                    item.iconScreenReaderText
                  }}</span>
                  <img
                    *ngIf="item.imgSrc"
                    src="{{ item.imgSrc }}"
                    alt="{{ item.imgAlt }}"
                    class="{{ item.imgCSS }}"
                  />
                </sprk-link>
              </div>

              <p class="sprk-o-Stack__item sprk-b-TypeBodyFour">
                {{ item.text }}
              </p>
            </div>
          </div>

          <div
            class="sprk-o-Stack__item sprk-o-Stack__item--seven-tenths@m sprk-o-Stack sprk-o-Stack--medium"
          >
            <div
              *ngIf="localLinks"
              class="sprk-o-Stack__item sprk-o-Stack sprk-o-Stack--medium sprk-o-Stack--split@m"
            >
              <div
                *ngFor="let item of localLinks"
                class="sprk-o-Stack__item sprk-o-Stack__item--third@m sprk-o-Box sprk-u-PaddingRight--a sprk-o-Stack sprk-o-Stack--large"
              >
                <h3 class="sprk-o-Stack__item sprk-b-TypeBodyOne">
                  {{ item.heading }}
                </h3>

                <ul
                  class="sprk-o-Stack__item sprk-o-Stack sprk-o-Stack--misc-a sprk-b-List sprk-b-List--bare"
                >
                  <li
                    class="sprk-o-Stack__item"
                    *ngFor="let link of item.links"
                  >
                    <sprk-link
                      linkType="simple"
                      additionalClasses="sprk-u-FontWeight--normal"
                      href="{{ link.href }}"
                      analyticsString="{{ link.analyticsString || link.analytics }}"
                    >
                      {{ link.text }}
                    </sprk-link>
                  </li>
                </ul>
              </div>
            </div>

            <div
              *ngIf="socialLinks"
              class="sprk-o-Stack__item sprk-o-Stack sprk-o-Stack--large sprk-o-Box"
            >
              <h3 class="sprk-o-Stack__item sprk-b-TypeBodyOne">
                {{ connectHeading }}
              </h3>

              <div
                class="sprk-o-Stack__item sprk-o-Stack sprk-o-Stack--large sprk-o-Stack--split@m"
              >
                <ul
                  *ngIf="socialLinks"
                  class="
                    sprk-o-Stack__item
                    sprk-o-Stack__item--flex@m
                    sprk-o-Stack
                    sprk-o-Stack--split@xxs
                    sprk-o-Stack--medium
                    sprk-b-List
                    sprk-b-List--bare"
                >
                  <li
                    *ngFor="let item of socialLinks"
                    class="sprk-o-Stack__item"
                  >
                    <sprk-link
                      linkType="plain"
                      href="{{ item.href }}"
                      analyticsString="{{ item.analytics || item.analyticsString }}"
                    >
                      <sprk-icon
                        *ngIf="item.icon"
                        iconType="{{ item.icon }}"
                        additionalClasses="{{ item.iconCSS }}"
                      ></sprk-icon>
                      <span *ngIf="item.icon" class="sprk-u-ScreenReaderText">{{
                        item.iconScreenReaderText
                      }}</span>
                    </sprk-link>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>

        <span
          class="sprk-c-Divider sprk-u-mvn sprk-u-mhm"
          data-id="divider-1"
        ></span>

        <div
          class="sprk-o-Stack__item sprk-o-Stack sprk-o-Stack--misc-b sprk-o-Box sprk-u-PaddingTop--b"
        >
          <div
            *ngIf="awards"
            class="sprk-o-Stack__item sprk-o-Stack sprk-o-Stack--large"
          >
            <h3 class="sprk-o-Stack__item sprk-b-TypeBodyOne">
              {{ awardsHeading }}
            </h3>

            <div
              class="sprk-o-Stack__item sprk-o-Stack sprk-o-Stack--medium sprk-o-Stack--split@s sprk-u-mbm"
            >
              <div class="sprk-o-Stack__item" *ngFor="let award of awards">
                <sprk-link
                  additionalClasses="sprk-o-Stack__item"
                  href="{{ award.href }}"
                  analyticsString="{{ award.analytics || award.analyticsString }}"
                >
                  <img
                    *ngIf="award.imgSrc"
                    src="{{ award.imgSrc }}"
                    alt="{{ award.imgAlt }}"
                    class="{{ award.imgCSS }}"
                  />
                </sprk-link>
              </div>
            </div>

            <div
              *ngFor="let toggle of disclaimerToggle"
              class="sprk-o-Stack__item"
            >
              <sprk-toggle
                title="{{ toggle.title }}"
                analyticsString="{{ toggle.analytics || toggle.analyticsString }}"
                iconClass="sprk-c-Icon--stroke-current-color"
                titleFontClass="sprk-b-TypeBodyFour"
              >
                <p class="sprk-b-TypeBodyFour">{{ toggle.body }}</p>
              </sprk-toggle>
            </div>
          </div>

          <div
            *ngIf="disclaimerText"
            class="sprk-o-Stack__item sprk-o-Stack sprk-o-Stack--large"
          >
            <p
              *ngFor="let disclaimer of disclaimerText"
              class="sprk-o-Stack__item sprk-b-TypeBodyFour"
            >
              {{ disclaimer.text }}
            </p>
          </div>

          <ul
            *ngIf="badgeLinks"
            class="
              sprk-o-Stack__item
              sprk-o-Stack__item--flex@m
              sprk-o-Stack
              sprk-o-Stack--split@xxs
              sprk-o-Stack--medium
              sprk-b-List
              sprk-b-List--bare"
          >
            <li *ngFor="let item of badgeLinks" class="sprk-o-Stack__item">
              <sprk-link
                linkType="plain"
                href="{{ item.href }}"
                analyticsString="{{ item.analytics || item.analyticsString }}"
              >
                <sprk-icon
                  *ngIf="item.icon"
                  iconType="{{ item.icon }}"
                  additionalClasses="{{ item.iconCSS }}"
                ></sprk-icon>
                <span *ngIf="item.icon" class="sprk-u-ScreenReaderText">{{
                  item.iconScreenReaderText
                }}</span>
              </sprk-link>
            </li>
          </ul>
        </div>
      </footer>
    </div>
  `
})
export class SprkFooterComponent {
  /**
   * Expects a space separated string
   * of classes to be added to the
   * component.
   */
  @Input()
  additionalClasses: string;
  /**
   * The value supplied will be assigned
   * to the `data-id` attribute on the
   * component. This is intended to be
   * used as a selector for automated
   * tools. This value should be unique
   * per page.
   */
  @Input()
  idString: string;
  /**
   * The heading for the "Global" section.
   */
  @Input()
  globalHeading: string;
  /**
   * The heading for the "Awards" section.
   */
  @Input()
  awardsHeading: string;
  /**
   * The heading for the "Connect With Us" section.
   */
  @Input()
  connectHeading: string;
  /**
   * Array of objects to build the links in the "Global" section.
   */
  @Input()
  globalLinks: object[];
  /**
   * Array of objects to build the links in the "Site Links" section.
   */
  @Input()
  localLinks: object[];
  /**
   * Array of objects to build the
   * icon links in the "Connect With Us section".
   */
  @Input()
  socialLinks: object[];
  /**
   * Array of objects to build the
   * awards in the "Awards".
   */
  @Input()
  awards: object[];
  /**
   * Array of objects to build the
   * icon links in the icon sectin in the bottom
   * of the Footer.
   */
  @Input()
  badgeLinks: object[];
  /**
   * Array of objects
   * to build disclaimer text in the bottom
   * of the Footer.
   */
  @Input()
  disclaimerText: object[];
  /**
   * Array of objects to build
   * the disclamer toggle(s) in
   * the bottom of the Footer.
   */
  @Input()
  disclaimerToggle: object[];

  /**
   * @ignore
   */
  getClasses(): string {
    const classArray: string[] = [
      'sprk-o-CenteredColumn sprk-o-Stack sprk-o-Stack--misc-b'
    ];

    if (this.additionalClasses) {
      this.additionalClasses.split(' ').forEach(className => {
        classArray.push(className);
      });
    }

    return classArray.join(' ');
  }
}
