// angular/projects/spark-angular/src/lib/components/sprk-promo/sprk-promo.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'sprk-promo',
  template: `
    <div [ngClass]="getClasses()" [attr.data-id]="idString">
      <a
        sprkLink
        variant="unstyled"
        *ngIf="isFlag && !mediaRev"
        [ngClass]="getClassesFlag()"
        [attr.href]="imgHref"
        [analyticsString]="flagLinkAnalytics"
      >
        <img
          class="sprk-c-Promo__image--flag"
          alt="{{ imgAlt }}"
          src="{{ imgSrc }}"
        />
      </a>
      <a
        sprkLink
        variant="unstyled"
        *ngIf="imgSrc && !mediaRev && !isFlag"
        [attr.href]="imgHref"
        [analyticsString]="imgLinkAnalytics"
        [ngClass]="getClassesImg()"
      >
        <img
          class="sprk-c-Promo__image"
          alt="{{ imgAlt }}"
          src="{{ imgSrc }}"
        />
      </a>

      <div [ngClass]="getClassesContent()">
        <h3
          *ngIf="title"
          class="sprk-b-TypeDisplayFive sprk-o-Stack__item sprk-c-Promo__title"
        >
          {{ title }}
        </h3>

        <div *ngIf="subtitle" class="sprk-c-Promo__subtitle sprk-o-Stack__item">
          {{ subtitle }}
        </div>

        <div class="sprk-b-TypeBodyTwo sprk-o-Stack__item">
          <ng-content></ng-content>
        </div>

        <div *ngIf="cta === 'button'" class="sprk-o-Stack__item">
          <a
            sprkLink
            variant="unstyled"
            [attr.href]="buttonHref"
            class="sprk-c-Button"
            [analyticsString]="buttonLinkAnalytics"
          >
            {{ ctaText }}
          </a>
        </div>

        <a
          sprkLink
          variant="simple"
          *ngIf="cta === 'link'"
          [attr.href]="ctaLinkHref"
          class="sprk-o-Stack__item"
          [analyticsString]="ctaLinkAnalytics"
        >
          {{ ctaText }}
        </a>
      </div>

      <a
        sprkLink
        variant="unstyled"
        *ngIf="isFlag && mediaRev"
        [attr.href]="imgHref"
        [ngClass]="getClassesFlag()"
        [analyticsString]="flagLinkAnalytics"
      >
        <img
          class="sprk-c-Promo__image--flag"
          alt="{{ imgAlt }}"
          src="{{ imgSrc }}"
        />
      </a>

      <a
        sprkLink
        variant="unstyled"
        *ngIf="imgSrc && mediaRev && !isFlag"
        [attr.href]="imgHref"
        [analyticsString]="imgLinkAnalytics"
        [ngClass]="getClassesImg()"
      >
        <img
          class="sprk-c-Promo__image"
          alt="{{ imgAlt }}"
          src="{{ imgSrc }}"
        />
      </a>
    </div>
  `
})
export class SprkPromoComponent {
  /**
   * The main heading on the Promo.
   */
  @Input()
  title: string;
  /**
   * If supplied, this will be used as the
   * text for a subtitle.
   */
  @Input()
  subtitle: string;
  /**
   * Can be `link` or `button`.
   * This determines the type for the call to action in the Promo body.
   */
  @Input()
  cta: string;
  /**
   * This determines the text for the call to action.
   */
  @Input()
  ctaText: string;
  /**
   * This will be the `href` for the button
   * if `cta` is set to `button`.
   */
  @Input()
  buttonHref: string;
  /**
   * The value supplied will be assigned to the
   * `data-analytics` attribute on the
   * call-to-action button if `cta` is set to `button`.
   * This is intended for an outside library to capture data.
   */
  @Input()
  buttonLinkAnalytics: string;
  /**
   * This will be the href for the the link if `cta` is set to `link`.
   */
  @Input()
  ctaLinkHref: string;
  /**
   * The value supplied will be assigned to
   * the `data-analytics` attribute on the
   * call-to-action link if `cta` is set to
   * `link`. This is intended for an
   * outside library to capture data.
   */
  @Input()
  ctaLinkAnalytics: string;
  /**
   * Expects a space separated string
   * of classes to be added to the
   * component.
   */
  @Input()
  additionalClasses: string;
  /**
   * Expects a space separated string
   * of classes to be added to the
   * content container.
   */
  @Input()
  additionalClassesContent: string;
  /**
   * If `true`, the Flag Promo variant will be rendered.
   */
  @Input()
  isFlag: boolean;
  /**
   * Expects a space separated string
   * of classes to be added to the
   * link surrounding the image in the Flag variant.
   */
  @Input()
  additionalClassesFlagLink: string;
  /**
   * If `isFlag` is set to `true`,
   * the Promo will render with
   * an anchor element containing the
   * image specified in `imgSrc`. The value
   * supplied here will be assigned to the `data-analytics`
   * attribute on that anchor element.
   * This is intended for an outside library to capture data.
   */
  @Input()
  flagLinkAnalytics: string;
  /**
   * The source value for the Promo image.
   */
  @Input()
  imgSrc: string;
  /**
   * The `alt` text for the Promo image.
   */
  @Input()
  imgAlt: string;
  /**
   * The `href` value for the Promo image.
   */
  @Input()
  imgHref: string;
  /**
   * If `imgSrc` is true and `isFlag` is `false`,
   * the value supplied will be assigned to
   * the `data-analytics` attribute on the
   * anchor containing the Promo image.
   * This is intended for an outside library to capture data.
   */
  @Input()
  imgLinkAnalytics: string;
  /**
   * If `imgSrc` is true and `isFlag` is false,
   * this string of additional classes will
   * be added to the anchor containing the Promo
   * image. This is intended for overrides.
   */
  @Input()
  additionalClassesImgLink: string;
  /**
   * If `true`, the media will render
   * on the right side of the Promo content.
   */
  @Input()
  mediaRev: boolean;
  /**
   * If `true`, the Promo will be rendered
   * with a border.
   */
  @Input()
  hasBorder: boolean;
  /**
   * The value supplied will be assigned
   * to the `data-id` attribute on the
   * component. This is intended to be
   * used as a selector for automated
   * tools. This value should be unique
   * per page.
   */
  @Input()
  idString: string;

  /**
   * @ignore
   */
  getClasses(): string {
    const classArray: string[] = [
      'sprk-c-Promo',
      'sprk-o-Stack',
      'sprk-o-Stack--split@s'
    ];

    if (this.isFlag) {
      classArray.push('sprk-c-Promo--flag');
    }

    if (this.hasBorder) {
      classArray.push('sprk-c-Promo--bordered');
    }

    if (this.additionalClasses) {
      this.additionalClasses.split(' ').forEach(className => {
        classArray.push(className);
      });
    }
    return classArray.join(' ');
  }

  /**
   * @ignore
   */
  getClassesFlag(): string {
    const classArray: string[] = [
      'sprk-o-Stack__item--fourth@s',
      'sprk-o-Stack__item'
    ];

    if (this.additionalClassesFlagLink) {
      this.additionalClassesFlagLink.split(' ').forEach(className => {
        classArray.push(className);
      });
    }
    return classArray.join(' ');
  }

  /**
   * @ignore
   */
  getClassesImg(): string {
    const classArray: string[] = [
      'sprk-o-Stack__item',
      'sprk-o-Stack__item--half@s'
    ];

    if (this.additionalClassesImgLink) {
      this.additionalClassesImgLink.split(' ').forEach(className => {
        classArray.push(className);
      });
    }
    return classArray.join(' ');
  }

  /**
   * @ignore
   */
  getClassesContent(): string {
    const classArray: string[] = [
      'sprk-c-Promo__content',
      'sprk-o-Stack__item',
      'sprk-o-Stack',
      'sprk-o-Stack--large'
    ];

    if (this.isFlag) {
      classArray.push('sprk-o-Stack__item--three-fourths@s');
    } else {
      if (this.imgSrc) {
        classArray.push('sprk-o-Stack__item--half@s');
      }
    }

    if (this.additionalClassesContent) {
      this.additionalClassesContent.split(' ').forEach(className => {
        classArray.push(className);
      });
    }
    return classArray.join(' ');
  }
}

// spark/components/promo/react/SprkPromo.js
import React from 'react';
import PropTypes from 'prop-types';
import classnames from 'classnames';
import SprkLink from '../SprkLink/SprkLink';
import SprkButton from '../SprkButton/SprkButton';

const SprkPromo = (props) => {
  const {
    title,
    subtitle,
    additionalClasses,
    additionalClassesContent,
    cta,
    ctaText,
    ctaHref,
    ctaAnalytics,
    ctaIdString,
    imgSrc,
    imgAlt,
    imgLinkHref,
    imgLinkAnalytics,
    imgLinkIdString,
    additionalClassesImgLink,
    idString,
    isFlag,
    mediaRev,
    hasBorder,
    children,
    ...other
  } = props;

  return (
    <div
      className={classnames(
        'sprk-c-Promo',
        'sprk-o-Stack',
        { 'sprk-c-Promo--flag': isFlag },
        { 'sprk-c-Promo--bordered': hasBorder },
        additionalClasses,
      )}
      data-id={idString}
      {...other}
    >
      {imgSrc
        && isFlag
        && !mediaRev && (
          <SprkLink
            variant="plain"
            href={imgLinkHref}
            additionalClasses={classnames(
              'sprk-o-Stack__item--fourth@s',
              'sprk-o-Stack__item',
              additionalClassesImgLink,
            )}
            analyticsString={imgLinkAnalytics}
            idString={imgLinkIdString}
          >
            <img
              className="sprk-c-Promo__image--flag"
              alt={imgAlt}
              src={imgSrc}
            />
          </SprkLink>
      )}

      {imgSrc
        && !mediaRev
        && !isFlag && (
          <SprkLink
            variant="plain"
            href={imgLinkHref}
            additionalClasses={classnames(
              'sprk-o-Stack__item',
              'sprk-o-Stack__item--half@s',
              additionalClassesImgLink,
            )}
            analyticsString={imgLinkAnalytics}
            idString={imgLinkIdString}
          >
            <img className="sprk-c-Promo__image" alt={imgAlt} src={imgSrc} />
          </SprkLink>
      )}

      <div
        className={classnames(
          'sprk-c-Promo__content',
          'sprk-o-Stack__item',
          'sprk-o-Stack',
          'sprk-o-Stack--large',
          { 'sprk-o-Stack__item--three-fourths@s': isFlag },
          { 'sprk-o-Stack__item--half@s': imgSrc },
          additionalClassesContent,
        )}
      >
        {title && (
          <h3
            className="
            sprk-b-TypeDisplayFive
            sprk-o-Stack__item
            sprk-c-Promo__title"
          >
            {title}
          </h3>
        )}

        {subtitle && (
          <div className="sprk-c-Promo__subtitle sprk-o-Stack__item">
            {subtitle}
          </div>
        )}

        <div
          className="
          sprk-b-TypeBodyTwo
          sprk-o-Stack__item
          sprk-c-Promo__childrenContainer"
        >
          {children}
        </div>

        {cta === 'button' && (
          <div className="sprk-o-Stack__item">
            <SprkButton
              element="a"
              href={ctaHref}
              analyticsString={ctaAnalytics}
              idString={ctaIdString}
            >
              {ctaText}
            </SprkButton>
          </div>
        )}

        {cta === 'link' && (
          <div className="sprk-o-Stack__item">
            <SprkLink
              variant="base"
              href={ctaHref}
              analyticsString={ctaAnalytics}
              idString={ctaIdString}
            >
              {ctaText}
            </SprkLink>
          </div>
        )}
      </div>

      {isFlag
        && imgSrc
        && mediaRev && (
          <SprkLink
            variant="plain"
            href={imgLinkHref}
            additionalClasses={classnames(
              'sprk-o-Stack__item--fourth@s',
              'sprk-o-Stack__item',
              additionalClassesImgLink,
            )}
            analyticsString={imgLinkAnalytics}
            idString={imgLinkIdString}
          >
            <img
              className="sprk-c-Promo__image--flag"
              alt={imgAlt}
              src={imgSrc}
            />
          </SprkLink>
      )}

      {!isFlag
        && imgSrc
        && mediaRev && (
          <SprkLink
            variant="plain"
            href={imgLinkHref}
            additionalClasses={classnames(
              'sprk-o-Stack__item',
              'sprk-o-Stack__item--half@s',
              additionalClassesImgLink,
            )}
            analyticsString={imgLinkAnalytics}
            idString={imgLinkIdString}
          >
            <img className="sprk-c-Promo__image" alt={imgAlt} src={imgSrc} />
          </SprkLink>
      )}
    </div>
  );
};

SprkPromo.propTypes = {
  // The children that will be rendered inside the content portion of the promo
  children: PropTypes.node,
  // The text to appear in the title section
  title: PropTypes.string,
  // The text to appear in the subtitle section
  subtitle: PropTypes.string,
  // Any additional classes (space-delimited string) to apply to the root
  // element of the Promo
  additionalClasses: PropTypes.string,
  // Any additional classes (space-delimited string) to apply to the content
  // element of the Promo
  additionalClassesContent: PropTypes.string,
  // The type of element to use for the Promo Call-to-Action. If this property
  // is omitted, no Call-to-Action will be rendered.
  cta: PropTypes.oneOf(['button', 'link']),
  // The text to include in the Call-to-Action.
  ctaText: PropTypes.string,
  // The URL to navigate to when the Call-to-Action is clicked.
  ctaHref: PropTypes.string,
  // The string to use for the data-analytics attribute on the Call-to-Action
  ctaAnalytics: PropTypes.string,
  // The string to use for the data-id attribute on the Call-to-Action
  ctaIdString: PropTypes.string,
  // The source location of the Promo image. If this property is omitted, no
  // image will be rendered.
  imgSrc: PropTypes.string,
  // The alt text property for the image
  imgAlt: PropTypes.string,
  // The URL to navigate to when the image is clicked.
  imgLinkHref: PropTypes.string,
  // The string to use for the data-analytics attribute on the image link.
  imgLinkAnalytics: PropTypes.string,
  // The string to use for the data-id attribute on the image link.
  imgLinkIdString: PropTypes.string,
  // Any additional classes (space-delimited string) to apply to the image link.
  additionalClassesImgLink: PropTypes.string,
  // The string to use for the data-id property on the root Promo element.
  idString: PropTypes.string,
  // If provided, the Promo will render as the Flag variant.
  isFlag: PropTypes.bool,
  // If provided, the Promo will be rendered in reverse horizontal order
  // (content on the left, image on the right)
  mediaRev: PropTypes.bool,
  // If provided, the Promo will be rendered with the sprk-c-Promo--bordered
  // class.
  hasBorder: PropTypes.bool,
};

SprkPromo.defaultProps = {
  isFlag: false,
  mediaRev: false,
  hasBorder: false,
};

export default SprkPromo;
