// angular/projects/spark-angular/src/lib/components/sprk-toggle/sprk-toggle.component.ts
import {
  Component,
  Input,
  AfterContentInit,
  Output,
  EventEmitter,
} from '@angular/core';
import { toggleAnimations } from './sprk-toggle-animations';
import { uniqueId } from 'lodash';
import 'focus-visible';

// TODO: Remove `title` in issue #issueNumber
@Component({
  selector: 'sprk-toggle',
  template: `
    <div
      class="sprk-c-Toggle {{ additionalClasses }}"
      [attr.data-id]="idString"
    >
      <button
        variant="icon"
        [ngClass]="getClasses()"
        (click)="toggle($event)"
        [attr.aria-expanded]="isOpen ? 'true' : 'false'"
        [attr.data-analytics]="analyticsString"
        [attr.aria-controls]="contentId"
        type="button"
      >
        <sprk-icon
          [iconName]="iconName"
          [additionalClasses]="getIconClasses()"
        ></sprk-icon>
        {{ triggerText || title }}
      </button>

      <div [@toggleContent]="animState" [id]="contentId">
        <div [ngClass]="getContentClasses()">
          <ng-content></ng-content>
        </div>
      </div>
    </div>
  `,
  animations: [toggleAnimations.toggleContent],
})
export class SprkToggleComponent implements AfterContentInit {
  /**
   * The value supplied will be assigned to the
   * `data-analytics` attribute on the component.
   * Intended for an outside
   * library to capture data.
   */
  @Input()
  analyticsString: string;
  /**
   * Expects a space separated string
   * of classes to be added to the
   * component.
   */
  @Input()
  additionalClasses: string;
  // TODO: Remove `title` in issue #issueNumber
  /**
   * Deprecated - Use `triggerText` instead.
   * The value supplied will be
   * rendered as the main Toggle link text.
   */
  @Input()
  title: string;
  /**
   * The value supplied will be
   * rendered as the main Toggle link text.
   */
  @Input()
  triggerText: string;
  // TODO: Remove `iconClass` in issue #issueNumber
  /**
   * Deprecated - Use `iconAdditionalClasses` instead.
   * The value supplied will be assigned as a
   * CSS class on the icon used in the Toggle.
   * This is intended for overrides.
   */
  @Input()
  iconClass: string;
  /**
   * Expects a space separated string
   * of classes to be added to the
   * icon.
   */
  @Input()
  iconAdditionalClasses: string;
  /**
   * Determines which icon is rendered.
   * Expects the value to match the exact name
   * of the icon found in the docs
   * (i.e. `chevron-down`, instead of `chevron down`).
   */
  @Input()
  iconName = 'chevron-down-circle';
  /**
   * Expects a space separated string
   * of classes to be added to the
   * content.
   */
  @Input()
  contentAdditionalClasses: string;
  // TODO: Remove `titleFontClass` in future issue #issueNumber.
  /**
   * Deprecated - Use `triggerTextAdditionalClasses` instead.
   * The value supplied will be assigned as a CSS class
   * on the clickable title text used in the Toggle.
   * This is intended for overrides.
   */
  @Input()
  titleFontClass = 'sprk-b-TypeBodyThree';
  // TODO: Move the default value from titleFontClass to
  // triggerTextAdditionalClasses in future issue #issueNumber.
  /**
   * Expects a space separated string
   * of classes to be added to the
   * trigger text.
   */
  @Input()
  triggerTextAdditionalClasses: string;
  /**
   * The value supplied will be assigned
   * to the `data-id` attribute on the
   * component. This is intended to be
   * used as a selector for automated
   * tools. This value should be unique
   * per page.
   */
  @Input()
  idString: string;
  /**
   * A string that is used to set the `id` on the content
   * and the `aria-controls` for the toggle trigger button.
   */
  @Input()
  contentId = uniqueId(`sprk_toggle_content_`);
  /**
   * When the toggle is opened this event will be emitted.
   */
  @Output()
  openedEvent = new EventEmitter<any>();
  /**
   * When the toggle is closed this event will be emitted.
   */
  @Output()
  closedEvent = new EventEmitter<any>();
  /**
   * If `true`, the Toggle will be open when rendered.
   */
  @Input()
  isOpen = false;

  /**
   * @ignore
   */
  public iconStateClass = '';
  /**
   * @ignore
   */
  public animState = 'closed';

  /**
   * @ignore
   */
  toggleState(): void {
    if (this.isOpen) {
      this.animState = 'open';
      this.iconStateClass = 'sprk-c-Icon--open';
    } else {
      this.animState = 'closed';
      this.iconStateClass = '';
    }
  }

  /**
   * @ignore
   */
  toggle(event): void {
    event.preventDefault();
    this.isOpen = !this.isOpen;
    if (this.isOpen) {
      this.openedEvent.emit();
    } else {
      this.closedEvent.emit();
    }
    this.toggleState();
  }

  /**
   * @ignore
   */
  // TODO: Remove `titleFontClass` in future issue #issueNumber.
  getClasses(): string {
    const additionalClasses =
      this.triggerTextAdditionalClasses || this.titleFontClass;
    const classArray: string[] = [
      'sprk-c-Toggle__trigger sprk-u-TextCrop--none',
      additionalClasses,
    ];
    return classArray.join(' ');
  }

  /**
   * @ignore
   */
  getIconClasses(): string {
    // TODO: Remove `iconClass` in issue #issueNumber
    const additionalClasses = this.iconAdditionalClasses || this.iconClass;
    const classArray: string[] = [
      'sprk-c-Icon--xl sprk-u-mrs sprk-c-Icon--toggle',
      this.iconStateClass,
    ];
    if (additionalClasses) {
      additionalClasses.split(' ').forEach((className) => {
        classArray.push(className);
      });
    }
    return classArray.join(' ');
  }

  /**
   * @ignore
   */
  getContentClasses(): string {
    const classArray: string[] = [
      'sprk-u-pts sprk-u-pbs sprk-c-Toggle__content',
    ];
    if (this.contentAdditionalClasses) {
      this.contentAdditionalClasses.split(' ').forEach((className) => {
        classArray.push(className);
      });
    }
    return classArray.join(' ');
  }

  ngAfterContentInit() {
    this.toggleState();
  }
}

// react/src/components/toggle/SprkToggle.js
import React, { Component } from 'react';
import AnimateHeight from 'react-animate-height';
import PropTypes from 'prop-types';
import classnames from 'classnames';
import uniqueId from 'lodash/uniqueId';
import SprkIcon from '../icons/SprkIcon';
import 'focus-visible';

class SprkToggle extends Component {
  constructor(props) {
    super(props);
    // TODO: Remove isDefaultOpen in issue #1296
    const { isDefaultOpen, isOpen = isDefaultOpen } = this.props;
    const { contentId = uniqueId('sprk_toggle_content_') } = this.props;

    this.state = {
      isOpen: isOpen || false,
      height: isOpen ? 'auto' : 0,
      uniqueIdentifier: contentId,
    };

    this.toggleOpen = this.toggleOpen.bind(this);
  }

  toggleOpen(e) {
    e.preventDefault();
    this.setState((prevState) => ({
      isOpen: !prevState.isOpen,
      height: !prevState.isOpen ? 'auto' : 0,
    }));
  }

  // TODO: Remove title, titleAddClasses, iconAddClasses in issue #1296
  render() {
    const {
      children,
      idString,
      additionalClasses,
      analyticsString,
      title,
      triggerText = title,
      titleAddClasses,
      triggerTextAdditionalClasses = titleAddClasses,
      iconAddClasses,
      iconAdditionalClasses = iconAddClasses,
      toggleIconName,
      contentId,
      contentAdditionalClasses,
      onClick,
      ...other
    } = this.props;
    const { isOpen, height, uniqueIdentifier } = this.state;

    const containerClasses = classnames('sprk-c-Toggle', additionalClasses);

    const titleClasses = classnames(
      'sprk-c-Toggle__trigger sprk-b-TypeBodyThree sprk-u-TextCrop--none',
      triggerTextAdditionalClasses,
    );
    const iconClasses = classnames(
      'sprk-c-Icon--xl sprk-c-Icon--toggle sprk-u-mrs',
      { 'sprk-c-Icon--open': isOpen },
      iconAdditionalClasses,
    );

    const contentClasses = classnames(
      'sprk-c-Toggle__content',
      contentAdditionalClasses,
    );
    return (
      <div data-id={idString} {...other} className={containerClasses}>
        <button
          className={titleClasses}
          data-analytics={analyticsString}
          onClick={(e) => {
            if (onClick) {
              onClick(e);
            }
            this.toggleOpen(e);
          }}
          aria-expanded={isOpen ? 'true' : 'false'}
          aria-controls={uniqueIdentifier}
          type="button"
        >
          <SprkIcon iconName={toggleIconName} additionalClasses={iconClasses} />
          {triggerText}
        </button>
        <AnimateHeight
          duration={300}
          height={height}
          className={contentClasses}
          id={uniqueIdentifier}
        >
          <div>{children}</div>
        </AnimateHeight>
      </div>
    );
  }
}

SprkToggle.defaultProps = {
  toggleIconName: 'chevron-down-circle',
};

SprkToggle.propTypes = {
  /**
   * 	The name of the icon other than the default to use for the toggle.
   */
  toggleIconName: PropTypes.string,
  /**
   * Deprecated - use `triggerText` instead.
   * The title text for the toggle.
   */
  // TODO: Remove title in issue #1296
  title: PropTypes.string,
  /**
   * The title text for the toggle.
   */
  triggerText: PropTypes.string,
  /** The content that will show up when the toggle opens. */
  children: PropTypes.node.isRequired,
  /**
   * Assigned to the `data-id` attribute serving as
   * a unique selector for automated tools.
   */
  idString: PropTypes.string,
  /**
   * Assigned to the `data-analytics` attribute serving as
   * a unique selector for outside libraries to capture data.
   */
  analyticsString: PropTypes.string,
  /**
   * Deprecated - Use `isOpen` instead.
   * Determines if the toggle is open upon loading on the page.
   */
  // TODO: isDefaultOpen in issue #1296
  isDefaultOpen: PropTypes.bool,
  /** Determines if the toggle is open or closed. */
  isOpen: PropTypes.bool,
  /**
   * A space-separated string of classes to add to the
   * outermost container of the component.
   */
  additionalClasses: PropTypes.string,
  /** Deprecated - Use `triggerTextAdditionalClasses` instead.
   * A space-separated string of classes to add to the title text. */
  // TODO: Remove titleAddClasses in issue #1296
  titleAddClasses: PropTypes.string,
  /** A space-separated string of classes to add to the title text. */
  triggerTextAdditionalClasses: PropTypes.string,
  /** Deprecated - Use `iconAdditionalClasses` instead.
   * A space-separated string of classes to add to the toggle icon. */
  // TODO: Remove iconAddClasses in issue #1296
  iconAddClasses: PropTypes.string,
  /** A space-separated string of classes to add to the toggle icon. */
  iconAdditionalClasses: PropTypes.string,
  /** A space-separated string of classes to add to the content. */
  contentAdditionalClasses: PropTypes.string,
  /**
   * A string that is used to set the `id` on the content
   * and the `aria-controls` for the toggle trigger button.
   */
  contentId: PropTypes.string,
  /** The event that will fire when the toggle trigger is clicked. */
  onClick: PropTypes.func,
};

export default SprkToggle;
