// angular/projects/spark-angular/src/lib/components/sprk-stack/sprk-stack.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'sprk-stack',
  template: `
    <div
      [ngClass]="getClasses()"
      [attr.data-id]="idString"
      [attr.data-analytics]="analyticsString"
    >
      <ng-content></ng-content>
    </div>
  `,
})
export class SprkStackComponent {
  /**
   * The value supplied can be `extraTiny`, `tiny`, `small`, `medium`, `large`, or `huge`.
   * This is used as the breakpoint at which the component moves or "splits"
   * to a side by side layout.
   */
  @Input()
  splitAt: string;
  /**
   * This is used as the amount of spacing between the child `sprkStackItem`
   * items. The value supplied can be `tiny`, `small`, `medium`, `large`, or
   * `huge`.
   */
  @Input()
  itemSpacing: string;
  /**
   * The value supplied will be assigned to the `data-id` attribute on the
   * component. This is intended to be used as a selector for automated tools.
   * This value should be unique per page.
   */
  @Input()
  idString: string;
  /**
   * The value supplied will be assigned to the `data-analytics` attribute on
   * the component. Intended for an outside library to capture data.
   */
  @Input()
  analyticsString: string;
  /**
   * Expects a space separated string of classes to be added to the component.
   */
  @Input()
  additionalClasses: string;

  /**
   * Use in cases of nested Stack components where the Stack is also
   * a Stack item.
   */
  @Input()
  isStackItem: boolean;

  /**
   * @ignore
   */
  getClasses(): string {
    const classArray: string[] = ['sprk-o-Stack'];

    // Handle the choice of item split breakpoint by adding CSS class
    switch (this.splitAt) {
      case 'extraTiny':
        classArray.push('sprk-o-Stack--split@xxs');
        break;
      case 'tiny':
        classArray.push('sprk-o-Stack--split@xs');
        break;
      case 'small':
        classArray.push('sprk-o-Stack--split@s');
        break;
      case 'medium':
        classArray.push('sprk-o-Stack--split@m');
        break;
      case 'large':
        classArray.push('sprk-o-Stack--split@l');
        break;
      case 'huge':
        classArray.push('sprk-o-Stack--split@xl');
        break;
      default:
        break;
    }

    // Handle the choice of item spacing by adding CSS class
    switch (this.itemSpacing) {
      case 'tiny':
        classArray.push('sprk-o-Stack--tiny');
        break;
      case 'small':
        classArray.push('sprk-o-Stack--small');
        break;
      case 'medium':
        classArray.push('sprk-o-Stack--medium');
        break;
      case 'large':
        classArray.push('sprk-o-Stack--large');
        break;
      case 'huge':
        classArray.push('sprk-o-Stack--huge');
        break;
      default:
        break;
    }

    if (this.additionalClasses) {
      this.additionalClasses.split(' ').forEach((className) => {
        classArray.push(className);
      });
    }

    if (this.isStackItem) {
      classArray.push('sprk-o-Stack__item');
    }

    return classArray.join(' ');
  }
}

// react/src/objects/stack/SprkStack.js
import React from 'react';
import PropTypes from 'prop-types';
import classnames from 'classnames';

const SprkStack = (props) => {
  const {
    children,
    itemSpacing,
    splitAt,
    additionalClasses,
    idString,
    analyticsString,
    isStackItem,
    ...other
  } = props;

  const classNames = classnames('sprk-o-Stack', additionalClasses, {
    'sprk-o-Stack--tiny': itemSpacing === 'tiny',
    'sprk-o-Stack--small': itemSpacing === 'small',
    'sprk-o-Stack--medium': itemSpacing === 'medium',
    'sprk-o-Stack--large': itemSpacing === 'large',
    'sprk-o-Stack--huge': itemSpacing === 'huge',
    // TODO deprecate hyphenated in favor of camelCase, Issue 1294
    'sprk-o-Stack--misc-a': itemSpacing === 'miscA' || itemSpacing === 'misc-a',
    'sprk-o-Stack--misc-b': itemSpacing === 'miscB' || itemSpacing === 'misc-b',
    'sprk-o-Stack--misc-c': itemSpacing === 'miscC' || itemSpacing === 'misc-c',
    'sprk-o-Stack--misc-d': itemSpacing === 'miscD' || itemSpacing === 'misc-d',
    'sprk-o-Stack--split@xxs': splitAt === 'extraTiny',
    'sprk-o-Stack--split@xs': splitAt === 'tiny',
    'sprk-o-Stack--split@s': splitAt === 'small',
    'sprk-o-Stack--split@m': splitAt === 'medium',
    'sprk-o-Stack--split@l': splitAt === 'large',
    'sprk-o-Stack--split@xl': splitAt === 'huge',
    'sprk-o-Stack__item': isStackItem,
  });

  return (
    <div
      className={classNames}
      data-id={idString}
      data-analytics={analyticsString}
      {...other}
    >
      {children}
    </div>
  );
};

SprkStack.propTypes = {
  children: PropTypes.node,

  /**
   * Determines when the layout will switch `flex-direction` from `column` to
   * `row` based on breakpoint.
   */
  splitAt: PropTypes.oneOf([
    'extraTiny',
    'tiny',
    'small',
    'medium',
    'large',
    'huge',
    '',
  ]),

  /**
   * Determines spacing between items.
   */
  itemSpacing: PropTypes.oneOf([
    'tiny',
    'small',
    'medium',
    'large',
    'huge',
    'misc-a',
    'misc-b',
    'misc-c',
    'misc-d',
    'miscA',
    'miscB',
    'miscC',
    'miscD',
    '',
  ]),

  /**
   * Assigned to the `data-id` attribute serving as a unique selector for
   * automated tools.
   */
  idString: PropTypes.string,

  /**
   * Assigned to the `data-analytics` attribute serving as a unique selector
   * for outside libraries to capture data.
   */
  analyticsString: PropTypes.string,

  /**
   * A space-separated string of classes to add to the outermost container of
   * the component.
   */
  additionalClasses: PropTypes.string,

  /**
   * Use in cases of nested Stack components where the Stack is also
   * a Stack item.
   */
  isStackItem: PropTypes.bool,
};

export default SprkStack;
