// react/src/components/tabs/SprkTabs.js
/* global window */
import React, { Component } from 'react';
import PropTypes from 'prop-types';
import classnames from 'classnames';
import uniqueId from 'lodash/uniqueId';
import SprkTabsPanel from './components/SprkTabsPanel/SprkTabsPanel';
import SprkTabsButton from './components/SprkTabsButton/SprkTabsButton';

/*
* This component expects SprkTabsPanel children.
* It loops through each provided SprkTabsPanel
* and creates a SprkTabsButton for each tab.
*/
class SprkTabs extends Component {
  constructor(props) {
    super(props);
    this.handleTabClick = this.handleTabClick.bind(this);
    this.handleKeyboardEvent = this.handleKeyboardEvent.bind(this);
    this.updateAriaOrientation = this.updateAriaOrientation.bind(this);
    this.setDefaultActiveTab = this.setDefaultActiveTab.bind(this);
    this.getActiveTabIndex = this.getActiveTabIndex.bind(this);
    this.retreatTab = this.retreatTab.bind(this);
    this.advanceTab = this.advanceTab.bind(this);
    this.tabsContainerRef = React.createRef();
    const { children } = this.props;
    const btnIds = children.map(() => uniqueId('tab-'));
    this.state = { btnIds };
  }

  /*
  * Immediately invoke setDefaultActiveTab()
  * when component is inserted into the tree
  * and update state with the ID of the tab that's active by default.
  * Update aria-orientation and listen for resizes for future updates.
  */
  componentDidMount() {
    const { breakpoint } = this.props;

    this.setDefaultActiveTab();
    this.updateAriaOrientation(window.innerWidth, breakpoint);
    window.addEventListener('resize', () => {
      this.updateAriaOrientation(window.innerWidth, breakpoint);
    });
  }

  /*
  * Find the SprkTabsButton that we want
  * active by default (isDefaultActive would be set on tab panel)
  * and update state with that tab button ID.
  */
  setDefaultActiveTab() {
    const { children } = this.props;
    const { btnIds } = this.state;
    let counter = 0;

    children.forEach((child, index) => {
      if (child.props.isDefaultActive) {
        this.setState({ isActive: btnIds[index] });
      } else {
        counter += 1;
      }

      if (counter === children.length) {
        this.setState({ isActive: btnIds[0] });
      }
    });
  }

  /*
  * Get the index of the active tab
  * by finding it from our state array of btn IDs.
  */
  getActiveTabIndex() {
    const { isActive, btnIds } = this.state;
    let tabIndex;
    btnIds.forEach((id, index) => {
      if (id === isActive) {
        tabIndex = index;
      }
    });
    return tabIndex;
  }

  retreatTab() {
    const { btnIds } = this.state;
    if (this.getActiveTabIndex() - 1 === -1) {
      this.setState({
        isActive: btnIds[btnIds.length - 1],
        isFocused: btnIds[btnIds.length - 1],
      });
    } else {
      const newActiveTabIndex = this.getActiveTabIndex() - 1;
      this.setState({
        isActive: btnIds[newActiveTabIndex],
        isFocused: btnIds[newActiveTabIndex],
      });
    }
  }

  advanceTab() {
    const { btnIds } = this.state;
    if ((this.getActiveTabIndex() + 1) < btnIds.length) {
      const newActiveTabIndex = this.getActiveTabIndex() + 1;
      this.setState({
        isActive: btnIds[newActiveTabIndex],
        isFocused: btnIds[newActiveTabIndex],
      });
    } else {
      this.setState({
        isActive: btnIds[0],
        isFocused: btnIds[0],
      });
    }
  }

  /*
  * Tabs uses arrow keys to move from tab to tab.
  * Depending on the key pressed we need to
  * set a new active tab.
  */
  handleKeyboardEvent(e) {
    const { btnIds } = this.state;
    const keys = {
      end: 35,
      home: 36,
      left: 37,
      right: 39,
    };

    switch (e.keyCode) {
      case keys.left:
        this.retreatTab();
        break;
      case keys.right:
        this.advanceTab();
        break;
      case keys.home:
        this.setState({
          isActive: btnIds[0],
          isFocused: btnIds[0],
        });
        break;
      case keys.end:
        this.setState({
          isActive: btnIds[btnIds.length - 1],
          isFocused: btnIds[btnIds.length - 1],
        });
        break;
      default:
        break;
    }
  }

  /*
  * Switch aria-orientation to vertical on
  * narrow viewports (based on _tabs.scss breakpoint).
  */
  updateAriaOrientation(width, breakpoint) {
    const tabsContainer = this.tabsContainerRef;

    if (width <= breakpoint) {
      tabsContainer.current.setAttribute('aria-orientation', 'vertical');
    } else {
      tabsContainer.current.setAttribute('aria-orientation', 'horizontal');
    }
  }

  /*
  * Get the ID of the clicked tab
  * and update state with the active tab ID.
  */
  handleTabClick(e) {
    const btnTabId = e.currentTarget.id;
    this.setState({ isActive: btnTabId });
  }

  render() {
    const {
      children,
      idString,
      additionalClasses,
      ...other
    } = this.props;

    const buttons = [];
    const panels = [];

    /*
    * Loop through all the SprkTabsPanels and
    * generate a SprkTabsButton for each one.
    * Don't render a SprkTabsButton
    * for an element that is not a SprkTabsPanel.
    */
    const generateTabs = () => {
      children.forEach((tabPanel, index) => {
        const {
          children: tabPanelChildren,
          tabPanelAddClasses,
          tabBtnChildren,
          tabBtnAddClasses,
          tabBtnDataId,
          tabBtnAnalytics,
          tabBtnClickFunc,
        } = tabPanel.props;

        const { isFocused, isActive, btnIds } = this.state;

        if (tabPanel.type.name !== SprkTabsPanel.name) return;

        buttons.push(
          <SprkTabsButton
            key={btnIds[index]}
            isFocused={isFocused === btnIds[index]}
            isActive={isActive === btnIds[index]}
            ariaControls={`target-${btnIds[index]}`}
            ariaSelected={isActive === btnIds[index]}
            tabBtnId={btnIds[index]}
            onTabClick={(e) => {
              this.handleTabClick(e);
              if (tabBtnClickFunc) {
                tabBtnClickFunc();
              }
            }}
            tabBtnAddClasses={tabBtnAddClasses}
            tabBtnChildren={tabBtnChildren}
            tabBtnDataId={tabBtnDataId}
            tabBtnAnalytics={tabBtnAnalytics}
          />,
        );

        panels.push(
          <SprkTabsPanel
            tabBtnId={btnIds[index]}
            key={btnIds[index]}
            ariaControls={`target-${btnIds[index]}`}
            isActive={isActive === btnIds[index]}
            tabPanelAddClasses={tabPanelAddClasses}
          >
            {tabPanelChildren}
          </SprkTabsPanel>,
        );
      });
    };

    generateTabs();

    return (
      <div
        className={classnames('sprk-c-Tabs', additionalClasses)}
        aria-orientation="horizontal"
        data-id={idString}
        ref={this.tabsContainerRef}
        {...other}
      >
        {/* eslint-disable jsx-a11y/interactive-supports-focus */}
        <div
          onKeyDown={this.handleKeyboardEvent}
          className="sprk-c-Tabs__buttons"
          role="tablist"
        >
          { buttons }
        </div>
        { panels }
      </div>
    );
  }
}

SprkTabs.defaultProps = {
  idString: '',
  additionalClasses: '',
  breakpoint: 736,
};

SprkTabs.propTypes = {
  /**
   * The content to render inside of SprkTabsPanel
   */
  children: PropTypes.node.isRequired,
  /**
   * The value supplied will be assigned
   * to the `data-id` attribute on the
   * component. This is intended to be
   * used as a selector for automated
   * tools. This value should be unique
   * per page.
   */
  idString: PropTypes.string,
  /**
   * Expects a space separated string
   * of classes to be added to the
   * component.
   */
  additionalClasses: PropTypes.string,
  /** Breakpoint for the aria-orientation switch from y to x. */
  breakpoint: PropTypes.number,
};

export default SprkTabs;

// angular/projects/spark-angular/src/lib/components/sprk-tabs/sprk-tabs.component.ts
import {
  AfterContentInit,
  Component,
  ContentChildren,
  ElementRef,
  HostListener,
  Input,
  QueryList,
  Renderer2,
} from '@angular/core';
import * as _ from 'lodash';
import { SprkTabsPanelDirective } from '../../directives/tabs/sprk-tabs-panel/sprk-tabs-panel.directive';
import { SprkTabsButtonDirective } from '../../directives/tabs/sprk-tabs-button/sprk-tabs-button.directive';

@Component({
  selector: 'sprk-tabs',
  template: `
    <div [ngClass]="getClasses()" [attr.data-id]="idString">
      <div class="sprk-c-Tabs__buttons" role="tablist">
        <ng-content select="[sprkTabsButton]"></ng-content>
      </div>
      <ng-content select="[sprkTabsPane]"></ng-content>
      <ng-content></ng-content>
    </div>
  `,
})
export class SprkTabsComponent implements AfterContentInit {
  /**
   * Expects a space separated string
   * of classes to be added to the
   * component.
   */
  @Input()
  additionalClasses: string;
  /**
   * The value supplied will be assigned
   * to the `data-id` attribute on the
   * component. This is intended to be
   * used as a selector for automated
   * tools. This value should be unique
   * per page.
   */
  @Input()
  idString: string;
  /**
   * This component expects children `<button>` elements
   * with the `SprkTabsButtonDirective` on them.
   * These serve as the Tabs.
   */
  @ContentChildren(SprkTabsButtonDirective)
  tabs: QueryList<SprkTabsButtonDirective>;
  /**
   * This component expects children `<div>` elements
   * with the `SprkTabsPanelDirective` on them.
   * These serve as the Panels.
   */
  @ContentChildren(SprkTabsPanelDirective)
  panels: QueryList<SprkTabsPanelDirective>;
  /**
   * @ignore
   */
  componentID = _.uniqueId();
  /**
   * @ignore
   */
  activeClass = 'sprk-c-Tabs__button--active';

  /**
   * @ignore
   */
  @HostListener('click', ['$event'])
  onClick($event) {
    if ($event.target.classList.contains('sprk-c-Tabs__button')) {
      const activePanel = this.panels.find((panel) => {
        return (
          panel.ref.nativeElement.id ===
          $event.target.getAttribute('aria-controls')
        );
      });

      this.resetTabs(
        this.tabs.map((tab) => tab.ref.nativeElement),
        this.panels.map((panel) => panel.ref.nativeElement),
        this.activeClass,
      );

      this.setActiveTab(
        $event.target,
        activePanel.ref.nativeElement,
        this.activeClass,
      );
    }
  }

  /**
   * @ignore
   */
  @HostListener('window:resize')
  onResize() {
    this.ariaOrientation(window.innerWidth, this.ref.nativeElement);
  }

  /**
   * @ignore
   */
  @HostListener('keydown', ['$event'])
  onKeydown($event) {
    const isTabsButton = $event.target.classList.contains(
      'sprk-c-Tabs__button',
    );
    if (!isTabsButton) {
      return;
    }

    const keys = {
      end: 35,
      home: 36,
      left: 37,
      up: 38,
      right: 39,
      down: 40,
      tab: 9,
    };

    const tabElements = this.tabs.map((tab) => tab.ref.nativeElement);
    const panelElements = this.panels.map((panel) => panel.ref.nativeElement);

    if ($event.keyCode === keys.left || $event.keyCode === keys.up) {
      this.incrementTab(tabElements, panelElements, this.activeClass, -1);
    } else if ($event.keyCode === keys.right || $event.keyCode === keys.down) {
      this.incrementTab(tabElements, panelElements, this.activeClass, 1);
    } else if ($event.keyCode === keys.tab) {
      if ($event.target.getAttribute('role') === 'tab') {
        $event.preventDefault();
        panelElements[
          this.getActiveTabIndex(tabElements, this.activeClass)
        ].focus();
      }
    } else if ($event.keyCode === keys.home) {
      this.goToEndTab(tabElements, panelElements, this.activeClass, -1);
    } else if ($event.keyCode === keys.end) {
      this.goToEndTab(tabElements, panelElements, this.activeClass, 1);
    }
  }

  /**
   * @ignore
   */
  getClasses(): string {
    const classArray: string[] = ['sprk-c-Tabs'];

    if (this.additionalClasses) {
      this.additionalClasses.split(' ').forEach((className) => {
        classArray.push(className);
      });
    }

    return classArray.join(' ');
  }

  /**
   * @ignore
   */
  getContentRelationships(): void {
    let tabIDs = [];
    let panelIDs = [];

    if (this.tabs && this.panels) {
      this.tabs.forEach((tab, index) => {
        const tabID = `tabs-${this.componentID}-tab-${index}`;
        const panelID = `tabs-${this.componentID}-panel-${index}`;

        this.renderer.setAttribute(tab.ref.nativeElement, 'id', tabID);
        this.renderer.setAttribute(
          tab.ref.nativeElement,
          'aria-controls',
          panelID,
        );
        tabIDs.push(tabID);
        panelIDs.push(panelID);
      });

      tabIDs = tabIDs.reverse();
      panelIDs = panelIDs.reverse();

      this.panels.forEach((panel) => {
        this.renderer.setAttribute(
          panel.ref.nativeElement,
          'id',
          panelIDs.pop(),
        );
        this.renderer.setAttribute(
          panel.ref.nativeElement,
          'aria-labelledby',
          tabIDs.pop(),
        );
      });
    }
  }

  /**
   * @ignore
   */
  ngAfterContentInit(): void {
    // Accounting for dynamic changes in the component
    this.panels.changes.subscribe(() => {
      this.getContentRelationships();
    });

    this.getContentRelationships();
  }

  /**
   * @ignore
   */
  ariaOrientation(width, element) {
    // switch aria-orientation on mobile (based on _tabs.scss breakpoint)
    if (width <= 736) {
      element.setAttribute('aria-orientation', 'vertical');
    } else {
      element.setAttribute('aria-orientation', 'horizontal');
    }
  }

  /**
   * @ignore
   */
  getActiveTabIndex(tabs, activeClass) {
    let activeIndex = null;
    tabs.forEach((tab, index) => {
      if (
        tab.classList.contains(activeClass || 'sprk-c-Tabs__button--active')
      ) {
        activeIndex = index;
      }
    });

    return activeIndex;
  }

  /**
   * @ignore
   */
  resetTabs(tabs, tabpanels, activeClass) {
    tabs.forEach((tab) => {
      tab.classList.remove(activeClass || 'sprk-c-Tabs__button--active');
      tab.removeAttribute('tabindex');
      tab.setAttribute('aria-selected', 'false');
      tabpanels.forEach((panel) => {
        panel.classList.add('sprk-u-HideWhenJs');
      });
    });
  }

  /**
   * @ignore
   */
  incrementTab(tabs, tabpanels, activeClass, direction) {
    let activeIndex = this.getActiveTabIndex(tabs, activeClass);

    let foundNewIndex = false;

    // Start looking for the next available tab
    while (foundNewIndex === false) {
      // if the next tab would be off the left of the tabstrip
      if (activeIndex + direction < 0) {
        // loop to the end and keep looking
        activeIndex = tabs.length;

        // if the next tab would be off the right of the tabstrip
      } else if (activeIndex + direction >= tabs.length) {
        // loop back to the beginning and keep looking
        activeIndex = -1;

        // If the next tab is not disabled
      } else if (!tabs[activeIndex + direction].hasAttribute('disabled')) {
        // move to the next tab
        activeIndex += direction;
        // stop looking for the correct tab
        foundNewIndex = true;
      } else {
        // move to the next tab and keep looking
        activeIndex += direction;
      }
    }

    // deselect all tabs
    this.resetTabs(tabs, tabpanels, activeClass);
    // select the correct tab
    this.setActiveTab(tabs[activeIndex], tabpanels[activeIndex], activeClass);
  }

  /**
   * @ignore
   */
  goToEndTab(tabs, tabpanels, activeClass, direction) {
    let newActiveIndex;

    // if direction is positive, go to the right-most tab
    if (direction > 0) {
      newActiveIndex = tabs.length - 1;

      // else go to the left-most tab
    } else {
      newActiveIndex = 0;
    }

    let foundNewIndex = false;

    // step through the tabs until we find one that isn't disabled
    while (foundNewIndex === false) {
      // if this tab is not disabled
      if (!tabs[newActiveIndex].hasAttribute('disabled')) {
        // stop looking for the correct tab
        foundNewIndex = true;

        // else step one tab away from the end and keep looking
      } else {
        newActiveIndex -= direction;
      }
    }

    this.resetTabs(tabs, tabpanels, activeClass);
    this.setActiveTab(
      tabs[newActiveIndex],
      tabpanels[newActiveIndex],
      activeClass,
    );
  }

  /**
   * @ignore
   */
  setActiveTab(tab, tabpanel, activeClass) {
    tab.classList.add(activeClass || 'sprk-c-Tabs__button--active');
    tab.setAttribute('tabindex', '0');
    tab.setAttribute('aria-selected', 'true');
    if (tabpanel) {
      tabpanel.classList.remove('sprk-u-HideWhenJs');
    }
    tab.focus();
  }

  /**
   * @ignore
   */
  constructor(public ref: ElementRef, private renderer: Renderer2) {
    this.ariaOrientation(window.innerWidth, this.ref.nativeElement);
  }
}
