// react/src/components/promo/SprkPromo.js
import React from 'react';
import PropTypes from 'prop-types';
import classnames from 'classnames';

const SprkPromo = (props) => {
  const {
    additionalClasses,
    idString,
    isFlag,
    hasBorder,
    children,
    ...other
  } = props;

  return (
    <div
      className={classnames(
        'sprk-c-Promo',
        'sprk-o-Stack',
        { 'sprk-c-Promo--flag': isFlag },
        { 'sprk-c-Promo--bordered': hasBorder },
        additionalClasses,
      )}
      data-id={idString}
      {...other}
    >
      {children}
    </div>
  );
};

SprkPromo.propTypes = {
  /**
   * The content to render inside the Promo.
   */
  children: PropTypes.node,
  /**
   * A space-separated string of classes to
   * add to the outermost container of the component.
   */
  additionalClasses: PropTypes.string,
  /**
   * Assigned to the `data-id` attribute serving
   * as a unique selector for automated tools.
   */
  idString: PropTypes.string,
  /**
   * If `true`, the Flag Promo variant styles
   * will be added to the component.
   */
  isFlag: PropTypes.bool,
  /**
   * If `true`, the Promo will be rendered
   * with a border.
   */
  hasBorder: PropTypes.bool,
};

SprkPromo.defaultProps = {
  isFlag: false,
  hasBorder: false,
};

export default SprkPromo;

// angular/projects/spark-angular/src/lib/components/sprk-promo/sprk-promo.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'sprk-promo',
  template: `
    <div [ngClass]="getClasses()" [attr.data-id]="idString">
      <ng-content></ng-content>
    </div>
  `,
})
export class SprkPromoComponent {
  /**
   * Expects a space separated string
   * of classes to be added to the
   * component.
   */
  @Input()
  additionalClasses: string;
  /**
   * If `true`, the Flag Promo variant styles
   * will be added to the component.
   */
  @Input()
  isFlag: boolean;
  /**
   * If `true`, the Promo will be rendered
   * with a border.
   */
  @Input()
  hasBorder: boolean;
  /**
   * The value supplied will be assigned
   * to the `data-id` attribute on the
   * component. This is intended to be
   * used as a selector for automated
   * tools. This value should be unique
   * per page.
   */
  @Input()
  idString: string;

  /**
   * @ignore
   */
  getClasses(): string {
    const classArray: string[] = ['sprk-c-Promo', 'sprk-o-Stack'];

    if (this.isFlag) {
      classArray.push('sprk-c-Promo--flag');
    }

    if (this.hasBorder) {
      classArray.push('sprk-c-Promo--bordered');
    }

    if (this.additionalClasses) {
      this.additionalClasses.split(' ').forEach((className) => {
        classArray.push(className);
      });
    }
    return classArray.join(' ');
  }
}
