// react/src/components/dictionary/SprkDictionary.js
import React from 'react';
import PropTypes from 'prop-types';
import classnames from 'classnames';
import uniqueId from 'lodash/uniqueId';

const SprkDictionary = (props) => {
  const {
    keyValuePairs,
    variant,
    idString,
    additionalClasses,
    ...other
  } = props;

  const classNames = classnames(
    'sprk-c-Dictionary',
    additionalClasses, {
      'sprk-c-Dictionary--striped': variant === 'striped',
    },
  );

  const keyValuePairsMap = Object.keys(keyValuePairs).map(term => (
    <div className="sprk-c-Dictionary__keyvaluepair" key={uniqueId('key-')}>
      <dt className="sprk-c-Dictionary__key sprk-b-Label sprk-b-Label--no-input">{term}</dt>
      <dd className="sprk-c-Dictionary__value">{keyValuePairs[term]}</dd>
    </div>
  ));

  return (
    <div className={classNames} data-id={idString} {...other}>
      <dl className="sprk-c-Dictionary__keyvaluepairs">
        {keyValuePairsMap}
      </dl>
    </div>
  );
};

SprkDictionary.defaultProps = {
  variant: '',
  idString: '',
  additionalClasses: '',
};

SprkDictionary.propTypes = {
  /**
   * The collection of key-value pairs to be rendered
   * into the component.
   */
  keyValuePairs: PropTypes.PropTypes.shape({
    '': '',
  }).isRequired,
  /**
   * Determines the variant of the dictionary component to render.
   * The only available option is `striped`.
   * Supplying no value will cause the base variant to be used.
   */
  variant: PropTypes.oneOf(['striped', '']),
  /**
    * The value supplied will be assigned
    * to the `data-id` attribute on the
    * component. This is intended to be
    * used as a selector for automated
    * tools. This value should be unique
    * per page.
    */
  idString: PropTypes.string,
  /**
    * Expects a space separated string
    * of classes to be added to the
    * component.
    */
  additionalClasses: PropTypes.string,
};

export default SprkDictionary;

// angular/projects/spark-angular/src/lib/components/sprk-dictionary/sprk-dictionary.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'sprk-dictionary',
  template: `
    <div [ngClass]="getClasses()" [attr.data-id]="idString">
      <dl class="sprk-c-Dictionary__keyvaluepairs">
        <div
          *ngFor="let key of objectKeys(data)"
          class="sprk-c-Dictionary__keyvaluepair"
        >
          <dt
            class="sprk-c-Dictionary__key sprk-b-Label sprk-b-Label--no-input"
          >
            {{ key }}
          </dt>
          <dd class="sprk-c-Dictionary__value">{{ data[key] }}</dd>
        </div>
      </dl>
    </div>
  `
})
export class SprkDictionaryComponent {
  /**
   * The collection of key-value pairs to be rendered
   * into the component.
   */
  @Input()
  data: object = {};
  /**
   * Determines the variant of the dictionary component to render.
   * The only available option is `striped`.
   * Supplying no value will cause the base variant to be used.
   */
  @Input()
  dictionaryType = 'base';
  /**
   * Expects a space separated string
   * of classes to be added to the
   * component.
   */
  @Input()
  additionalClasses: string;
  /**
   * The value supplied will be assigned
   * to the `data-id` attribute on the
   * component. This is intended to be
   * used as a selector for automated
   * tools. This value should be unique
   * per page.
   */
  @Input()
  idString: string;
  /**
   * @ignore
   * Used to grab all the keys from
   * objects.
   */
  objectKeys = Object.keys;

  /**
   * @ignore
   */
  getClasses(): string {
    const classArray: string[] = ['sprk-c-Dictionary'];

    if (this.dictionaryType === 'striped') {
      classArray.push('sprk-c-Dictionary--striped');
    }

    if (this.additionalClasses) {
      this.additionalClasses.split(' ').forEach(className => {
        classArray.push(className);
      });
    }

    return classArray.join(' ');
  }
}
