// angular/projects/spark-angular/src/lib/components/sprk-award/sprk-award.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'sprk-award',
  template: `
    <sprk-stack
      itemSpacing="medium"
      additionalClasses="{{ additionalClasses }}"
    >
      <h2
        sprkStackItem
        [attr.data-id]="idString"
        class="
        sprk-o-Stack__item
        sprk-b-TypeDisplayFive
        sprk-b-Measure sprk-b-Measure--narrow
        sprk-u-TextAlign--center
        sprk-o-Stack__item--center-column"
      >
        {{ title }}
      </h2>

      <div sprkStackItem [ngClass]="getClasses()">
        <sprk-link
          linkType="unstyled"
          additionalClasses="sprk-o-Stack__item sprk-o-Stack__item--flex@s sprk-o-Stack"
          [href]="imgOneHref"
          [analyticsString]="analyticsStringImgOne"
        >
          <img
            [ngClass]="getClassesImgOne()"
            alt="{{ imgOneAlt }}"
            src="{{ imgOneSrc }}"
          />
        </sprk-link>

        <sprk-link
          linkType="unstyled"
          additionalClasses="sprk-o-Stack__item sprk-o-Stack__item--flex@s sprk-o-Stack"
          [href]="imgTwoHref"
          [analyticsString]="analyticsStringImgTwo"
        >
          <img
            [ngClass]="getClassesImgTwo()"
            alt="{{ imgTwoAlt }}"
            src="{{ imgTwoSrc }}"
          />
        </sprk-link>
      </div>

      <sprk-toggle
        *ngIf="disclaimer !== 'false'"
        sprkStackItem
        additionalClasses="sprk-o-Stack__item--start-column"
        toggleType="base"
        title="{{ disclaimerTitle }}"
        analyticsString="{{ analyticsStringDisclaimer }}"
      >
        <p class="sprk-b-TypeBodyFour">{{ disclaimerCopy }}</p>
      </sprk-toggle>
    </sprk-stack>
  `,
  styles: ['']
})
export class SprkAwardComponent {
  @Input()
  splitAt: string;
  @Input()
  imgOneAlt: string;
  @Input()
  imgOneHref: string;
  @Input()
  imgTwoHref: string;
  @Input()
  imgTwoAlt: string;
  @Input()
  imgOneSrc: string;
  @Input()
  imgTwoSrc: string;
  @Input()
  analyticsStringImgOne: string;
  @Input()
  analyticsStringImgTwo: string;
  @Input()
  analyticsStringDisclaimer: string;
  /**
   * Expects a space separated string
   * of classes to be added to the
   * component.
   */
  @Input()
  additionalClasses: string;
  /**
   * Expects a space separated string
   * of classes to be added to the
   * first image.
   */
  @Input()
  additionalClassesImgOne: string;
  /**
   * Expects a space separated string
   * of classes to be added to the
   * second image.
   */
  @Input()
  additionalClassesImgTwo: string;
  @Input()
  title: string;
  @Input()
  disclaimerTitle: string;
  @Input()
  disclaimerCopy: string;
  @Input()
  disclaimer: string;
  /**
   * The value supplied will be assigned
   * to the 'data-id' attribute on the
   * component. This is intended to be
   * used as a selector for automated
   * tools. This value should be unique
   * per page.
   */
  @Input()
  idString: string;

  getClasses(): string {
    const classArray: string[] = [
      'sprk-o-Stack sprk-o-Stack--medium sprk-o-Stack__item sprk-o-Stack__item--center-column'
    ];

    // Handle the choice of item split breakpoint by adding CSS class
    switch (this.splitAt) {
      case 'tiny':
        classArray.push('sprk-o-Stack--split@xs');
        break;
      case 'small':
        classArray.push('sprk-o-Stack--split@s');
        break;
      case 'medium':
        classArray.push('sprk-o-Stack--split@m');
        break;
      case 'large':
        classArray.push('sprk-o-Stack--split@l');
        break;
      case 'huge':
        classArray.push('sprk-o-Stack--split@xl');
        break;
      default:
        break;
    }

    return classArray.join(' ');
  }

  getClassesImgOne(): string {
    const classArray: string[] = [
      'sprk-o-Stack__item sprk-o-Stack__item--center-column'
    ];

    if (this.additionalClassesImgOne) {
      this.additionalClassesImgOne.split(' ').forEach(className => {
        classArray.push(className);
      });
    }
    return classArray.join(' ');
  }

  getClassesImgTwo(): string {
    const classArray: string[] = [
      'sprk-o-Stack__item sprk-o-Stack__item--center-column'
    ];

    if (this.additionalClassesImgTwo) {
      this.additionalClassesImgTwo.split(' ').forEach(className => {
        classArray.push(className);
      });
    }
    return classArray.join(' ');
  }
}

// react/src/components/awards/SprkAward.js
import React from 'react';
import classnames from 'classnames';
import PropTypes from 'prop-types';
import uniqueId from 'lodash/uniqueId';
import SprkToggle from '../toggle/SprkToggle';
import SprkStack from '../../objects/stack/SprkStack';

const SprkAward = (props) => {
  const {
    idString,
    additionalClasses,
    heading,
    disclaimerTitle,
    disclaimerText,
    disclaimerAnalytics,
    images,
    splitAt,
    itemSpacing,
  } = props;
  const classNames = classnames('sprk-o-CenteredColumn', additionalClasses);

  return (
    <SprkStack additionalClasses={classNames} idString={idString} itemSpacing={itemSpacing}>
      <h2 className="sprk-o-Stack__item sprk-o-Stack__item--center-column sprk-b-TypeDisplayFive sprk-b-Measure sprk-b-Measure--narrow sprk-u-TextAlign--center">
        {heading}
      </h2>

      <SprkStack additionalClasses="sprk-o-Stack__item sprk-o-Stack__item--center-column" splitAt={splitAt} itemSpacing={itemSpacing}>
        {images.map((image) => {
          const {
            analyticsString,
            href,
            linkAddClasses,
            addClasses,
            alt,
            src,
            element,
            ...rest
          } = image;
          const TagName = element || 'a';
          return (
            <TagName
              className={classnames('sprk-o-Stack__item sprk-o-Stack__item--flex@s sprk-o-Stack', linkAddClasses)}
              href={TagName === 'a' ? href || '#nogo' : undefined}
              data-analytics={analyticsString}
              key={uniqueId('award-img-')}
              {...rest}
            >
              <img
                className={classnames('sprk-o-Stack__item sprk-o-Stack__item--center-column', addClasses)}
                alt={alt}
                src={src}
              />
            </TagName>
          );
        })}
      </SprkStack>

      <SprkToggle title={disclaimerTitle} analyticsString={disclaimerAnalytics} additionalClasses="sprk-o-Stack__item">
        <p className="sprk-b-TypeBodyFour sprk-u-pts sprk-u-pbs">
          {disclaimerText}
        </p>
      </SprkToggle>
    </SprkStack>
  );
};

SprkAward.defaultProps = {
  splitAt: 'small',
  itemSpacing: 'medium',
  additionalClasses: '',
  idString: '',
  heading: '',
  disclaimerText: '',
  disclaimerAnalytics: '',
  disclaimerTitle: '',
};

SprkAward.propTypes = {
  /** Determines the spacing between the items. */
  itemSpacing: PropTypes.string,
  /**
   * Determines when the flex-direction should
   * change to row from column for the images.
   */
  splitAt: PropTypes.string,
  /**
   * Expects a space separated string
   * of classes to be added to the
   * component.
   */
  additionalClasses: PropTypes.string,
  /** Heading text. */
  heading: PropTypes.string,
  /**
   * Assigned to the `data-id` attribute serving as a unique selector for automated tools.
   */
  idString: PropTypes.string,
  /** The image data. */
  images: PropTypes.arrayOf(
    PropTypes.shape({
      /** The link href for the image. */
      href: PropTypes.string,
      /** Element to render, can be 'a' or Link. */
      element: PropTypes.oneOfType([PropTypes.string, PropTypes.func]),
      /** The image src. */
      src: PropTypes.string.isRequired,
      /** The alt text for the image, icon, or SprkIcon. */
      alt: PropTypes.string.isRequired,
      /** Additional classes for the image. */
      addClasses: PropTypes.string,
      /** Additional classes for the link wrapping the image. */
      linkAddClasses: PropTypes.string,
      /** String used for the data-analytics attribute. */
      analyticsString: PropTypes.string,
    }),
  ).isRequired,
  /** The text rendered in the disclaimer. */
  disclaimerText: PropTypes.string,
  /** Used for the data-analytics value on the title. */
  disclaimerAnalytics: PropTypes.string,
  /** The title text rendered in the disclaimer. */
  disclaimerTitle: PropTypes.string,
};

export default SprkAward;
